import { StyleSheet } from "react-native";
import type { Theme } from "../../theme";

export const makeStyles = (theme: Theme) =>
  StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.bg },
  scroll: { padding: 16, paddingBottom: 100 },
  monthHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  monthLabel: { fontSize: 20, fontWeight: "800", color: theme.text, letterSpacing: -0.5 },
  monthNav: { flexDirection: "row", alignItems: "center", gap: 6 },
  viewSwitch: {
    flexDirection: "row",
    backgroundColor: theme.surface,
    borderRadius: theme.radiusSm,
    padding: 3,
    gap: 3,
    marginBottom: 14,
  },
  viewBtn: { flex: 1, paddingVertical: 8, borderRadius: 5, alignItems: "center" },
  viewBtnActive: { backgroundColor: theme.primary },
  viewText: { fontSize: 13, color: theme.textSecondary, fontWeight: "600" },
  viewTextActive: { color: "#fff" },
  weekStrip: { flexDirection: "row", gap: 4 },
  weekDayBtn: {
    flex: 1,
    alignItems: "center",
    gap: 3,
    paddingVertical: 8,
    borderRadius: theme.radiusSm,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  weekDayBtnActive: { backgroundColor: theme.primary, borderColor: theme.primary },
  weekDayName: { fontSize: 10, color: theme.textMuted, fontWeight: "600" },
  weekDayNum: { fontSize: 15, color: theme.text, fontWeight: "700" },
  weekDayActiveText: { color: "#fff" },
  weekCountDot: { width: 5, height: 5, borderRadius: 2.5 },
  weekCountSpacer: { height: 5 },
  hourly: {
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    overflow: "hidden",
  },
  hourRow: {
    flexDirection: "row",
    minHeight: 38,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  hourLabel: {
    width: 56,
    paddingTop: 6,
    paddingHorizontal: 8,
    fontSize: 11,
    color: theme.textMuted,
    textAlign: "right",
  },
  hourCell: {
    flex: 1,
    paddingVertical: 4,
    paddingHorizontal: 6,
    gap: 4,
    borderLeftWidth: 1,
    borderLeftColor: theme.border,
  },
  hourEvent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 6,
    borderLeftWidth: 3,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  hourEventText: { fontSize: 12, color: theme.text, fontWeight: "500" },
  navBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  todayBtn: {
    paddingHorizontal: 12,
    height: 34,
    borderRadius: 8,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  todayText: { color: theme.textSecondary, fontSize: 13, fontWeight: "600" },
  weekRow: { flexDirection: "row", marginBottom: 4 },
  weekday: {
    flex: 1,
    textAlign: "center",
    fontSize: 11,
    fontWeight: "700",
    color: theme.textMuted,
  },
  grid: { flexDirection: "row", flexWrap: "wrap" },
  cell: { width: `${100 / 7}%`, aspectRatio: 1, padding: 2 },
  cellInner: {
    flex: 1,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  cellSelected: { backgroundColor: theme.primary },
  cellToday: { backgroundColor: theme.primaryGlow },
  cellNum: { fontSize: 14, color: theme.text, fontWeight: "500" },
  cellNumMuted: { color: theme.textMuted, opacity: 0.5 },
  cellNumActive: { fontWeight: "700" },
  dots: { flexDirection: "row", gap: 2, height: 5 },
  dayDot: { width: 5, height: 5, borderRadius: 2.5 },
  dayHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 18,
    marginBottom: 10,
  },
  dayTitle: { fontSize: 15, fontWeight: "700", color: theme.text },
  emptyDay: { color: theme.textMuted, fontSize: 13, paddingVertical: 12 },
  event: {
    flexDirection: "row",
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    overflow: "hidden",
  },
  colorBar: { width: 4 },
  eventBody: { flex: 1, padding: 14, gap: 4 },
  eventTitleRow: { flexDirection: "row", alignItems: "center", gap: 5 },
  eventTitle: { fontSize: 15, fontWeight: "600", color: theme.text, flexShrink: 1 },
  eventMeta: { flexDirection: "row", alignItems: "center", gap: 5 },
  eventTime: { fontSize: 12, color: theme.textSecondary },
  eventDesc: { fontSize: 12, color: theme.textMuted },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
  },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.6)", justifyContent: "flex-end" },
  modalScroll: { maxHeight: "90%" },
  modalCard: {
    backgroundColor: theme.bgElevated,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 32,
    gap: 8,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  modalTitle: { fontSize: 18, fontWeight: "700", color: theme.text },
  readOnlyNote: {
    fontSize: 12,
    color: theme.textMuted,
    fontStyle: "italic",
    marginBottom: 4,
  },
  inputDisabled: { opacity: 0.6 },
  label: {
    fontSize: 11,
    fontWeight: "600",
    color: theme.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 6,
  },
  input: {
    backgroundColor: theme.inputBg,
    borderWidth: 1,
    borderColor: theme.inputBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: theme.text,
    fontSize: 15,
  },
  textarea: { minHeight: 70, textAlignVertical: "top" },
  hint: { fontSize: 12, color: theme.textMuted, marginTop: 4 },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
  },
  toggleLabel: { fontSize: 15, color: theme.text, fontWeight: "500" },
  toggle: {
    width: 46,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.surfaceHover,
    padding: 3,
    justifyContent: "center",
  },
  toggleOn: { backgroundColor: theme.primary },
  knob: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#fff",
    alignSelf: "flex-start",
  },
  knobOn: { alignSelf: "flex-end" },
  stepper: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: theme.inputBg,
    borderWidth: 1,
    borderColor: theme.inputBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 8,
  },
  stepBtn: {
    width: 40,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  stepBtnText: { color: theme.primary, fontSize: 24, fontWeight: "600" },
  stepValue: { color: theme.text, fontSize: 15, fontWeight: "600" },
  colorRow: { flexDirection: "row", gap: 10, marginTop: 4 },
  swatch: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 2,
    borderColor: "transparent",
  },
  swatchActive: { borderColor: theme.text },
  submit: {
    backgroundColor: theme.primary,
    borderRadius: theme.radiusSm,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 16,
  },
  submitDisabled: { opacity: 0.4 },
  submitText: { color: "#fff", fontSize: 15, fontWeight: "600" },
  deleteBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    marginTop: 8,
  },
  deleteText: { color: theme.danger, fontSize: 14, fontWeight: "600" },
  // Meeting banner (edit mode, existing meeting event)
  meetingBanner: {
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusSm,
    padding: 12,
    marginTop: 12,
    gap: 8,
  },
  meetingBannerHead: { flexDirection: "row", alignItems: "center", gap: 6 },
  meetingBannerTitle: { fontSize: 14, fontWeight: "700", color: theme.text },
  meetingCodeText: { fontSize: 12, color: theme.textSecondary },
  joinBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: theme.primary,
    borderRadius: theme.radiusSm,
    paddingVertical: 10,
  },
  joinBtnText: { color: "#fff", fontSize: 14, fontWeight: "600" },
  // Add-online-meeting toggle + participant picker (create mode)
  meetingToggleLabel: { flexDirection: "row", alignItems: "center", gap: 8 },
  meetingOptions: { gap: 6, marginTop: 4 },
  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginBottom: 4 },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusFull,
    paddingHorizontal: 10,
    paddingVertical: 5,
    maxWidth: "100%",
  },
  chipConflict: { borderColor: theme.danger },
  chipOptional: { borderStyle: "dashed" },
  chipText: { fontSize: 13, color: theme.text, maxWidth: 140 },
  // Required/Optional target switch for the participant search box.
  pickerTargetRow: {
    flexDirection: "row",
    gap: 6,
    marginTop: 4,
  },
  pickerTargetBtn: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: theme.radiusSm,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    backgroundColor: theme.glass,
    alignItems: "center",
  },
  pickerTargetBtnActive: { backgroundColor: theme.primary, borderColor: theme.primary },
  pickerTargetText: { fontSize: 12, fontWeight: "600", color: theme.textSecondary },
  pickerTargetTextActive: { color: "#fff" },
  // Existing-meeting participant roster (banner).
  rosterWrap: { gap: 8, marginTop: 4 },
  rosterGroup: { gap: 4 },
  rosterGroupLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  rosterChips: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  rosterBadge: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusFull,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  rosterBadgeOptional: { borderStyle: "dashed" },
  rosterBadgeText: { fontSize: 12, color: theme.text },
  resultsList: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusSm,
    marginTop: 4,
    overflow: "hidden",
  },
  resultRow: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  resultName: { fontSize: 14, color: theme.text, fontWeight: "500" },
  resultUser: { fontSize: 12, color: theme.textMuted },
  conflictBox: {
    flexDirection: "row",
    gap: 8,
    backgroundColor: "rgba(224,62,62,0.12)",
    borderWidth: 1,
    borderColor: "rgba(224,62,62,0.35)",
    borderRadius: theme.radiusSm,
    padding: 10,
    marginTop: 6,
  },
  conflictText: { fontSize: 12, color: theme.textSecondary, lineHeight: 17 },
  conflictName: { fontWeight: "700", color: theme.text },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 8,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: theme.inputBorder,
    backgroundColor: theme.inputBg,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxOn: { backgroundColor: theme.primary, borderColor: theme.primary },
  checkMark: { color: "#fff", fontSize: 13, fontWeight: "700" },
  settingText: { fontSize: 14, color: theme.text },
});


