import { StyleSheet } from "react-native";
import type { Theme } from "../src/theme";

export const makeStyles = (theme: Theme) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: theme.bg },
    center: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.bg,
      padding: 24,
    },
    emptyMsg: {
      color: theme.textSecondary,
      fontSize: 14,
      textAlign: "center",
      lineHeight: 20,
    },

    /* Tabs — square segmented control (matches Attendance) */
    tabRow: {
      flexDirection: "row",
      backgroundColor: theme.surface,
      borderRadius: theme.radiusSm,
      padding: 3,
      gap: 3,
      margin: 16,
      marginBottom: 0,
    },
    tab: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
      paddingVertical: 9,
      paddingHorizontal: 2,
      borderRadius: 5,
    },
    tabActive: {
      backgroundColor: theme.primary,
    },
    tabText: { fontSize: 13, fontWeight: "600", color: theme.textSecondary },
    tabTextActive: { color: theme.onAccent },

    tabContent: { padding: 16, gap: 12, paddingBottom: 40 },

    /* Cards */
    card: {
      backgroundColor: theme.glass,
      borderWidth: 1,
      borderColor: theme.glassBorder,
      borderRadius: theme.radiusLg,
      padding: 16,
      gap: 10,
    },
    cardHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    cardHeaderTitle: { flexDirection: "row", alignItems: "center", gap: 8 },
    cardTitle: { fontSize: 14, fontWeight: "700", color: theme.text },
    editBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: theme.radiusSm,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    editBtnText: { fontSize: 12, color: theme.textSecondary },

    detailGrid: { gap: 12 },
    detailItem: { gap: 2 },
    detailLabel: { fontSize: 11, color: theme.textMuted },
    detailValue: { fontSize: 13, fontWeight: "500", color: theme.text },

    /* Forms */
    form: { gap: 12 },
    formHint: { fontSize: 12, color: theme.textMuted, lineHeight: 17 },
    fieldLabel: {
      fontSize: 11,
      color: theme.textSecondary,
      marginBottom: 5,
    },
    input: {
      backgroundColor: theme.inputBg,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      borderRadius: theme.radiusSm,
      paddingHorizontal: 12,
      paddingVertical: 9,
      color: theme.text,
      fontSize: 13,
    },
    toggleRow: { flexDirection: "row", gap: 8 },
    toggleBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      borderWidth: 1,
      borderColor: theme.glassBorder,
      backgroundColor: theme.glass,
      borderRadius: theme.radiusSm,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    toggleBtnActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    toggleText: { fontSize: 12, fontWeight: "600", color: theme.textSecondary },
    toggleTextActive: { color: theme.onAccent },
    formActions: { flexDirection: "row", gap: 10, marginTop: 4 },
    primaryBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: theme.primary,
      borderRadius: theme.radiusSm,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    primaryBtnText: { color: theme.onAccent, fontSize: 13, fontWeight: "600" },
    ghostBtn: {
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: theme.radiusSm,
      paddingHorizontal: 16,
      paddingVertical: 10,
      justifyContent: "center",
    },
    ghostBtnText: { color: theme.textSecondary, fontSize: 13 },
    disabled: { opacity: 0.6 },

    sectionTitle: {
      fontSize: 13,
      fontWeight: "700",
      color: theme.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 0.6,
      marginTop: 6,
    },
    errorText: { color: theme.danger, fontSize: 12 },
    empty: {
      color: theme.textMuted,
      fontSize: 13,
      textAlign: "center",
      paddingTop: 24,
    },

    /* Salary slip cards */
    slipCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: theme.glass,
      borderWidth: 1,
      borderColor: theme.glassBorder,
      borderRadius: theme.radius,
      padding: 14,
    },
    slipBody: { flex: 1, gap: 4 },
    slipMonth: { fontSize: 15, fontWeight: "700", color: theme.text },
    slipMeta: { fontSize: 12, color: theme.textSecondary },
    slipNet: { fontWeight: "700", color: theme.text },
    slipStatusRow: { flexDirection: "row", alignItems: "center", gap: 4 },
    slipStatusText: { fontSize: 11, fontWeight: "600" },
    slipPending: { fontSize: 11, color: theme.textMuted },
    iconBtn: { padding: 6 },

    /* Row cards (dept/team) */
    rowCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: theme.glass,
      borderWidth: 1,
      borderColor: theme.glassBorder,
      borderRadius: theme.radius,
      padding: 14,
    },
    rowIcon: {
      width: 40,
      height: 40,
      borderRadius: 11,
      backgroundColor: theme.primaryGlow,
      alignItems: "center",
      justifyContent: "center",
    },
    rowBody: { flex: 1, gap: 3 },
    rowTitle: { fontSize: 15, fontWeight: "600", color: theme.text },
    rowMeta: { fontSize: 12, color: theme.textSecondary },
    rowSubMeta: { fontSize: 11, color: theme.textMuted },
    countBadge: {
      backgroundColor: theme.primaryGlow,
      borderRadius: theme.radiusFull,
      minWidth: 26,
      paddingHorizontal: 8,
      paddingVertical: 3,
      alignItems: "center",
    },
    countText: {
      color: theme.primaryLight,
      fontSize: 12,
      fontWeight: "700",
    },

    /* Org chart */
    searchBox: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: theme.inputBg,
      borderWidth: 1,
      borderColor: theme.inputBorder,
      borderRadius: theme.radiusSm,
      paddingHorizontal: 12,
      paddingVertical: 4,
    },
    searchInput: { flex: 1, color: theme.text, fontSize: 13, paddingVertical: 6 },
    searchClear: { color: theme.textMuted, fontSize: 14, paddingHorizontal: 4 },

    deptHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
    deptName: { flex: 1, fontSize: 15, fontWeight: "700", color: theme.text },
    teamBlock: {
      gap: 6,
      marginTop: 6,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    teamTitleRow: { flexDirection: "row", alignItems: "center", gap: 5 },
    teamTitle: { fontSize: 13, fontWeight: "600", color: theme.text },
    teamCount: {
      fontSize: 11,
      fontWeight: "700",
      color: theme.primaryLight,
      backgroundColor: theme.primaryGlow,
      borderRadius: theme.radiusFull,
      paddingHorizontal: 6,
      paddingVertical: 1,
    },
    teamLead: { fontSize: 11, color: theme.textMuted },

    chip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: theme.surface,
      borderRadius: theme.radiusSm,
      padding: 8,
    },
    chipAvatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    chipAvatarImg: { width: 32, height: 32, borderRadius: 16 },
    chipAvatarText: { color: "#fff", fontSize: 12, fontWeight: "700" },
    chipBody: { flex: 1, gap: 1 },
    chipName: { fontSize: 13, fontWeight: "600", color: theme.text },
    chipMeta: { fontSize: 11, color: theme.textSecondary },
    chipRole: {
      backgroundColor: theme.primaryGlow,
      borderRadius: theme.radiusFull,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    chipRoleText: {
      color: theme.primaryLight,
      fontSize: 10,
      fontWeight: "600",
      textTransform: "capitalize",
    },

    treeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: theme.glass,
      borderWidth: 1,
      borderColor: theme.glassBorder,
      borderRadius: theme.radiusSm,
      padding: 8,
      marginBottom: 6,
    },
    treeRowHl: { borderColor: theme.primary },
    treeDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.textMuted,
      marginHorizontal: 4,
    },
    treeCount: {
      fontSize: 11,
      fontWeight: "700",
      color: theme.primaryLight,
      backgroundColor: theme.primaryGlow,
      borderRadius: theme.radiusFull,
      paddingHorizontal: 7,
      paddingVertical: 2,
    },
    treeChildren: {
      borderLeftWidth: 1,
      borderLeftColor: theme.border,
      paddingLeft: 6,
    },

    /* Task labels */
    colorRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    colorSwatch: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: "transparent",
    },
    colorSwatchActive: { borderColor: theme.text },
    labelRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      backgroundColor: theme.glass,
      borderWidth: 1,
      borderColor: theme.glassBorder,
      borderRadius: theme.radius,
      padding: 12,
    },
    labelBadge: {
      borderRadius: theme.radiusFull,
      paddingHorizontal: 12,
      paddingVertical: 5,
    },
    labelBadgeText: { color: "#fff", fontSize: 13, fontWeight: "700" },
    labelActions: { flexDirection: "row", gap: 4 },
    labelActionBtn: { padding: 6 },
  });

