import { StyleSheet } from "react-native";
import type { Theme } from "../src/theme";

export const makeStyles = (theme: Theme) =>
  StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.bg },
  container: { padding: 16, gap: 10, paddingBottom: 32 },
  headerCard: {
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusLg,
    padding: 24,
    alignItems: "center",
    gap: 4,
  },
  avatarWrap: { width: 84, height: 84, marginBottom: 8 },
  avatar: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarImg: { width: 84, height: 84, borderRadius: 42 },
  avatarText: { color: "#fff", fontSize: 30, fontWeight: "700" },
  avatarStatus: {
    position: "absolute",
    bottom: 2,
    left: 2,
  },
  avatarEdit: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.primaryDark,
    borderWidth: 2,
    borderColor: theme.bgElevated,
    alignItems: "center",
    justifyContent: "center",
  },
  statusDot: {
    alignItems: "center",
    justifyContent: "center",
  },
  name: { fontSize: 20, fontWeight: "700", color: theme.text },
  username: { color: theme.textSecondary, fontSize: 14 },
  muted: { color: theme.textMuted, fontSize: 13 },
  badges: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusFull,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusBadgeText: { color: theme.text, fontSize: 12, fontWeight: "600" },
  modeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusFull,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  modeBadgeText: { color: theme.textSecondary, fontSize: 12, fontWeight: "600" },
  statusTrigger: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusSm,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  statusTriggerLabel: { flex: 1, color: theme.text, fontWeight: "600", fontSize: 15 },
  autoBadge: {
    backgroundColor: theme.surfaceHover,
    color: theme.textSecondary,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: "hidden",
  },
  statusOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: theme.radiusSm,
  },
  statusOptionActive: { backgroundColor: theme.surfaceHover },
  statusOptionLabel: { flex: 1, color: theme.text, fontSize: 15 },
  invisibleDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: theme.textMuted,
  },
  action: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusSm,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  actionText: { color: theme.text, fontWeight: "500", fontSize: 15, flex: 1 },
  enrolledPill: {
    backgroundColor: "rgba(77, 170, 87, 0.15)",
    borderRadius: theme.radiusFull,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  enrolledPillText: { color: theme.success, fontSize: 11, fontWeight: "700" },
  versionText: { color: theme.textMuted, fontSize: 12, fontWeight: "500" },
  logout: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "rgba(224, 62, 62, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(224, 62, 62, 0.25)",
    borderRadius: theme.radiusSm,
    paddingVertical: 14,
  },
  logoutText: { color: theme.danger, fontWeight: "600", fontSize: 15 },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: theme.bgElevated,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    gap: 6,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  modalTitle: { fontSize: 18, fontWeight: "700", color: theme.text },
  label: {
    fontSize: 11,
    fontWeight: "600",
    color: theme.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 8,
    marginBottom: 6,
  },
  input: {
    backgroundColor: theme.inputBg,
    borderWidth: 1,
    borderColor: theme.inputBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: theme.text,
    fontSize: 15,
  },
  submit: {
    backgroundColor: theme.primary,
    borderRadius: theme.radiusSm,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 16,
  },
  submitDisabled: { opacity: 0.5 },
  submitText: { color: "#fff", fontSize: 15, fontWeight: "600" },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingVertical: 2,
  },
  switch: {
    width: 44,
    height: 26,
    borderRadius: 13,
    backgroundColor: theme.surfaceHover,
    padding: 3,
    justifyContent: "center",
  },
  switchOn: { backgroundColor: theme.primary },
  knob: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#fff",
  },
  knobOn: { alignSelf: "flex-end" },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusFull,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipActive: { backgroundColor: theme.primaryGlow, borderColor: theme.primary },
  chipText: { color: theme.textSecondary, fontSize: 13, textTransform: "capitalize" },
  chipTextActive: { color: theme.primaryLight, fontWeight: "600" },
  soundScroll: { maxHeight: 560 },
  soundContent: { gap: 14, paddingBottom: 6 },
  soundSection: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
  },
  sectionTitle: {
    fontSize: 12,
    color: theme.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontWeight: "700",
  },
  toneHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  toneRow: { gap: 8 },
  toneLabel: { fontSize: 13, color: theme.text, fontWeight: "600" },
  previewBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: theme.primary + "55",
    borderRadius: theme.radiusFull,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: theme.primaryGlow,
  },
  previewBtnDisabled: {
    borderColor: theme.glassBorder,
    backgroundColor: theme.surfaceHover,
  },
  previewBtnText: { color: theme.primaryLight, fontSize: 12, fontWeight: "700" },
  previewBtnTextDisabled: { color: theme.textMuted },
  resetBtn: {
    borderWidth: 1,
    borderColor: theme.glassBorder,
    backgroundColor: theme.surfaceHover,
    paddingVertical: 10,
    borderRadius: theme.radiusSm,
    alignItems: "center",
  },
  resetBtnText: { color: theme.textSecondary, fontWeight: "600", fontSize: 13 },
});

