import { StyleSheet } from "react-native";
import type { Theme } from "../src/theme";

export const makeStyles = (theme: Theme) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: theme.bg },
    center: { flex: 1, alignItems: "center", justifyContent: "center" },
    tabRow: {
      flexDirection: "row",
      backgroundColor: theme.surface,
      borderRadius: theme.radiusSm,
      padding: 3,
      gap: 3,
      margin: 16,
      marginBottom: 8,
    },
    tabBtn: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 9,
      paddingHorizontal: 4,
      borderRadius: 5,
    },
    tabBtnActive: { backgroundColor: theme.primary },
    tabText: { fontSize: 12, color: theme.textSecondary, fontWeight: "600" },
    tabTextActive: { color: "#fff" },
    list: { padding: 16, paddingTop: 8, gap: 12, paddingBottom: 40 },

    // stats grid
    statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
    statCard: {
      flexGrow: 1,
      flexBasis: "22%",
      minWidth: 70,
      backgroundColor: theme.glass,
      borderWidth: 1,
      borderColor: theme.glassBorder,
      borderRadius: theme.radius,
      paddingVertical: 14,
      alignItems: "center",
      gap: 2,
    },
    statValue: { fontSize: 22, fontWeight: "800", color: theme.text },
    statLabel: {
      fontSize: 10,
      color: theme.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.3,
    },

    // group sections
    groupSection: { gap: 10 },
    groupTitle: { fontSize: 14, fontWeight: "700", color: theme.text },

    // member card
    memberCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: theme.glass,
      borderWidth: 1,
      borderColor: theme.glassBorder,
      borderRadius: theme.radius,
      padding: 12,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarImg: { width: 44, height: 44, borderRadius: 22 },
    avatarText: { color: "#fff", fontSize: 15, fontWeight: "700" },
    memberBody: { flex: 1, gap: 2 },
    memberName: { fontSize: 15, fontWeight: "600", color: theme.text },
    memberRole: { fontSize: 12, color: theme.textSecondary },
    memberMetaRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      gap: 10,
      marginTop: 2,
    },
    metaItem: { flexDirection: "row", alignItems: "center", gap: 4 },
    memberMeta: {
      fontSize: 12,
      color: theme.textSecondary,
      textTransform: "capitalize",
    },
    taskHighlight: { fontSize: 12, color: theme.primary, marginTop: 2 },
    badge: {
      borderRadius: theme.radiusSm,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    badgeText: { fontSize: 11, fontWeight: "700" },

    // filters
    filterRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      paddingHorizontal: 16,
      paddingBottom: 8,
    },
    filterChip: {
      paddingHorizontal: 14,
      paddingVertical: 7,
      borderRadius: theme.radiusFull,
      backgroundColor: theme.glass,
      borderWidth: 1,
      borderColor: theme.glassBorder,
    },
    filterChipActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    filterChipText: { fontSize: 13, color: theme.textSecondary, fontWeight: "600" },
    filterChipTextActive: { color: "#fff" },

    // approval card
    approvalCard: {
      backgroundColor: theme.glass,
      borderWidth: 1,
      borderColor: theme.glassBorder,
      borderRadius: theme.radius,
      padding: 14,
      gap: 8,
    },
    approvalHeader: { flexDirection: "row", alignItems: "center", gap: 10 },
    avatarSm: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    avatarImgSm: { width: 36, height: 36, borderRadius: 18 },
    avatarTextSm: { color: "#fff", fontSize: 13, fontWeight: "700" },
    approvalName: { fontSize: 15, fontWeight: "600", color: theme.text },
    approvalType: {
      fontSize: 12,
      color: theme.textSecondary,
      textTransform: "capitalize",
    },
    detailRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    approvalDetail: { fontSize: 13, color: theme.text, flex: 1 },
    approvalReason: { fontSize: 13, color: theme.textMuted, fontStyle: "italic" },
    rejectReasonNote: { fontSize: 12, color: theme.danger },
    actionRow: { flexDirection: "row", gap: 10, marginTop: 4 },
    actionBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingVertical: 10,
      borderRadius: theme.radiusSm,
    },
    rejectBtn: {
      backgroundColor: "rgba(224,62,62,0.1)",
      borderWidth: 1,
      borderColor: "rgba(224,62,62,0.25)",
    },
    approveBtn: { backgroundColor: theme.primary },
    actionText: { fontSize: 14, fontWeight: "600" },

    // analytics summary
    summaryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
    summaryCard: {
      flexGrow: 1,
      flexBasis: "30%",
      minWidth: 100,
      backgroundColor: theme.glass,
      borderWidth: 1,
      borderColor: theme.glassBorder,
      borderRadius: theme.radius,
      padding: 12,
      alignItems: "center",
      gap: 4,
    },
    summaryIcon: { marginBottom: 2 },
    summaryValue: { fontSize: 20, fontWeight: "800", color: theme.text },
    summaryLabel: {
      fontSize: 10,
      color: theme.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.3,
      textAlign: "center",
    },
    sectionTitle: { fontSize: 15, fontWeight: "700", color: theme.text },
    memberCount: { fontSize: 13, color: theme.textMuted, fontWeight: "500" },

    // member performance
    perfCard: {
      backgroundColor: theme.glass,
      borderWidth: 1,
      borderColor: theme.glassBorder,
      borderRadius: theme.radius,
      padding: 14,
      gap: 10,
    },
    perfHeader: { flexDirection: "row", alignItems: "center", gap: 10 },
    perfName: { fontSize: 15, fontWeight: "600", color: theme.text },
    perfMeta: { fontSize: 12, color: theme.textSecondary, marginTop: 2 },
    perfHours: { alignItems: "flex-end" },
    perfHoursValue: { fontSize: 16, fontWeight: "800", color: theme.text },
    perfHoursLabel: {
      fontSize: 9,
      color: theme.textMuted,
      textTransform: "uppercase",
    },
    perfStatsRow: { flexDirection: "row", gap: 10 },
    perfStat: {
      flex: 1,
      backgroundColor: theme.surface,
      borderRadius: theme.radiusSm,
      paddingVertical: 8,
      alignItems: "center",
      gap: 2,
    },
    perfStatLabel: {
      fontSize: 9,
      color: theme.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.3,
    },
    perfStatValue: { fontSize: 14, fontWeight: "700", color: theme.text },
    perfBarRow: { flexDirection: "row", alignItems: "center", gap: 10 },
    perfBarLabel: { fontSize: 12, color: theme.textSecondary, width: 80 },
    percentWrap: { flex: 1, flexDirection: "row", alignItems: "center", gap: 8 },
    percentTrack: {
      flex: 1,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.surface,
      overflow: "hidden",
    },
    percentFill: { height: "100%", borderRadius: 3 },
    percentLabel: {
      fontSize: 11,
      fontWeight: "700",
      color: theme.text,
      width: 34,
      textAlign: "right",
    },

    // my requests
    requestCard: {
      backgroundColor: theme.glass,
      borderWidth: 1,
      borderColor: theme.glassBorder,
      borderRadius: theme.radius,
      padding: 14,
      gap: 8,
    },
    requestTop: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    typePill: {
      backgroundColor: theme.surface,
      borderRadius: theme.radiusSm,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    typePillText: {
      fontSize: 12,
      color: theme.text,
      fontWeight: "600",
      textTransform: "capitalize",
    },
    requestMeta: { fontSize: 12, color: theme.textMuted },

    // empty
    empty: { alignItems: "center", gap: 10, paddingTop: 60 },
    emptyText: { color: theme.textMuted, fontSize: 14 },
  });
