import { StyleSheet } from "react-native";
import type { Theme } from "../../src/theme";

export const makeStyles = (theme: Theme) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: "#0a0a0a" },
    // Transparent full-screen layer that captures taps to toggle the auto-hide
    // call chrome (WhatsApp/Signal style). Sits above the media stage but below
    // the overlay chrome so the actual control buttons still receive their taps.
    tapToToggleLayer: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 2,
    },
    // Dark fades behind the top info + bottom controls so the white call name
    // and control glyphs remain legible on the system-themed (possibly light)
    // video-off background and over bright video.
    // Rendered as LinearGradients (top → transparent, transparent → bottom) so
    // the darkening fades out smoothly toward the center instead of painting a
    // hard-edged solid dark band over the video. No flat backgroundColor here —
    // the gradient colours are supplied by the LinearGradient component.
    topScrim: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: 180,
      zIndex: 1,
    },
    bottomScrim: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      height: 180,
      zIndex: 1,
    },
    remoteVideo: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "#000",
    },
    localVideo: {
      position: "absolute",
      top: 50,
      right: 16,
      width: 110,
      height: 160,
      borderRadius: 12,
      backgroundColor: "#000",
      overflow: "hidden",
      // zIndex alone does NOT lift a view above a sibling on Android — elevation
      // is required, otherwise the full-screen remote video paints over the
      // self-preview once the call connects and the local tile "disappears".
      zIndex: 5,
      elevation: 8,
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.25)",
    },
    avatarWrap: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      alignItems: "center",
      justifyContent: "center",
    },
    avatar: {
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: theme.primary,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    avatarImg: { width: "100%", height: "100%" },
    avatarText: { color: "#fff", fontSize: 44, fontWeight: "700" },
    avatarName: {
      marginTop: 20,
      fontSize: 22,
      fontWeight: "600",
      letterSpacing: 0.2,
      maxWidth: "80%",
      textAlign: "center",
    },
    info: {
      position: "absolute",
      top: 80,
      left: 0,
      right: 0,
      alignItems: "flex-start",
      gap: 4,
      paddingHorizontal: 24,
      zIndex: 6,
    },
    // Signal aligns the recipient name to the LEFT near the top, with the
    // status/duration directly beneath it in a smaller, muted weight.
    peerName: {
      color: "#fff",
      fontSize: 26,
      fontWeight: "600",
      textAlign: "left",
      letterSpacing: 0.2,
    },
    status: {
      color: "rgba(255,255,255,0.8)",
      fontSize: 15,
      fontWeight: "400",
      textAlign: "left",
    },
    /* ─── Picture-in-Picture compact voice overlay ─── */
    pipVoiceOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      alignItems: "center",
      justifyContent: "flex-end",
      paddingBottom: 10,
    },
    pipVoiceName: { color: "#fff", fontSize: 13, fontWeight: "700" },
    pipVoiceStatus: { color: "rgba(255,255,255,0.7)", fontSize: 11 },
    topBar: {
      position: "absolute",
      top: 44, // overridden inline with insets.top + 8
      left: 16,
      right: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      zIndex: 6,
      elevation: 9,
      gap: 8,
    },
    statusBadgeRow: { flexDirection: "row", alignItems: "center", gap: 6 },
    pill: {
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 4,
      backgroundColor: "rgba(0,0,0,0.45)",
    },
    holdPill: { backgroundColor: "rgba(245,158,11,0.7)" },
    nsPill: { backgroundColor: "rgba(59,130,246,0.7)" },
    recPill: { backgroundColor: "rgba(239,68,68,0.75)" },
    pillText: { color: "#fff", fontSize: 11, fontWeight: "700" },
    qualityBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      backgroundColor: "rgba(0,0,0,0.45)",
      borderRadius: 14,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    qualityLabel: { fontSize: 12, fontWeight: "700" },
    muteBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      backgroundColor: "rgba(239,68,68,0.85)",
      borderRadius: 14,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    muteBadgeText: { color: "#fff", fontSize: 12, fontWeight: "700" },
    peerQualityBanner: {
      position: "absolute",
      alignSelf: "center",
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      maxWidth: "85%",
      backgroundColor: "rgba(239,68,68,0.9)",
      borderRadius: 16,
      paddingHorizontal: 12,
      paddingVertical: 6,
      zIndex: 7,
      elevation: 9,
    },
    peerQualityText: {
      color: "#fff",
      fontSize: 12,
      fontWeight: "600",
      flexShrink: 1,
    },
    /* ─── Controls bar (Signal-style row of circular buttons) ─── */
    controlsBar: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      alignItems: "center",
      zIndex: 10,
      elevation: 10,
    },
    // Evenly distributed circular buttons across the width, like Signal's call
    // control bar. No frosted pill — the buttons float directly over the video.
    controlsRow: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      justifyContent: "space-evenly" as const,
      width: "100%" as any,
      paddingHorizontal: 12,
      gap: 8,
    },
    /* ─── Incoming call layout ─── */
    incomingControls: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      flexDirection: "row" as const,
      justifyContent: "space-evenly" as const,
      alignItems: "flex-end" as const,
      zIndex: 10,
    },
    incomingBtnWrap: {
      alignItems: "center" as const,
      gap: 12,
      paddingBottom: 8,
    },
    ctrlLabel: {
      color: "rgba(255,255,255,0.9)",
      fontSize: 13,
      fontWeight: "500" as const,
    },
    // Signal control button: translucent white circle with a white glyph. When
    // "toggled" (mic muted, video off, speaker on…) it inverts to a solid white
    // circle with a dark glyph — the icon colour is set inline in the overlay.
    ctrl: {
      width: 58,
      height: 58,
      borderRadius: 29,
      backgroundColor: "rgba(255,255,255,0.16)",
      alignItems: "center",
      justifyContent: "center",
    },
    ctrlActive: { backgroundColor: "#ffffff" },
    ctrlHold: { backgroundColor: "#f59e0b" },
    ctrlEnd: {
      width: 58,
      height: 58,
      borderRadius: 29,
      backgroundColor: "#ef4444",
      alignItems: "center",
      justifyContent: "center",
    },
    reject: {
      width: 66,
      height: 66,
      borderRadius: 33,
      backgroundColor: "#ef4444",
      alignItems: "center",
      justifyContent: "center",
    },
    accept: {
      width: 66,
      height: 66,
      borderRadius: 33,
      backgroundColor: "#22c55e",
      alignItems: "center",
      justifyContent: "center",
    },
    unreadDot: {
      position: "absolute",
      top: -2,
      right: -2,
      minWidth: 16,
      height: 16,
      paddingHorizontal: 3,
      borderRadius: 8,
      backgroundColor: "#ef4444",
      alignItems: "center",
      justifyContent: "center",
    },
    unreadText: { color: "#fff", fontSize: 10, fontWeight: "700" },
    sheetBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.45)",
      justifyContent: "flex-end",
    },
    sheet: {
      backgroundColor: theme.bgSecondary,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: 26,
      gap: 6,
    },
    sheetHandle: {
      alignSelf: "center",
      width: 38,
      height: 4,
      borderRadius: 2,
      backgroundColor: "rgba(255,255,255,0.22)",
      marginBottom: 8,
    },
    sheetHeading: {
      color: theme.textSecondary,
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 0.6,
      textTransform: "uppercase",
      paddingHorizontal: 6,
      paddingBottom: 4,
    },
    sheetItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      paddingHorizontal: 12,
      paddingVertical: 12,
      borderRadius: 16,
      backgroundColor: "rgba(255,255,255,0.05)",
    },
    sheetItemLast: {},
    sheetIconWrap: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: "rgba(255,255,255,0.08)",
      alignItems: "center",
      justifyContent: "center",
    },
    sheetItemBody: { flex: 1, gap: 2 },
    sheetItemText: { color: theme.text, fontSize: 15, fontWeight: "600" },
    sheetItemSub: { color: theme.textMuted, fontSize: 12, fontWeight: "400" },
    sheetUnreadDot: {
      position: "absolute",
      top: -2,
      right: -2,
      minWidth: 16,
      height: 16,
      paddingHorizontal: 3,
      borderRadius: 8,
      backgroundColor: "#ef4444",
      alignItems: "center",
      justifyContent: "center",
    },
    reactionSheet: {
      marginTop: "auto",
      backgroundColor: theme.bgSecondary,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      padding: 16,
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      justifyContent: "center",
    },
    reactionBtn: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: "rgba(255,255,255,0.08)",
      alignItems: "center",
      justifyContent: "center",
    },
    reactionBtnText: { fontSize: 26 },
    floatingReaction: {
      position: "absolute",
      bottom: 110,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      backgroundColor: "rgba(0,0,0,0.45)",
      zIndex: 12,
      elevation: 12,
    },
    floatingReactionSelf: { right: 24 },
    floatingReactionPeer: { left: 24 },
    floatingReactionText: { fontSize: 28 },
    chatPanel: {
      flex: 1,
      marginTop: 80,
      backgroundColor: theme.bgSecondary,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
    },
    chatHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.glassBorder,
    },
    chatTitle: { color: theme.text, fontSize: 16, fontWeight: "700" },
    chatClose: { color: theme.primary, fontSize: 14, fontWeight: "600" },
    chatBody: { flex: 1, paddingHorizontal: 12, paddingVertical: 10 },
    chatMsg: {
      maxWidth: "82%",
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 8,
      marginBottom: 8,
    },
    chatMsgMine: {
      alignSelf: "flex-end",
      backgroundColor: "rgba(59,130,246,0.22)",
    },
    chatMsgPeer: {
      alignSelf: "flex-start",
      backgroundColor: "rgba(255,255,255,0.08)",
    },
    chatMsgSender: {
      color: "rgba(255,255,255,0.7)",
      fontSize: 11,
      marginBottom: 2,
    },
    chatMsgText: { color: "#fff", fontSize: 14 },
    chatComposer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderTopWidth: 1,
      borderTopColor: theme.glassBorder,
    },
    chatInput: {
      flex: 1,
      minHeight: 40,
      maxHeight: 100,
      borderRadius: 20,
      backgroundColor: "rgba(255,255,255,0.08)",
      color: "#fff",
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    chatSendBtn: {
      borderRadius: 18,
      backgroundColor: theme.primary,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    chatSendText: { color: "#fff", fontSize: 13, fontWeight: "700" },
  });
