/**
 * Notifee wrapper for background/terminated-state call & message notifications.
 *
 * WHY NOTIFEE (and not expo-notifications) FOR BACKGROUND DELIVERY:
 * - On Android, when the app is terminated, FCM spawns a *headless* JS task
 *   (see `mobile/index.js`) — the React tree never mounts. `expo-notifications`
 *   relies on its handler/channels being configured during React init, so its
 *   `scheduleNotificationAsync` is unreliable (often silently no-ops) from a
 *   headless background task.
 * - Notifee is purpose-built to run from `setBackgroundMessageHandler` and is
 *   the standard way to render a **full-screen-intent** incoming-call screen
 *   over the lock screen even when the app is killed, plus reliable status-bar
 *   message notifications in the terminated state.
 *
 * This module is defensive: every call resolves the native module via `require`
 * and no-ops if it is unavailable (e.g. Expo Go / web), so importing it never
 * crashes the JS bundle.
 */

import { Platform } from "react-native";
import * as Linking from "expo-linking";
import { nativeCallService } from "./nativeCallService";
import type { NotificationPayload } from "./pushNotificationService";
import {
  setPendingCall,
  pendingCallFromData,
  persistPendingCall,
  clearPersistedPendingCall,
  loadPersistedPendingCall,
} from "../realtime/pendingCall";
import { loadCallPrefs } from "./callPrefsStore";
import {
  startRinging,
  stopRinging,
  isCallRingerAvailable,
  getPendingCallAction,
  clearPendingCallAction,
} from "../../modules/call-ringer";

// Versioned channel IDs. Android notification channels are IMMUTABLE after
// creation — recreating a channel with the same ID does NOT update its
// importance/sound/visibility. If a device created "calls"/"messages" under an
// earlier build with weaker settings, those stale settings would persist and
// silently downgrade our call/message notifications. Bumping the ID forces the
// OS to create a fresh channel with the corrected high-importance settings.
// (Mirrors Signal-Android's `calls_v3` versioned-channel pattern.)
//
// Bumped v2 → v3 when we switched the calls channel SOUND from the Android
// system default ("default") to our BUNDLED `res/raw/ringtone` resource (see
// scripts/withAndroidRingtoneAssets + generate-call-sounds). A channel's sound
// is IMMUTABLE after creation, so the ID MUST be bumped for the new ringtone to
// take effect on devices that already created calls_v2.
const CALL_CHANNEL_ID = "calls_v3";
// The bundled raw resource name (file `res/raw/ringtone.wav`, referenced WITHOUT
// extension). This is the default WorkPulse incoming-call ringtone (== the
// "classic" option) used when the selected tone has no dedicated resource.
const CALL_RINGTONE_RESOURCE = "ringtone";

// SELECTED-RINGTONE SUPPORT (per-tone channels).
// An Android channel's sound is IMMUTABLE after creation, so to ring the
// killed/background status-bar call with the user's SELECTED ringtone we create
// ONE channel per ringtone option, each whose sound is the matching bundled
// `res/raw/ringtone_<id>` resource (generated by scripts/generate-call-sounds +
// copied by withAndroidRingtoneAssets), and post the incoming-call notification
// on the channel matching the user's choice (cached in callPrefsStore so the
// headless path can read it).
//
// Keep this list in sync with the RINGTONES presets in app/profile.tsx and the
// RINGTONE_NOTES map in scripts/generate-call-sounds.cjs. "none" is intentionally
// excluded (it maps to the SILENT channel).
const RINGTONE_IDS = [
  "classic",
  "calm",
  "dynamic",
  "urgent",
  "boop",
  "marimba",
  "crystal",
  "vapor",
] as const;
// Per-tone channel id. Versioned (_v3) alongside the default calls channel so a
// settings change creates fresh channels with the right immutable sound.
function callChannelIdForTone(toneId: string): string {
  return `calls_${toneId}_v3`;
}
// Per-tone bundled raw resource name (file `res/raw/ringtone_<id>.wav`).
function ringtoneResourceForTone(toneId: string): string {
  return `ringtone_${toneId}`;
}

// Silent sibling of the calls channel, used when the user has muted all
// notification sounds (`muteAll`). A channel's sound is IMMUTABLE after
// creation, so a separate silent channel is the only way to post a non-ringing
// incoming-call notification while still surfacing the full-screen call UI.
const CALL_SILENT_CHANNEL_ID = "calls_silent_v2";
const MESSAGE_CHANNEL_ID = "messages_v2";

type NotifeeModule = any;
type AndroidImportanceEnum = Record<string, number>;
type AndroidCategoryEnum = Record<string, string>;
type AndroidVisibilityEnum = Record<string, number>;
type EventTypeEnum = Record<string, number>;
type AndroidNotificationSettingEnum = Record<string, number>;

function callNotificationId(callId: string, conversationId: string): string {
  return `wp-call-${conversationId}-${callId}`;
}

// ── Cancelled-call tombstones ───────────────────────────────────────────────
// The `call_incoming` push and the `call_cancelled`/`call_ended` push can arrive
// out of order (or the cancel can land WHILE the incoming display is still being
// built in the headless task). Without a guard, a cancel that arrives first is a
// no-op and the now-dead incoming call still rings a moment later (the "receiver
// keeps ringing after the caller hung up" bug). We record recently cancelled/
// ended call ids with a timestamp; displayIncomingCall consults this set and
// SUPPRESSES a ring for a call that was just cancelled. Entries auto-expire so
// the set never grows unbounded and a genuine later call with a reused id is not
// blocked.
const CANCELLED_CALL_TTL_MS = 30000;
const cancelledCalls = new Map<string, number>();

function callKey(callId: string, conversationId: string): string {
  return `${conversationId}:${callId}`;
}

function markCallCancelled(callId?: string, conversationId?: string): void {
  if (!callId || !conversationId) return;
  const now = Date.now();
  cancelledCalls.set(callKey(callId, conversationId), now);
  // Opportunistic prune of expired entries.
  for (const [key, ts] of cancelledCalls) {
    if (now - ts > CANCELLED_CALL_TTL_MS) cancelledCalls.delete(key);
  }
}

function wasCallCancelled(callId?: string, conversationId?: string): boolean {
  if (!callId || !conversationId) return false;
  const ts = cancelledCalls.get(callKey(callId, conversationId));
  if (ts == null) return false;
  if (Date.now() - ts > CANCELLED_CALL_TTL_MS) {
    cancelledCalls.delete(callKey(callId, conversationId));
    return false;
  }
  return true;
}

function messageNotificationId(messageId: string): string {
  return `wp-msg-${messageId}`;
}

class NotifeeService {
  private notifee: NotifeeModule | null = null;
  private AndroidImportance: AndroidImportanceEnum = {};
  private AndroidCategory: AndroidCategoryEnum = {};
  private AndroidVisibility: AndroidVisibilityEnum = {};
  private EventType: EventTypeEnum = {};
  private AndroidNotificationSetting: AndroidNotificationSettingEnum = {};
  private resolved = false;
  private channelsEnsured = false;
  private fsiPermissionChecked = false;

  private resolve(): NotifeeModule | null {
    if (this.resolved) return this.notifee;
    this.resolved = true;
    try {
      const mod = require("@notifee/react-native");
      this.notifee = mod?.default || mod;
      this.AndroidImportance = mod?.AndroidImportance || {};
      this.AndroidCategory = mod?.AndroidCategory || {};
      this.AndroidVisibility = mod?.AndroidVisibility || {};
      this.EventType = mod?.EventType || {};
      this.AndroidNotificationSetting = mod?.AndroidNotificationSetting || {};
    } catch {
      this.notifee = null;
      console.warn("[NotifeeService] @notifee/react-native unavailable; background call/message UI disabled.");
    }
    return this.notifee;
  }

  isAvailable(): boolean {
    return this.resolve() != null;
  }

  /**
   * Creates the Android notification channels Notifee will post into. Safe to
   * call repeatedly; only does work once per process. Channels must exist before
   * displaying notifications, including during killed-state delivery.
   */
  async ensureChannels(): Promise<void> {
    const notifee = this.resolve();
    if (!notifee || Platform.OS !== "android") return;
    if (this.channelsEnsured) return;
    try {
      await notifee.createChannel({
        id: CALL_CHANNEL_ID,
        name: "Calls",
        description: "Incoming call alerts",
        importance: this.AndroidImportance.HIGH ?? 4,
        // Ring with the BUNDLED WorkPulse ringtone (res/raw/ringtone) instead of
        // the Android system default — this is what fixes "the status-bar call
        // uses the system tone, not the app ringtone" in the killed/background
        // state. The channel sound is immutable, hence the calls_v3 ID bump.
        sound: CALL_RINGTONE_RESOURCE,
        // Real-call cadence: short-long-short-long buzz pattern, repeated by the
        // OS while the heads-up/FSI notification is alerting.
        vibration: true,
        vibrationPattern: [0, 700, 1000, 700],
        bypassDnd: true,
        lights: true,
      });
      // Per-tone calls channels — ONE per selectable ringtone option, each
      // whose (immutable) sound is the matching bundled res/raw/ringtone_<id>
      // resource. displayIncomingCall posts on the channel matching the user's
      // SELECTED ringtone so the status-bar/background ring uses their choice.
      for (const toneId of RINGTONE_IDS) {
        try {
          await notifee.createChannel({
            id: callChannelIdForTone(toneId),
            name: `Calls (${toneId})`,
            description: "Incoming call alerts",
            importance: this.AndroidImportance.HIGH ?? 4,
            sound: ringtoneResourceForTone(toneId),
            vibration: true,
            vibrationPattern: [0, 700, 1000, 700],
            bypassDnd: true,
            lights: true,
          });
        } catch (e) {
          // A single bad tone (e.g. its raw resource missing) must not abort the
          // remaining channels — the default CALL_CHANNEL_ID still rings.
          console.warn(
            `[NotifeeService] failed to create calls channel for ${toneId}:`,
            e,
          );
        }
      }
      // Silent calls channel for when the user muted all sounds. Still
      // HIGH-importance so the full-screen-intent call UI surfaces, but with no
      // sound and no vibration so it honours `muteAll`.
      await notifee.createChannel({
        id: CALL_SILENT_CHANNEL_ID,
        name: "Calls (silent)",
        description: "Incoming call alerts (muted)",
        importance: this.AndroidImportance.HIGH ?? 4,
        sound: undefined,
        vibration: false,
        bypassDnd: true,
        lights: true,
      });
      await notifee.createChannel({
        id: MESSAGE_CHANNEL_ID,
        name: "Messages",
        description: "Chat message alerts",
        importance: this.AndroidImportance.HIGH ?? 4,
        sound: "default",
        vibration: true,
        vibrationPattern: [160, 80, 160],
        lights: true,
        lightColor: "#FF6B6B",
      });
      this.channelsEnsured = true;
    } catch (err) {
      console.warn("[NotifeeService] Failed to create channels:", err);
    }
  }

  /**
   * Requests the runtime notification permission through Notifee as well as
   * expo-notifications. Data-only FCM pushes can reach the app, but Android 13+
   * will still block the visible Notifee call/message UI if POST_NOTIFICATIONS
   * has not been granted to the native notification library.
   */
  async requestNotificationPermission(): Promise<boolean> {
    const notifee = this.resolve();
    if (!notifee) return false;
    try {
      if (typeof notifee.requestPermission !== "function") return true;
      const settings = await notifee.requestPermission();
      const authorizationStatus = settings?.authorizationStatus;
      const DENIED = 0;
      return authorizationStatus === undefined || authorizationStatus > DENIED;
    } catch (err) {
      console.warn("[NotifeeService] Failed to request notification permission:", err);
      return false;
    }
  }

  /**
   * Ensures the Android 14+ (API 34) USE_FULL_SCREEN_INTENT permission is
   * granted. On Android 14+, this permission is auto-revoked for apps that are
   * NOT the default phone/alarm app, which DOWNGRADES our incoming-call
   * notification: the looping ring sound still plays, but the full-screen
   * Answer/Decline screen NEVER surfaces over the lock screen — the user is
   * forced to open the app manually. This is the #1 cause of "only ringing, can't
   * answer from the lock screen".
   *
   * Notifee exposes the current setting via `getNotificationSettings()`. When it
   * is not ENABLED we deep-link the user to the dedicated system settings page
   * (`android.settings.MANAGE_APP_USE_FULL_SCREEN_INTENT`) so they can grant it.
   * No-ops on iOS / older Android and when Notifee is unavailable. Only prompts
   * once per process to avoid nagging.
   */
  async ensureFullScreenIntentPermission(): Promise<void> {
    const notifee = this.resolve();
    if (!notifee || Platform.OS !== "android") return;
    if (this.fsiPermissionChecked) return;
    this.fsiPermissionChecked = true;

    try {
      if (typeof notifee.getNotificationSettings !== "function") return;
      const settings = await notifee.getNotificationSettings();
      const fsi = settings?.android?.fullScreenAction;

      const ENABLED = this.AndroidNotificationSetting.ENABLED ?? 1;
      const NOT_SUPPORTED = this.AndroidNotificationSetting.NOT_SUPPORTED ?? -1;

      // Already granted, or the OS version predates the runtime FSI permission.
      if (fsi === undefined || fsi === ENABLED || fsi === NOT_SUPPORTED) return;

      // Prefer Notifee's helper that opens the exact FSI settings page.
      if (typeof notifee.openSystemSettings === "function") {
        // Some Notifee versions accept no args and open the app notification
        // settings; the dedicated FSI intent below is more precise.
      }

      try {
        await Linking.sendIntent(
          "android.settings.MANAGE_APP_USE_FULL_SCREEN_INTENT",
        );
      } catch {
        // Fallback: open the app's notification settings so the user can find
        // the "Full screen notifications" toggle manually.
        await Linking.openSettings().catch(() => {});
      }
    } catch (err) {
      console.warn("[NotifeeService] Failed to ensure full-screen-intent permission:", err);
    }
  }

  /**
   * Starts the native CallRinger foreground service, which posts the branded
   * CallStyle incoming-call notification (green Answer / red Decline + full-
   * screen intent) AND plays the user's selected ringtone. Honours `muteAll` and
   * the "none" ringtone (silent). Persists the pending-call route first so a
   * LOCKED + KILLED cold launch routes straight to the call screen.
   */
  private async startForegroundRinger(
    data: NonNullable<NotificationPayload["data"]>,
  ): Promise<void> {
    const title =
      data.title ||
      (data.callType === "video"
        ? "Incoming Video Call"
        : "Incoming Voice Call");
    const body = data.body || `${data.callerName || "Someone"} is calling...`;

    const { muteAll, ringtone } = await loadCallPrefs();
    const toneId = ringtone || "classic";
    const isKnownTone = (RINGTONE_IDS as readonly string[]).includes(toneId);
    const callSoundResource = isKnownTone
      ? ringtoneResourceForTone(toneId)
      : CALL_RINGTONE_RESOURCE;
    const silentRing = muteAll || toneId === "none";

    // Persist the pending route BEFORE starting the FGS — the full-screen intent
    // can auto-launch a brand-new process and app/index.tsx reads the route on
    // boot to route straight to /call (see displayIncomingCall's note).
    const route = pendingCallFromData(data);
    if (route) await persistPendingCall(route);

    try {
      startRinging({
        ringtoneRes: silentRing ? "" : callSoundResource,
        title,
        body,
        vibrate: !silentRing,
        silent: silentRing,
        callId: data.callId,
        conversationId: data.conversationId,
        callerId: data.callerId,
        callerName: data.callerName || title,
        callerAvatar: data.callerAvatar,
        callType: data.callType || "voice",
      });
    } catch (err) {
      console.warn("[NotifeeService] Failed to start foreground ringer:", err);
    }
  }

  /**
   * Displays a full-screen-intent incoming-call notification on Android. This is
   * what surfaces the WhatsApp/Teams-style incoming-call screen over the lock
   * screen even when the app is terminated. Includes Answer/Decline actions
   * handled by the background/foreground event handlers below.
   */
  async displayIncomingCall(data: NotificationPayload["data"]): Promise<void> {
    if (!data?.callId || !data?.conversationId) return;

    // SUPPRESS a ring for a call that was already cancelled/ended. The
    // `call_incoming` and `call_cancelled` pushes can arrive out of order in the
    // headless task; without this the receiver would still ring after the caller
    // hung up. (Tombstones auto-expire — see wasCallCancelled.)
    if (wasCallCancelled(data.callId, data.conversationId)) {
      try {
        stopRinging();
      } catch {
        /* best-effort */
      }
      return;
    }

    const notifee = this.resolve();
    // The native CallRinger foreground service (when present) OWNS the entire
    // incoming-call surface: it posts a branded CallStyle notification with a
    // green Answer / red Decline button + full-screen intent AND plays the ring.
    // In that case Notifee must NOT post its own competing notification (the
    // old behaviour produced a button-less ongoing notification that preempted
    // the proper one). We start the ringer here and return. Notifee is used only
    // as the FALLBACK when the native module is unavailable (Expo Go / iOS).
    if (isCallRingerAvailable) {
      await this.startForegroundRinger(data);
      return;
    }

    if (!notifee) return;

    await this.ensureChannels();

    const title =
      data.title ||
      (data.callType === "video" ? "Incoming Video Call" : "Incoming Voice Call");
    const body = data.body || `${data.callerName || "Someone"} is calling...`;
    const id = callNotificationId(data.callId, data.conversationId);

    // Honour the user's `muteAll` preference even in the killed/headless state.
    // The prefs are persisted to SecureStore while the app is alive (see
    // callPrefsStore) so they are readable here without an authenticated API
    // call. When muted we post on the SILENT channel with no sound/vibration —
    // the full-screen call UI still surfaces; it just doesn't ring/buzz.
    const { muteAll, ringtone } = await loadCallPrefs();

    // Resolve the per-tone channel + bundled ringtone resource for the user's
    // SELECTED ringtone so the status-bar/background ring uses THEIR choice
    // (not a single fixed tone). "none" → silent. An unknown/legacy id falls
    // back to the default calls channel ("classic"). The per-tone channels are
    // created in ensureChannels (their sound is immutable, hence per-tone).
    const toneId = ringtone || "classic";
    const isKnownTone = (RINGTONE_IDS as readonly string[]).includes(toneId);
    const callChannelId =
      muteAll || toneId === "none"
        ? CALL_SILENT_CHANNEL_ID
        : isKnownTone
          ? callChannelIdForTone(toneId)
          : CALL_CHANNEL_ID;
    const callSoundResource = isKnownTone
      ? ringtoneResourceForTone(toneId)
      : CALL_RINGTONE_RESOURCE;
    const silentRing = muteAll || toneId === "none";

    // PHASE 3 — Signal/Teams-parity ringing via a foreground service.
    // When the native CallRinger module is present we let the FOREGROUND SERVICE
    // own the ring (looping selected ringtone via MediaPlayer + repeating
    // Vibrator), which is consistent in every app state and stops instantly on
    // answer/decline. In that case Notifee must post SILENTLY (silent channel,
    // no sound/vibration override) so the OS notification channel doesn't ALSO
    // ring → no double-ring. When the module is unavailable (iOS / Expo Go /
    // non-prebuilt) we fall back to the per-tone channel ring from Phase 2b.
    const ringerOwnsSound = isCallRingerAvailable;
    if (ringerOwnsSound) {
      try {
        startRinging({
          ringtoneRes: silentRing ? "" : callSoundResource,
          title,
          body,
          vibrate: !silentRing,
          silent: silentRing,
        });
      } catch {
        // Best-effort; the Notifee notification still surfaces the call UI.
      }
    }
    // Effective channel/sound for the Notifee notification: silent whenever the
    // ring is muted OR the foreground-service ringer is handling the sound.
    const notifeeSilent = silentRing || ringerOwnsSound;
    const effectiveChannelId = notifeeSilent
      ? CALL_SILENT_CHANNEL_ID
      : callChannelId;

    // CRITICAL ORDERING (fixes the "dashboard flashes then switches to the call
    // UI" bug on a LOCKED + KILLED device): persist the pending-call route to
    // durable storage BEFORE we display the full-screen-intent notification.
    // The FSI AUTO-launches MainActivity in a brand-new process the instant the
    // notification is posted; app/index.tsx reads the persisted route on boot to
    // route STRAIGHT to /call (no dashboard underneath). If we persisted AFTER
    // displayNotification(), the freshly-launched activity could read storage
    // before the write landed, find nothing, redirect to the dashboard, and
    // only later switch to the call screen — the visible flash. Writing first
    // closes that race.
    const earlyRoute = pendingCallFromData(data);
    if (earlyRoute) await persistPendingCall(earlyRoute);

    try {
      await notifee.displayNotification({
        id,
        title,
        body,
        data: { ...data } as Record<string, string>,
        android: {
          channelId: effectiveChannelId,
          category: this.AndroidCategory.CALL ?? "call",
          importance: this.AndroidImportance.HIGH ?? 4,
          visibility: this.AndroidVisibility.PUBLIC ?? 1,
          // Full-screen intent: launches the app's main activity full-screen
          // over the lock screen even when terminated.
          fullScreenAction: {
            id: "default",
            launchActivity: "default",
          },
          pressAction: {
            id: "default",
            launchActivity: "default",
          },
          // Persistent + (when not muted) looping sound + vibration so it rings
          // like a real call. When `muteAll` is set we drop the sound, the loop
          // and the vibration pattern so the call surfaces silently.
          //
          // NOTE: Notifee VALIDATES `android.vibrationPattern` — it must have an
          // EVEN number of entries and every value must be > 0. A malformed
          // pattern (e.g. an odd length or a leading 0) makes
          // displayNotification() THROW, which the catch below swallows — so the
          // incoming-call notification is silently dropped in the killed/
          // background state (it then only appears once the app is opened). Keep
          // this pattern even-length and all-positive. When muted we omit the
          // override entirely (do NOT pass `undefined`).
          ongoing: true,
          autoCancel: false,
          loopSound: !notifeeSilent,
          // Ring with the user's SELECTED bundled ringtone (res/raw/ringtone_<id>),
          // not the system default. loopSound replays it for the call's duration
          // so it behaves like a real incoming-call ring in the status-bar/
          // background state. vibrationPattern uses a real-call cadence (even
          // length, all > 0 — Notifee rejects malformed patterns). When the ring
          // is silent — muteAll, "none", OR the foreground-service ringer is
          // handling the sound (notifeeSilent) — we omit the override so the OS
          // channel doesn't ALSO ring (no double-ring).
          ...(notifeeSilent
            ? {}
            : {
                sound: callSoundResource,
                vibrationPattern: [0, 700, 1000, 700],
              }),
          actions: [
            {
              title: "Answer",
              pressAction: { id: "answer", launchActivity: "default" },
            },
            {
              title: "Decline",
              pressAction: { id: "decline" },
            },
          ],
          timeoutAfter: 45000,
        },
      });

      // Persist the call route so a LOCKED + KILLED device — where the
      // full-screen-intent AUTO-launches MainActivity in a brand-new process
      // (not a notification tap, so getInitialNotification() is null) — can
      // still route to the incoming-call screen instead of the dashboard. The
      // in-memory pending route does not survive that process death; SecureStore
      // does. PendingCallNavigator loads + consumes it (if still fresh) on mount.
      const route = pendingCallFromData(data);
      if (route) await persistPendingCall(route);
    } catch (err) {
      console.warn("[NotifeeService] Failed to display incoming call:", err);
      // DEFENSIVE FALLBACK: a single malformed android option (e.g. an invalid
      // vibrationPattern) makes displayNotification() throw and would otherwise
      // drop the incoming-call notification entirely in the killed/background
      // state. Retry once with ONLY the essential fields so the ringing call
      // still surfaces (full-screen intent + Answer/Decline) even if some
      // optional styling field was rejected.
      try {
        await notifee.displayNotification({
          id,
          title,
          body,
          data: { ...data } as Record<string, string>,
          android: {
            channelId: muteAll ? CALL_SILENT_CHANNEL_ID : CALL_CHANNEL_ID,
            category: this.AndroidCategory.CALL ?? "call",
            importance: this.AndroidImportance.HIGH ?? 4,
            visibility: this.AndroidVisibility.PUBLIC ?? 1,
            fullScreenAction: { id: "default", launchActivity: "default" },
            pressAction: { id: "default", launchActivity: "default" },
            ongoing: true,
            autoCancel: false,
            actions: [
              {
                title: "Answer",
                pressAction: { id: "answer", launchActivity: "default" },
              },
              {
                title: "Decline",
                pressAction: { id: "decline" },
              },
            ],
            timeoutAfter: 45000,
          },
        });
        const route = pendingCallFromData(data);
        if (route) await persistPendingCall(route);
      } catch (err2) {
        console.warn(
          "[NotifeeService] Fallback incoming-call display also failed:",
          err2,
        );
      }
    }
  }

  /**
   * Displays a standard status-bar message notification. Reliable in
   * background/terminated state, unlike expo-notifications from a headless task.
   */
  async displayMessage(payload: NotificationPayload): Promise<void> {
    const notifee = this.resolve();
    if (!notifee) return;
    const data = payload.data || {};
    const title = payload.title || data.title || data.senderName || "New message";
    const body = payload.body || data.body || "";
    if (!title && !body) return;

    await this.ensureChannels();

    const id = data.messageId ? messageNotificationId(data.messageId) : undefined;
    // Server-authoritative launcher/app-icon badge total (e.g. "3" unread).
    const badgeCount = Number(data.badgeCount ?? data.unreadCount);
    const hasBadge = Number.isFinite(badgeCount) && badgeCount >= 0;
    try {
      await notifee.displayNotification({
        ...(id ? { id } : {}),
        title,
        body,
        data: { ...data } as Record<string, string>,
        android: {
          channelId: MESSAGE_CHANNEL_ID,
          importance: this.AndroidImportance.HIGH ?? 4,
          visibility: this.AndroidVisibility.PRIVATE ?? 0,
          pressAction: { id: "default", launchActivity: "default" },
          sound: "default",
          // Drive the launcher dot/count from the running total.
          ...(hasBadge ? { badgeCount } : {}),
          // No custom `smallIcon` — Notifee falls back to the app's launcher
          // icon. We deliberately avoid generating a dedicated notification
          // drawable via expo-notifications `icon`/`color` because those inject
          // FCM default-notification meta-data that collides with
          // @react-native-firebase/messaging and fails the manifest merge.
        },
      });
    } catch (err) {
      // Retry once without any extra android options as a last-ditch fallback.
      try {
        await notifee.displayNotification({
          ...(id ? { id } : {}),
          title,
          body,
          data: { ...data } as Record<string, string>,
          android: {
            channelId: MESSAGE_CHANNEL_ID,
            importance: this.AndroidImportance.HIGH ?? 4,
            pressAction: { id: "default", launchActivity: "default" },
            sound: "default",
          },
        });
      } catch (err2) {
        console.warn("[NotifeeService] Failed to display message:", err2);
      }
    }
  }

  /** Cancels a previously-displayed incoming-call notification (call ended/handled). */
  async cancelCall(callId?: string, conversationId?: string): Promise<void> {
    // Record a tombstone so that if a `call_incoming` push for this same call is
    // still in flight (push ordering race), displayIncomingCall suppresses it
    // instead of ringing a now-dead call (the "receiver keeps ringing after the
    // caller hung up" bug).
    markCallCancelled(callId, conversationId);
    // PHASE 3 — stop the foreground-service ringer (looping ringtone + vibration)
    // IMMEDIATELY so the ring ends the instant the call is answered/declined/
    // cancelled/handled-elsewhere. No-op when the native module is unavailable.
    try {
      stopRinging();
    } catch {
      // best-effort
    }
    // Drop any persisted pending-call route so a future cold start never routes
    // to a call that has already ended / been handled (avoids "ghost" call
    // screens). Done regardless of Notifee availability.
    await clearPersistedPendingCall();
    // Also drop any native status-bar Answer/Decline action recorded by
    // CallActionReceiver so a warm-app action tap (already routed via the deep
    // link) can't linger and auto-answer/decline a later cold-started call.
    try {
      clearPendingCallAction();
    } catch {
      // best-effort
    }
    const notifee = this.resolve();
    if (!notifee || !callId || !conversationId) return;
    try {
      await notifee.cancelNotification(callNotificationId(callId, conversationId));
    } catch (err) {
      console.warn("[NotifeeService] Failed to cancel call notification:", err);
    }
  }

  /**
   * Handles a Notifee event (press / action press) for an incoming call.
   * Returns true if the event was a call event it handled. Used by both the
   * foreground and background event handlers.
   */
  async handleCallEvent(type: number, detail: any): Promise<boolean> {
    const notifee = this.resolve();
    if (!notifee) return false;

    const pressActionId: string | undefined =
      detail?.pressAction?.id || detail?.notification?.android?.pressAction?.id;
    const data = (detail?.notification?.data || {}) as Record<string, string>;
    if (!data.callId || !data.conversationId) return false;

    const isPress = type === (this.EventType.PRESS ?? 1);
    const isAction = type === (this.EventType.ACTION_PRESS ?? 2);
    if (!isPress && !isAction) return false;

    // Always clear the ringing notification once acted upon.
    await this.cancelCall(data.callId, data.conversationId);

    if (pressActionId === "decline") {
      // Stash a pending "decline" route so a cold-started app still reconciles
      // (the call screen auto-rejects on mount). nativeCallService also sends
      // the raw reject for the genuinely-killed case.
      const route = pendingCallFromData({ ...data, notificationAction: "decline_call" });
      if (route) setPendingCall(route);
      await nativeCallService.handleAction("reject", data);
      return true;
    }

    if (pressActionId === "answer") {
      // Stash a pending "answer" route so that when the app is launched COLD by
      // this tap (Linking deep link is lost before expo-router mounts), the
      // root layout still navigates to the call screen with autoAnswer=1.
      const route = pendingCallFromData({ ...data, notificationAction: "accept_call" });
      if (route) setPendingCall(route);
      await nativeCallService.handleAction("answer", data);
      return true;
    }

    // Body press → open the call screen in incoming mode without auto-answer.
    // Stash a pending route too, so a cold start still reaches the call screen.
    const route = pendingCallFromData(data);
    if (route) setPendingCall(route);
    try {
      // Include peerName/peerAvatar so the call screen shows the caller's name
      // (not the generic "Call" fallback) when this body-press deep link wins.
      const peerName = encodeURIComponent(data.callerName || "");
      const peerAvatar = encodeURIComponent(data.callerAvatar || "");
      const href = `/call/${data.conversationId}?mode=incoming&callId=${data.callId}&callType=${data.callType || "voice"}&peerId=${data.callerId || ""}&peerName=${peerName}&peerAvatar=${peerAvatar}`;
      await Linking.openURL(Linking.createURL(href));
    } catch (err) {
      console.warn("[NotifeeService] Failed to route answer:", err);
    }
    return true;
  }

  /**
   * Reads Notifee's initial notification (the call notification that COLD-
   * launched the app) and returns a pending call route for it, or null. Called
   * once at app startup from the root layout so a killed-state notification tap
   * / Answer action routes to the call screen even though the headless deep
   * link was lost before the router mounted.
   */
  async captureInitialCallRoute(): Promise<void> {
    // FIRST: the native CallStyle status-bar notification path. When the user
    // taps Answer/Decline on the foreground-service (CallRingService) call
    // notification, CallActionReceiver records the choice natively
    // (PendingCallActionStore) and launches a deep link. On a COLD start the
    // proven routing path (app/index.tsx) reads the SecureStore-PERSISTED
    // pending-call route — which was written at RING time with autoAnswer="0"
    // and no action — so it would open the call screen in plain RINGING mode and
    // the deep link's action params are lost (Answer never connects, Decline
    // never rejects). Here we read that native action and MERGE it into the
    // in-memory pending route (which app/index.tsx prefers over the persisted
    // one), so the call screen's autoAnswer/autoDecline effects fire. This is a
    // no-op when the native module is unavailable or no action was recorded.
    try {
      const nativeAction = getPendingCallAction();
      if (nativeAction) {
        // The full call details (callType, peerName, peerAvatar, peerId) live in
        // the persisted route written at ring time; the native record only has
        // the action + identity. Merge them so the call screen has everything.
        const persisted = await loadPersistedPendingCall();
        const matches =
          persisted &&
          String(persisted.callId) === String(nativeAction.callId) &&
          String(persisted.conversationId) ===
            String(nativeAction.conversationId);
        const base =
          matches && persisted
            ? persisted
            : {
                conversationId: String(nativeAction.conversationId),
                callId: String(nativeAction.callId),
                callType: "voice",
                peerId: "",
                peerName: "Incoming call",
                peerAvatar: "",
                autoAnswer: "0",
              };
        const merged = {
          ...base,
          autoAnswer: nativeAction.action === "answer" ? "1" : "0",
          ...(nativeAction.action === "decline"
            ? { action: "decline" }
            : { action: undefined }),
        };
        setPendingCall(merged);
        // Consumed — clear so a stale tap can't auto-answer a later call.
        clearPendingCallAction();
        return;
      }
    } catch (err) {
      console.warn(
        "[NotifeeService] Failed to read native pending call action:",
        err,
      );
    }

    const notifee = this.resolve();
    if (!notifee || typeof notifee.getInitialNotification !== "function") return;
    try {
      const initial = await notifee.getInitialNotification();
      if (!initial) return;
      const data = (initial.notification?.data || {}) as Record<string, string>;
      if (!data.callId || !data.conversationId) return;
      const pressActionId: string | undefined = initial.pressAction?.id;
      const action =
        pressActionId === "answer"
          ? "accept_call"
          : pressActionId === "decline"
            ? "decline_call"
            : undefined;
      const route = pendingCallFromData({ ...data, notificationAction: action });
      if (route) setPendingCall(route);
    } catch (err) {
      console.warn("[NotifeeService] Failed to read initial notification:", err);
    }
  }

  /**
   * Registers the Notifee background event handler. MUST be called at the JS
   * entry top-level (see `mobile/index.js`) so Answer/Decline work when the app
   * is killed. Idempotent and safe if Notifee is unavailable.
   */
  registerBackgroundHandler(): void {
    const notifee = this.resolve();
    if (!notifee) return;
    try {
      notifee.onBackgroundEvent(async ({ type, detail }: { type: number; detail: any }) => {
        await this.handleCallEvent(type, detail);
      });
    } catch (err) {
      console.warn("[NotifeeService] Failed to register background event handler:", err);
    }
  }

  /**
   * Registers the foreground event handler (call answer/decline while app is
   * alive). Returns an unsubscribe function.
   */
  registerForegroundHandler(): () => void {
    const notifee = this.resolve();
    if (!notifee) return () => {};
    try {
      const unsub = notifee.onForegroundEvent(async ({ type, detail }: { type: number; detail: any }) => {
        await this.handleCallEvent(type, detail);
      });
      return typeof unsub === "function" ? unsub : () => {};
    } catch (err) {
      console.warn("[NotifeeService] Failed to register foreground event handler:", err);
      return () => {};
    }
  }
}

export const notifeeService = new NotifeeService();