// @ts-check
/**
 * ESLint flat config for the mobile workspace.
 *
 * The project had NO linter at all, which is how it accumulated 195 empty
 * `catch {}` blocks, 135 `as any` casts and 146 raw `console.*` calls without
 * anyone noticing. This config is deliberately PRAGMATIC: rules that would
 * flag thousands of pre-existing lines are set to "warn" so the build stays
 * green and the debt is visible-but-not-blocking, while rules that protect the
 * invariants fixed in this refactor are hard "error"s.
 *
 * Run: `npm run lint`  /  `npm run lint:fix`
 */
const expoConfig = require("eslint-config-expo/flat");
const tseslint = require("typescript-eslint");

module.exports = [
  ...expoConfig,

  {
    ignores: [
      "node_modules/**",
      "android/**",
      "ios/**",
      ".expo/**",
      "dist/**",
      "graphify-out/**",
      "scripts/**",
      "patches/**",
    ],
  },

  {
    files: ["**/*.ts", "**/*.tsx"],
    plugins: { "@typescript-eslint": tseslint.plugin },
    languageOptions: { parser: tseslint.parser },
    linterOptions: {
      // Off deliberately. With most rules set to "warn", a directive that
      // suppresses a still-valid warning gets reported as "unused", which
      // tempts you to delete a disable comment that IS load-bearing. Revisit
      // once the warning debt below is paid down.
      reportUnusedDisableDirectives: "off",
    },
    rules: {
      /* ── ERRORS: protect the invariants this refactor established ─────── */

      // A floating promise in a `catch`-free path is how the socket race and
      // several "silently did nothing" bugs got in. `void expr` opts out
      // explicitly when fire-and-forget really is intended.
      "no-void": "off",

      // Hooks correctness is non-negotiable — especially with the React
      // Compiler enabled (app.config.ts → experiments.reactCompiler), which
      // assumes components are pure and can MISCOMPILE code that isn't.
      "react-hooks/rules-of-hooks": "error",

      // Importing a `src/` module via a long relative chain still works, but
      // the alias exists now; flag the worst offenders (3+ levels up).
      // WARN, not error: ~391 deep relative imports predate the alias, and
      // migrating them is a separate mechanical change that should not be
      // bundled into this refactor. New code gets nudged; CI stays green.
      "no-restricted-imports": [
        "warn",
        {
          patterns: [
            {
              group: ["../../../*"],
              message:
                "Use the '@/…' alias instead of a deep relative import (see tsconfig paths).",
            },
          ],
        },
      ],

      /* ── WARNINGS: pre-existing debt, surfaced but not blocking ───────── */

      // 195 of these exist. Each hides a real failure — migrate them to
      // `logError(scope, err)` from src/utils/logError.ts over time.
      "no-empty": ["warn", { allowEmptyCatch: false }],

      // 135 `as any` casts erase the type safety the rest of the config buys.
      "@typescript-eslint/no-explicit-any": "warn",

      // 146 raw console calls ship to production and leak data into logcat.
      // Many are the deliberate `[WP-COLDSTART]` boot-trace breadcrumbs, which
      // are genuinely useful — hence warn, not error.
      "no-console": ["warn", { allow: ["warn", "error"] }],

      // Apostrophes in copy ("don't") are flagged by default; harmless in RN
      // <Text>, and there are ~35 of them in existing screens.
      "react/no-unescaped-entities": "warn",

      "react-hooks/exhaustive-deps": "warn",

      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },

  {
    // Tests legitimately need `any`, console output and empty stubs.
    files: [
      "**/__tests__/**/*.{ts,tsx}",
      "**/*.test.{ts,tsx}",
      "jest.setup.js",
      "jest.config.js",
    ],
    languageOptions: {
      globals: {
        jest: "readonly",
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
      },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "no-console": "off",
      "no-empty": "off",
      "no-restricted-imports": "off",
      "no-undef": "off",
    },
  },

  {
    // AUTO-GENERATED by scripts/gen-custom-icons.cjs. Its `makeIcon` factory
    // returns anonymous components by design; adding displayName would be
    // overwritten on the next regeneration.
    files: ["src/icons/custom.tsx"],
    rules: { "react/display-name": "off" },
  },

  {
    // Node-context config files (CommonJS, `require`/`module`/`__dirname`).
    files: ["*.config.js", "eslint.config.js", "metro.config.js", "babel.config.js"],
    languageOptions: {
      globals: {
        require: "readonly",
        module: "writable",
        __dirname: "readonly",
        process: "readonly",
      },
    },
    rules: { "no-undef": "off" },
  },
];
