import { StyleSheet } from "react-native";
import type { Theme } from "../../src/theme";

export const makeStyles = (theme: Theme) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: "#0a0a0a",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 10,
      gap: 12,
    },
    headerLeft: { flex: 1, gap: 4 },
    headerTitle: { color: "#fff", fontSize: 17, fontWeight: "700" },
    codePill: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
      gap: 6,
      backgroundColor: "rgba(255,255,255,0.08)",
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    codeText: {
      color: "rgba(255,255,255,0.7)",
      fontSize: 12,
      fontWeight: "600",
      letterSpacing: 0.5,
    },
    headerRight: { flexDirection: "row", alignItems: "center", gap: 10 },
    headerStatus: { color: "rgba(255,255,255,0.6)", fontSize: 13 },
    headerBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: "rgba(255,255,255,0.08)",
      alignItems: "center",
      justifyContent: "center",
    },
    gridScroll: { flex: 1 },
    grid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      padding: 12,
      justifyContent: "center",
    },
    tile: {
      backgroundColor: "#161616",
      borderRadius: 14,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.08)",
    },
    tileVideo: { flex: 1, backgroundColor: "#000" },
    // Android mobile peers can publish front-camera video mirrored.
    // Counter-flip only remote tiles; keep local mirror behavior unchanged.
    unmirrorVideo: { transform: [{ scaleX: -1 }] },
    tileAvatarWrap: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
    },
    tileAvatar: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: theme.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    tileAvatarText: { color: "#fff", fontSize: 26, fontWeight: "700" },
    tileAvatarImg: { width: 64, height: 64, borderRadius: 32 },
    tileHand: {
      position: "absolute",
      top: 6,
      right: 6,
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: theme.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    tileStatusRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    tileStatusText: {
      color: "rgba(255,255,255,0.55)",
      fontSize: 12,
      fontWeight: "500",
    },
    tileFooter: {
      position: "absolute",
      bottom: 6,
      left: 6,
      right: 6,
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      backgroundColor: "rgba(0,0,0,0.45)",
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    tileName: { color: "#fff", fontSize: 12, fontWeight: "600", flex: 1 },
    waiting: {
      position: "absolute",
      top: "45%",
      left: 0,
      right: 0,
      alignItems: "center",
      gap: 10,
    },
    waitingText: { color: "rgba(255,255,255,0.6)", fontSize: 14 },
    controls: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "flex-start",
      gap: 22,
      paddingVertical: 14,
      paddingBottom: 20,
      backgroundColor: "rgba(0,0,0,0.3)",
    },
    ctrlWrap: { alignItems: "center", gap: 6 },
    ctrl: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: "rgba(255,255,255,0.16)",
      alignItems: "center",
      justifyContent: "center",
    },
    ctrlUnreadDot: {
      position: "absolute",
      top: -6,
      right: -8,
      minWidth: 16,
      height: 16,
      borderRadius: 8,
      paddingHorizontal: 3,
      backgroundColor: theme.danger,
      alignItems: "center",
      justifyContent: "center",
    },
    ctrlUnreadText: { color: "#fff", fontSize: 10, fontWeight: "700" },
    ctrlActive: { backgroundColor: "rgba(255,255,255,0.32)" },
    ctrlDanger: { backgroundColor: theme.danger },
    ctrlLabel: { color: "rgba(255,255,255,0.7)", fontSize: 11 },
    // ── Error / fallback card ──
    card: {
      margin: 16,
      backgroundColor: theme.glass,
      borderWidth: 1,
      borderColor: theme.glassBorder,
      borderRadius: theme.radiusLg,
      padding: 24,
      alignItems: "center",
      gap: 10,
    },
    iconWrap: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: theme.primaryGlow,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 4,
    },
    cardTitle: { fontSize: 18, fontWeight: "800", color: theme.text },
    hint: {
      fontSize: 13,
      color: theme.textMuted,
      textAlign: "center",
      lineHeight: 19,
      marginVertical: 4,
    },
    fallbackBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: theme.primary,
      borderRadius: theme.radiusSm,
      paddingVertical: 12,
      paddingHorizontal: 24,
      marginTop: 6,
    },
    fallbackBtnText: { color: "#fff", fontSize: 15, fontWeight: "600" },
    linkBtn: { paddingVertical: 10, paddingHorizontal: 16 },
    linkBtnText: { color: theme.textSecondary, fontSize: 14 },
    // ── Pre-join lobby ──
    lobbyPreviewWrap: {
      flex: 1,
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    lobbyPreview: {
      flex: 1,
      backgroundColor: "#161616",
      borderRadius: 18,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.08)",
    },
    lobbyVideo: { flex: 1, backgroundColor: "#000" },
    lobbyAvatarWrap: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
    },
    lobbyAvatar: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: "rgba(255,255,255,0.12)",
      alignItems: "center",
      justifyContent: "center",
    },
    lobbyHint: { color: "rgba(255,255,255,0.6)", fontSize: 14 },
    lobbyMuteBadge: {
      position: "absolute",
      bottom: 12,
      left: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      backgroundColor: "rgba(0,0,0,0.55)",
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    lobbyMuteText: { color: "#fff", fontSize: 12, fontWeight: "600" },
    lobbyActions: {
      alignItems: "center",
      gap: 4,
      paddingBottom: 18,
    },
    lobbyJoinBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: theme.primary,
      borderRadius: 28,
      paddingVertical: 14,
      paddingHorizontal: 48,
    },
    lobbyJoinText: { color: "#fff", fontSize: 16, fontWeight: "700" },
    // ── More drawer + participants modal ──
    sheetBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    sheet: {
      backgroundColor: theme.bgElevated,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      padding: 12,
      gap: 4,
    },
    sheetItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 14,
      paddingHorizontal: 12,
      borderRadius: 10,
    },
    sheetItemText: { color: theme.text, fontSize: 15, fontWeight: "600" },
    sheetCancel: {
      alignItems: "center",
      paddingVertical: 14,
      marginTop: 4,
    },
    sheetCancelText: { color: theme.textSecondary, fontSize: 15 },
    reactionSheet: {
      marginTop: "auto",
      backgroundColor: theme.bgElevated,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      padding: 14,
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      justifyContent: "center",
    },
    reactionBtn: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: "rgba(255,255,255,0.08)",
      alignItems: "center",
      justifyContent: "center",
    },
    reactionText: { fontSize: 26 },
    chatPanel: {
      flex: 1,
      marginTop: 84,
      backgroundColor: theme.bgElevated,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
    },
    chatHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.glassBorder,
    },
    chatTitle: { color: theme.text, fontSize: 16, fontWeight: "700" },
    chatClose: { color: theme.primary, fontSize: 14, fontWeight: "600" },
    chatBody: { flex: 1, paddingHorizontal: 12, paddingVertical: 10 },
    chatMsg: {
      maxWidth: "82%",
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 8,
      marginBottom: 8,
    },
    chatMsgMine: {
      alignSelf: "flex-end",
      backgroundColor: "rgba(59,130,246,0.22)",
    },
    chatMsgPeer: {
      alignSelf: "flex-start",
      backgroundColor: "rgba(255,255,255,0.08)",
    },
    chatMsgSender: {
      color: "rgba(255,255,255,0.7)",
      fontSize: 11,
      marginBottom: 2,
    },
    chatMsgText: { color: "#fff", fontSize: 14 },
    chatComposer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderTopWidth: 1,
      borderTopColor: theme.glassBorder,
    },
    chatInput: {
      flex: 1,
      minHeight: 40,
      maxHeight: 100,
      borderRadius: 20,
      backgroundColor: "rgba(255,255,255,0.08)",
      color: "#fff",
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    chatSendBtn: {
      borderRadius: 18,
      backgroundColor: theme.primary,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    chatSendText: { color: "#fff", fontSize: 13, fontWeight: "700" },
    participantsPanel: {
      backgroundColor: theme.bgElevated,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 24,
      maxHeight: "70%",
    },
    participantsHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    participantsTitle: { color: theme.text, fontSize: 16, fontWeight: "700" },
    participantRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 10,
    },
    participantAvatar: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.primary,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    participantAvatarImg: { width: 38, height: 38, borderRadius: 19 },
    participantAvatarText: { color: "#fff", fontSize: 15, fontWeight: "700" },
    participantName: { color: theme.text, fontSize: 15, flex: 1 },
  });

