import { StyleSheet } from "react-native";
import type { Theme } from "../../src/theme";

export const makeStyles = (theme: Theme) =>
  StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.bg },
  body: { padding: 16, paddingBottom: 40, gap: 6 },
  tabRow: {
    flexDirection: "row",
    backgroundColor: theme.surface,
    borderRadius: theme.radiusSm,
    padding: 3,
    gap: 3,
    margin: 16,
    marginBottom: 0,
  },
  tabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingVertical: 9,
    paddingHorizontal: 2,
    borderRadius: 5,
  },
  tabBtnActive: { backgroundColor: theme.primary },
  tabText: { fontSize: 12, color: theme.textSecondary, fontWeight: "600" },
  tabTextActive: { color: "#fff" },
  // calendar
  monthHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  monthLabel: {
    fontSize: 18,
    fontWeight: "800",
    color: theme.text,
    letterSpacing: -0.5,
  },
  monthNav: { flexDirection: "row", alignItems: "center", gap: 6 },
  navBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  todayBtn: {
    paddingHorizontal: 12,
    height: 34,
    borderRadius: 8,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  todayText: { color: theme.textSecondary, fontSize: 13, fontWeight: "600" },
  legend: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 10,
  },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendText: { fontSize: 11, color: theme.textSecondary },
  weekRow: { flexDirection: "row", marginBottom: 4 },
  weekday: {
    flex: 1,
    textAlign: "center",
    fontSize: 11,
    fontWeight: "700",
    color: theme.textMuted,
  },
  grid: { flexDirection: "row", flexWrap: "wrap" },
  cell: { width: `${100 / 7}%`, aspectRatio: 1, padding: 2 },
  cellInner: {
    flex: 1,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  cellSelected: { backgroundColor: theme.primary },
  cellToday: { backgroundColor: theme.primaryGlow },
  cellNum: { fontSize: 14, color: theme.text, fontWeight: "500" },
  cellNumMuted: { color: theme.textMuted, opacity: 0.5 },
  cellNumActive: { fontWeight: "700" },
  workDot: { width: 6, height: 6, borderRadius: 3 },
  workDotSpacer: { height: 6 },
  detailHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 16,
    marginBottom: 8,
  },
  detailTitle: { fontSize: 15, fontWeight: "700", color: theme.text },
  detailCard: {
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusLg,
    paddingHorizontal: 16,
  },
  divider: { height: 1, backgroundColor: theme.border },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 13,
  },
  rowLabel: { color: theme.textSecondary, fontSize: 14 },
  rowValue: {
    color: theme.text,
    fontWeight: "600",
    fontSize: 14,
    textTransform: "capitalize",
    flexShrink: 1,
    textAlign: "right",
    marginLeft: 12,
  },
  emptyDetail: {
    color: theme.textMuted,
    fontSize: 13,
    paddingVertical: 16,
    textAlign: "center",
  },
  // manual
  hint: { color: theme.textMuted, fontSize: 13, marginBottom: 6 },
  infoText: { color: theme.textSecondary, fontSize: 13, marginTop: 6 },
  label: {
    fontSize: 11,
    fontWeight: "600",
    color: theme.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 10,
    marginBottom: 4,
  },
  input: {
    backgroundColor: theme.inputBg,
    borderWidth: 1,
    borderColor: theme.inputBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: theme.text,
    fontSize: 15,
  },
  textarea: { minHeight: 70, textAlignVertical: "top" },
  timeRow: { flexDirection: "row", gap: 12 },
  modeRow: { flexDirection: "row", gap: 8 },
  modeChip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: theme.radiusSm,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  modeChipActive: { backgroundColor: theme.primary, borderColor: theme.primary },
  modeText: { fontSize: 13, color: theme.textSecondary, fontWeight: "600" },
  modeTextActive: { color: "#fff" },
  checkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: theme.inputBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxOn: { backgroundColor: theme.primary, borderColor: theme.primary },
  checkMark: { color: "#fff", fontSize: 13, fontWeight: "700" },
  checkLabel: { color: theme.textSecondary, fontSize: 14 },
  breaksHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  addBreakBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: theme.radiusSm,
    backgroundColor: theme.primaryGlow,
  },
  addBreakText: { color: theme.primary, fontSize: 12, fontWeight: "600" },
  breakRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    marginTop: 6,
  },
  removeBreakBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  editBanner: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: theme.primaryGlow,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 8,
  },
  editBannerText: { color: theme.text, fontSize: 14 },
  warnCard: {
    borderRadius: theme.radius,
    borderWidth: 1,
    padding: 14,
    marginTop: 10,
  },
  warnLeave: {
    backgroundColor: "rgba(245,158,11,0.08)",
    borderColor: "rgba(245,158,11,0.3)",
  },
  warnClocked: {
    backgroundColor: "rgba(14,165,233,0.08)",
    borderColor: "rgba(14,165,233,0.3)",
  },
  warnExisting: {
    backgroundColor: theme.glass,
    borderColor: theme.glassBorder,
  },
  warnTitle: { color: theme.text, fontSize: 14, fontWeight: "700" },
  warnBody: { color: theme.textSecondary, fontSize: 13, marginTop: 4 },
  existingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  existingLabel: { color: theme.textSecondary, fontSize: 13 },
  existingTime: { color: theme.text, fontSize: 13, fontWeight: "600" },
  editExistingBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: theme.primary,
    borderRadius: theme.radiusSm,
    paddingVertical: 11,
    marginTop: 12,
  },
  editExistingText: { color: "#fff", fontSize: 14, fontWeight: "600" },
  submit: {
    backgroundColor: theme.primary,
    borderRadius: theme.radiusSm,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 20,
  },
  submitDisabled: { opacity: 0.5 },
  submitText: { color: "#fff", fontSize: 15, fontWeight: "600" },
  requestsSection: {
    marginTop: 22,
    paddingTop: 18,
    borderTopWidth: 1,
    borderTopColor: theme.border,
    gap: 4,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
    marginTop: 6,
  },
  sectionTitle: { fontSize: 15, fontWeight: "700", color: theme.text },
  requestItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    padding: 12,
  },
  requestDate: { color: theme.text, fontSize: 14, fontWeight: "600" },
  requestMeta: { color: theme.textSecondary, fontSize: 12, marginTop: 2 },
  requestReason: { color: theme.textMuted, fontSize: 12, marginTop: 2 },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: theme.radiusFull,
  },
  statusText: { fontSize: 11, fontWeight: "700" },
  // analytics
  analyticsHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  analyticsTitle: { fontSize: 17, fontWeight: "800", color: theme.text },
  exportRow: { flexDirection: "row", gap: 10, marginVertical: 6 },
  exportBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: theme.radiusSm,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  exportBtnBusy: { opacity: 0.7 },
  exportText: { color: theme.primary, fontSize: 13, fontWeight: "700" },
  doughnutRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  rangeRow: { flexDirection: "row", gap: 8, marginBottom: 6, flexWrap: "wrap" },
  rangeChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: theme.radiusFull,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  rangeChipActive: { backgroundColor: theme.primary, borderColor: theme.primary },
  rangeText: { fontSize: 13, color: theme.textSecondary, fontWeight: "600" },
  rangeTextActive: { color: "#fff" },
  customRange: { flexDirection: "row", gap: 12, marginBottom: 6 },
  statsRow: { flexDirection: "row", gap: 10, marginVertical: 8 },
  statCard: {
    flex: 1,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    paddingVertical: 14,
    alignItems: "center",
    gap: 3,
  },
  statValue: { fontSize: 17, fontWeight: "800" },
  statLabel: {
    fontSize: 10,
    color: theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  chartCard: {
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusLg,
    padding: 14,
    gap: 10,
  },
  chartRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  chartDate: { width: 54, fontSize: 11, color: theme.textSecondary },
  chartBarTrack: {
    flex: 1,
    height: 10,
    borderRadius: 5,
    backgroundColor: theme.surface,
    overflow: "hidden",
  },
  chartBarFill: { height: "100%", borderRadius: 5, backgroundColor: theme.primary },
  chartValue: {
    width: 56,
    fontSize: 11,
    color: theme.text,
    textAlign: "right",
    fontWeight: "600",
  },
  tableCard: {
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusLg,
    overflow: "hidden",
  },
  tableRow: {
    flexDirection: "row",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  tableHead: { backgroundColor: theme.surface },
  th: {
    flex: 1,
    fontSize: 11,
    fontWeight: "700",
    color: theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  td: { flex: 1, fontSize: 13, color: theme.text },
});

