import { StyleSheet } from "react-native";
import type { Theme } from "../../src/theme";

export const makeStyles = (theme: Theme) =>
  StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.bg },
  center: { alignItems: "center", justifyContent: "center" },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
  },
  list: { padding: 16, gap: 10, paddingBottom: 32 },
  heading: {
    fontSize: 24,
    fontWeight: "800",
    color: theme.text,
    letterSpacing: -0.5,
    marginBottom: 12,
  },
  tabRow: {
    flexDirection: "row",
    backgroundColor: theme.surface,
    borderRadius: theme.radiusSm,
    padding: 3,
    gap: 3,
    marginBottom: 12,
  },
  tabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 9,
    borderRadius: 5,
  },
  tabBtnActive: { backgroundColor: theme.primary },
  tabText: { fontSize: 12, color: theme.textSecondary, fontWeight: "600" },
  tabTextActive: { color: "#fff" },
  backlogHint: { color: theme.textMuted, fontSize: 13, flex: 1 },
  backlogToolbar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  filterToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: theme.radiusFull,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  filterToggleActive: { backgroundColor: theme.primary, borderColor: theme.primary },
  filterToggleText: { fontSize: 12, color: theme.textSecondary, fontWeight: "600" },
  filterToggleTextActive: { color: "#fff" },
  filterPanel: {
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    padding: 14,
    gap: 6,
    marginBottom: 8,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: theme.inputBg,
    borderWidth: 1,
    borderColor: theme.inputBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  searchInput: { flex: 1, color: theme.text, fontSize: 14, paddingVertical: 8 },
  clearFiltersBtn: {
    alignSelf: "flex-start",
    marginTop: 6,
    paddingVertical: 6,
  },
  clearFiltersText: { color: theme.primary, fontSize: 13, fontWeight: "600" },
  filterRow: { gap: 8, paddingVertical: 4, marginBottom: 8 },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: theme.radiusFull,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  filterChipActive: { backgroundColor: theme.primary, borderColor: theme.primary },
  filterText: { fontSize: 13, color: theme.textSecondary, fontWeight: "500" },
  filterTextActive: { color: "#fff", fontWeight: "600" },
  sprintHeader: {
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    padding: 14,
    gap: 4,
    marginBottom: 8,
  },
  sprintHeaderTitle: { fontSize: 16, fontWeight: "800", color: theme.text },
  sprintHeaderSub: { fontSize: 12, color: theme.textSecondary },
  sprintToolbar: { flexDirection: "row", gap: 8, marginBottom: 8 },
  toolbarBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: theme.radiusSm,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  toolbarBtnActive: { borderColor: theme.primary },
  toolbarBtnText: { fontSize: 12, color: theme.text, fontWeight: "600" },
  importPanel: {
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    padding: 12,
    gap: 8,
    marginBottom: 8,
  },
  importHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  importHeaderText: { fontSize: 13, fontWeight: "700", color: theme.text },
  importEmpty: { color: theme.textMuted, fontSize: 13, paddingVertical: 8 },
  importItem: {
    backgroundColor: theme.surface,
    borderRadius: theme.radiusSm,
    padding: 10,
    gap: 8,
  },
  importItemActive: { borderWidth: 1, borderColor: theme.primary },
  importItemTop: { flexDirection: "row", alignItems: "center", gap: 8 },
  importItemKey: { fontSize: 11, fontWeight: "700", color: theme.primaryLight },
  importPriBadge: {
    borderRadius: theme.radiusSm,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  importPriText: { fontSize: 10, fontWeight: "700" },
  importItemTitle: { flex: 1, fontSize: 13, color: theme.text },
  importBtn: {
    backgroundColor: theme.primary,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  importBtnText: { color: "#fff", fontSize: 12, fontWeight: "600" },
  importConfig: { gap: 4 },
  importConfigActions: { flexDirection: "row", gap: 8, marginTop: 8 },
  importConfirmBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: theme.success,
    borderRadius: theme.radiusSm,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  importConfirmText: { color: "#fff", fontSize: 13, fontWeight: "600" },
  importCancelBtn: {
    backgroundColor: theme.surface,
    borderRadius: theme.radiusSm,
    paddingVertical: 10,
    paddingHorizontal: 14,
    justifyContent: "center",
  },
  importCancelText: { color: theme.textSecondary, fontSize: 13, fontWeight: "600" },
  progressCard: {
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    padding: 16,
    gap: 10,
    marginBottom: 8,
  },
  progressInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressLabel: { color: theme.text, fontWeight: "600", fontSize: 14 },
  progressPct: { color: theme.primary, fontWeight: "800", fontSize: 16 },
  progressBar: {
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.surface,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: theme.primary,
  },
  statusCounts: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  statusCount: { fontSize: 12, fontWeight: "600" },
  progressPoints: { color: theme.textSecondary, fontSize: 12, fontWeight: "600" },
  lifecycleRow: { flexDirection: "row", gap: 8, marginTop: 4 },
  lifecycleBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: theme.primary,
    borderRadius: theme.radiusSm,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  completeBtn: { backgroundColor: theme.success },
  lifecycleBtnText: { color: "#fff", fontWeight: "600", fontSize: 13 },
  disabled: { opacity: 0.5 },
  card: {
    flexDirection: "row",
    gap: 12,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    padding: 14,
  },
  check: { paddingTop: 1 },
  cardBody: { flex: 1, gap: 8 },
  title: { fontSize: 15, fontWeight: "600", color: theme.text, lineHeight: 20 },
  titleDone: { textDecorationLine: "line-through", color: theme.textMuted },
  metaRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  badge: { borderRadius: theme.radiusSm, paddingHorizontal: 8, paddingVertical: 3 },
  badgeText: { fontSize: 11, fontWeight: "600" },
  priority: { flexDirection: "row", alignItems: "center", gap: 5 },
  dot: { width: 8, height: 8, borderRadius: 4 },
  priorityText: { fontSize: 11, color: theme.textSecondary },
  empty: { alignItems: "center", gap: 10, paddingTop: 80, paddingHorizontal: 24 },
  emptyText: { color: theme.text, fontSize: 15, fontWeight: "600" },
  emptySub: { color: theme.textMuted, fontSize: 13, textAlign: "center" },
  label: {
    fontSize: 11,
    fontWeight: "600",
    color: theme.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 8,
  },
  segment: {
    flexDirection: "row",
    backgroundColor: theme.surface,
    borderRadius: theme.radiusSm,
    padding: 3,
    gap: 3,
  },
  segmentBtn: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 5,
    alignItems: "center",
  },
  segmentBtnActive: { backgroundColor: theme.primary },
  segmentText: { fontSize: 13, color: theme.textSecondary, fontWeight: "600" },
  segmentTextActive: { color: "#fff" },
});
