// Curated emoji dataset — the always-available fallback used when the bundled
// image set (scripts/generate-emoji.mjs → generated.ts) has not been produced.
// Renders native unicode glyphs. The picker prefers GENERATED_EMOJI when
// present (see emojiStore.ts), so installing emoji-datasource-apple upgrades the
// look without touching this file.
//
// Mirrored in mobile/src/emoji/emojiData.ts.

import type { Emoji, EmojiCategory } from "./types";

function mk(
    native: string,
    id: string,
    name: string,
    category: EmojiCategory,
    keywords: string[],
    order: number,
    skins?: string[]
): Emoji {
    const unified = [...native]
        .map((c) => c.codePointAt(0)!.toString(16).toUpperCase())
        .join("-");
    return {
        id,
        name,
        native,
        keywords,
        category,
        sortOrder: order,
        base: { unified, native, sheetX: 0, sheetY: 0, image: `${unified}.png` },
        ...(skins
            ? {
                  skins: skins.map((sn) => {
                      const u = [...sn]
                          .map((c) => c.codePointAt(0)!.toString(16).toUpperCase())
                          .join("-");
                      return { unified: u, native: sn, sheetX: 0, sheetY: 0, image: `${u}.png` };
                  }),
              }
            : {}),
    };
}

let n = 0;
const o = () => n++;

export const CURATED_EMOJI: Emoji[] = [
    // ── Smileys & Emotion ───────────────────────────────────────────────
    mk("😀", "grinning", "Grinning Face", "smileys", ["smile", "happy", "joy", "grin"], o()),
    mk("😁", "grin", "Beaming Face", "smileys", ["smile", "happy", "teeth"], o()),
    mk("😂", "joy", "Face With Tears of Joy", "smileys", ["lol", "laugh", "cry", "haha"], o()),
    mk("🤣", "rofl", "Rolling on the Floor Laughing", "smileys", ["lol", "rofl", "laugh"], o()),
    mk("😃", "smiley", "Smiling Face With Open Mouth", "smileys", ["happy", "joy"], o()),
    mk("😄", "smile", "Smiling Face With Open Mouth and Smiling Eyes", "smileys", ["happy", "joy"], o()),
    mk("😅", "sweat_smile", "Smiling Face With Sweat", "smileys", ["hot", "relief", "phew"], o()),
    mk("😆", "laughing", "Grinning Squinting Face", "smileys", ["haha", "laugh"], o()),
    mk("😉", "wink", "Winking Face", "smileys", ["flirt", "wink"], o()),
    mk("😊", "blush", "Smiling Face With Smiling Eyes", "smileys", ["happy", "blush", "shy"], o()),
    mk("😋", "yum", "Face Savoring Food", "smileys", ["tongue", "delicious", "yum"], o()),
    mk("😎", "sunglasses", "Smiling Face With Sunglasses", "smileys", ["cool", "shades"], o()),
    mk("😍", "heart_eyes", "Smiling Face With Heart-Eyes", "smileys", ["love", "crush"], o()),
    mk("🥰", "smiling_face_with_three_hearts", "Smiling Face With Hearts", "smileys", ["love", "adore"], o()),
    mk("😘", "kissing_heart", "Face Blowing a Kiss", "smileys", ["love", "kiss"], o()),
    mk("😗", "kissing", "Kissing Face", "smileys", ["kiss"], o()),
    mk("🙂", "slightly_smiling_face", "Slightly Smiling Face", "smileys", ["smile"], o()),
    mk("🙃", "upside_down_face", "Upside-Down Face", "smileys", ["silly", "sarcasm"], o()),
    mk("🤗", "hugs", "Hugging Face", "smileys", ["hug", "embrace"], o()),
    mk("🤩", "star_struck", "Star-Struck", "smileys", ["wow", "amazing", "excited"], o()),
    mk("🤔", "thinking", "Thinking Face", "smileys", ["hmm", "think", "consider"], o()),
    mk("🤨", "raised_eyebrow", "Face With Raised Eyebrow", "smileys", ["skeptical", "doubt"], o()),
    mk("😐", "neutral_face", "Neutral Face", "smileys", ["meh", "blank"], o()),
    mk("😑", "expressionless", "Expressionless Face", "smileys", ["blank", "meh"], o()),
    mk("🙄", "roll_eyes", "Face With Rolling Eyes", "smileys", ["whatever", "annoyed"], o()),
    mk("😏", "smirk", "Smirking Face", "smileys", ["smug", "flirt"], o()),
    mk("😴", "sleeping", "Sleeping Face", "smileys", ["sleep", "zzz", "tired"], o()),
    mk("😪", "sleepy", "Sleepy Face", "smileys", ["tired", "sleep"], o()),
    mk("😌", "relieved", "Relieved Face", "smileys", ["calm", "relief"], o()),
    mk("😛", "stuck_out_tongue", "Face With Tongue", "smileys", ["tongue", "playful"], o()),
    mk("😜", "stuck_out_tongue_winking_eye", "Winking Face With Tongue", "smileys", ["silly", "playful"], o()),
    mk("🤤", "drooling_face", "Drooling Face", "smileys", ["drool", "want"], o()),
    mk("😒", "unamused", "Unamused Face", "smileys", ["meh", "annoyed"], o()),
    mk("😔", "pensive", "Pensive Face", "smileys", ["sad", "down"], o()),
    mk("😕", "confused", "Confused Face", "smileys", ["confused", "unsure"], o()),
    mk("🙁", "slightly_frowning_face", "Slightly Frowning Face", "smileys", ["sad", "frown"], o()),
    mk("😣", "persevere", "Persevering Face", "smileys", ["struggle"], o()),
    mk("😖", "confounded", "Confounded Face", "smileys", ["frustrated"], o()),
    mk("😞", "disappointed", "Disappointed Face", "smileys", ["sad", "down"], o()),
    mk("😟", "worried", "Worried Face", "smileys", ["worry", "concern"], o()),
    mk("😢", "cry", "Crying Face", "smileys", ["sad", "tear", "cry"], o()),
    mk("😭", "sob", "Loudly Crying Face", "smileys", ["sob", "cry", "bawl"], o()),
    mk("😤", "triumph", "Face With Steam From Nose", "smileys", ["angry", "frustrated"], o()),
    mk("😠", "angry", "Angry Face", "smileys", ["mad", "angry"], o()),
    mk("😡", "rage", "Pouting Face", "smileys", ["mad", "rage", "angry"], o()),
    mk("🤬", "cursing_face", "Face With Symbols on Mouth", "smileys", ["swear", "curse"], o()),
    mk("🤯", "exploding_head", "Exploding Head", "smileys", ["mind blown", "shocked"], o()),
    mk("😳", "flushed", "Flushed Face", "smileys", ["embarrassed", "shy"], o()),
    mk("🥵", "hot_face", "Hot Face", "smileys", ["heat", "sweat"], o()),
    mk("🥶", "cold_face", "Cold Face", "smileys", ["freezing", "cold"], o()),
    mk("😱", "scream", "Face Screaming in Fear", "smileys", ["scared", "shock"], o()),
    mk("😨", "fearful", "Fearful Face", "smileys", ["scared", "fear"], o()),
    mk("😰", "cold_sweat", "Anxious Face With Sweat", "smileys", ["nervous", "anxious"], o()),
    mk("😬", "grimacing", "Grimacing Face", "smileys", ["awkward", "yikes"], o()),
    mk("🤐", "zipper_mouth_face", "Zipper-Mouth Face", "smileys", ["quiet", "secret"], o()),
    mk("🤫", "shushing_face", "Shushing Face", "smileys", ["quiet", "shh"], o()),
    mk("🤥", "lying_face", "Lying Face", "smileys", ["lie", "pinocchio"], o()),
    mk("😷", "mask", "Face With Medical Mask", "smileys", ["sick", "mask"], o()),
    mk("🤒", "face_with_thermometer", "Face With Thermometer", "smileys", ["sick", "ill"], o()),
    mk("🤕", "face_with_head_bandage", "Face With Head-Bandage", "smileys", ["hurt", "injured"], o()),
    mk("🤢", "nauseated_face", "Nauseated Face", "smileys", ["sick", "gross"], o()),
    mk("🤮", "vomiting_face", "Face Vomiting", "smileys", ["sick", "puke"], o()),
    mk("🥳", "partying_face", "Partying Face", "smileys", ["party", "celebrate"], o()),
    mk("🤠", "cowboy_hat_face", "Cowboy Hat Face", "smileys", ["cowboy", "yeehaw"], o()),
    mk("😇", "innocent", "Smiling Face With Halo", "smileys", ["angel", "innocent"], o()),
    mk("🤓", "nerd_face", "Nerd Face", "smileys", ["nerd", "geek"], o()),
    mk("💀", "skull", "Skull", "smileys", ["dead", "skull", "lol"], o()),
    mk("👻", "ghost", "Ghost", "smileys", ["ghost", "boo", "spooky"], o()),
    mk("👽", "alien", "Alien", "smileys", ["alien", "ufo"], o()),
    mk("🤖", "robot", "Robot", "smileys", ["robot", "bot"], o()),
    mk("💩", "poop", "Pile of Poo", "smileys", ["poop", "crap"], o()),
    mk("🤡", "clown_face", "Clown Face", "smileys", ["clown"], o()),

    // ── People & Body ───────────────────────────────────────────────────
    mk("👋", "wave", "Waving Hand", "people", ["hi", "hello", "bye", "wave"], o(), ["👋🏻", "👋🏼", "👋🏽", "👋🏾", "👋🏿"]),
    mk("🤚", "raised_back_of_hand", "Raised Back of Hand", "people", ["hand"], o(), ["🤚🏻", "🤚🏼", "🤚🏽", "🤚🏾", "🤚🏿"]),
    mk("🖐️", "raised_hand_with_fingers_splayed", "Hand With Fingers Splayed", "people", ["hand", "five"], o(), ["🖐🏻", "🖐🏼", "🖐🏽", "🖐🏾", "🖐🏿"]),
    mk("✋", "hand", "Raised Hand", "people", ["stop", "high five"], o(), ["✋🏻", "✋🏼", "✋🏽", "✋🏾", "✋🏿"]),
    mk("👌", "ok_hand", "OK Hand", "people", ["ok", "perfect"], o(), ["👌🏻", "👌🏼", "👌🏽", "👌🏾", "👌🏿"]),
    mk("🤌", "pinched_fingers", "Pinched Fingers", "people", ["italian", "chef"], o(), ["🤌🏻", "🤌🏼", "🤌🏽", "🤌🏾", "🤌🏿"]),
    mk("✌️", "v", "Victory Hand", "people", ["peace", "victory"], o(), ["✌🏻", "✌🏼", "✌🏽", "✌🏾", "✌🏿"]),
    mk("🤞", "crossed_fingers", "Crossed Fingers", "people", ["luck", "hope"], o(), ["🤞🏻", "🤞🏼", "🤞🏽", "🤞🏾", "🤞🏿"]),
    mk("🤟", "love_you_gesture", "Love-You Gesture", "people", ["love"], o(), ["🤟🏻", "🤟🏼", "🤟🏽", "🤟🏾", "🤟🏿"]),
    mk("🤘", "metal", "Sign of the Horns", "people", ["rock", "metal"], o(), ["🤘🏻", "🤘🏼", "🤘🏽", "🤘🏾", "🤘🏿"]),
    mk("🤙", "call_me_hand", "Call Me Hand", "people", ["call", "shaka"], o(), ["🤙🏻", "🤙🏼", "🤙🏽", "🤙🏾", "🤙🏿"]),
    mk("👈", "point_left", "Backhand Index Pointing Left", "people", ["point", "left"], o(), ["👈🏻", "👈🏼", "👈🏽", "👈🏾", "👈🏿"]),
    mk("👉", "point_right", "Backhand Index Pointing Right", "people", ["point", "right"], o(), ["👉🏻", "👉🏼", "👉🏽", "👉🏾", "👉🏿"]),
    mk("👆", "point_up_2", "Backhand Index Pointing Up", "people", ["point", "up"], o(), ["👆🏻", "👆🏼", "👆🏽", "👆🏾", "👆🏿"]),
    mk("👇", "point_down", "Backhand Index Pointing Down", "people", ["point", "down"], o(), ["👇🏻", "👇🏼", "👇🏽", "👇🏾", "👇🏿"]),
    mk("☝️", "point_up", "Index Pointing Up", "people", ["point", "up", "one"], o(), ["☝🏻", "☝🏼", "☝🏽", "☝🏾", "☝🏿"]),
    mk("👍", "thumbsup", "Thumbs Up", "people", ["+1", "yes", "approve", "ok", "like"], o(), ["👍🏻", "👍🏼", "👍🏽", "👍🏾", "👍🏿"]),
    mk("👎", "thumbsdown", "Thumbs Down", "people", ["-1", "no", "dislike"], o(), ["👎🏻", "👎🏼", "👎🏽", "👎🏾", "👎🏿"]),
    mk("✊", "fist_raised", "Raised Fist", "people", ["fist", "power"], o(), ["✊🏻", "✊🏼", "✊🏽", "✊🏾", "✊🏿"]),
    mk("👊", "fist_oncoming", "Oncoming Fist", "people", ["punch", "bro fist"], o(), ["👊🏻", "👊🏼", "👊🏽", "👊🏾", "👊🏿"]),
    mk("👏", "clap", "Clapping Hands", "people", ["clap", "applause", "bravo"], o(), ["👏🏻", "👏🏼", "👏🏽", "👏🏾", "👏🏿"]),
    mk("🙌", "raised_hands", "Raising Hands", "people", ["celebrate", "praise", "yay"], o(), ["🙌🏻", "🙌🏼", "🙌🏽", "🙌🏾", "🙌🏿"]),
    mk("👐", "open_hands", "Open Hands", "people", ["open", "hug"], o(), ["👐🏻", "👐🏼", "👐🏽", "👐🏾", "👐🏿"]),
    mk("🤲", "palms_up_together", "Palms Up Together", "people", ["pray", "cupped"], o(), ["🤲🏻", "🤲🏼", "🤲🏽", "🤲🏾", "🤲🏿"]),
    mk("🤝", "handshake", "Handshake", "people", ["deal", "agree", "shake"], o()),
    mk("🙏", "pray", "Folded Hands", "people", ["pray", "thanks", "please", "hope"], o(), ["🙏🏻", "🙏🏼", "🙏🏽", "🙏🏾", "🙏🏿"]),
    mk("💪", "muscle", "Flexed Biceps", "people", ["strong", "flex", "gym"], o(), ["💪🏻", "💪🏼", "💪🏽", "💪🏾", "💪🏿"]),
    mk("🧠", "brain", "Brain", "people", ["smart", "think"], o()),
    mk("👀", "eyes", "Eyes", "people", ["look", "see", "watch"], o()),
    mk("👁️", "eye", "Eye", "people", ["look", "see"], o()),

    // ── Animals & Nature ────────────────────────────────────────────────
    mk("🐶", "dog", "Dog Face", "nature", ["dog", "puppy", "pet"], o()),
    mk("🐱", "cat", "Cat Face", "nature", ["cat", "kitten", "pet"], o()),
    mk("🐭", "mouse", "Mouse Face", "nature", ["mouse"], o()),
    mk("🐹", "hamster", "Hamster", "nature", ["hamster", "pet"], o()),
    mk("🐰", "rabbit", "Rabbit Face", "nature", ["bunny", "rabbit"], o()),
    mk("🦊", "fox_face", "Fox", "nature", ["fox"], o()),
    mk("🐻", "bear", "Bear", "nature", ["bear"], o()),
    mk("🐼", "panda_face", "Panda", "nature", ["panda"], o()),
    mk("🐨", "koala", "Koala", "nature", ["koala"], o()),
    mk("🐯", "tiger", "Tiger Face", "nature", ["tiger"], o()),
    mk("🦁", "lion", "Lion", "nature", ["lion"], o()),
    mk("🐮", "cow", "Cow Face", "nature", ["cow"], o()),
    mk("🐷", "pig", "Pig Face", "nature", ["pig"], o()),
    mk("🐸", "frog", "Frog", "nature", ["frog"], o()),
    mk("🐵", "monkey_face", "Monkey Face", "nature", ["monkey"], o()),
    mk("🐔", "chicken", "Chicken", "nature", ["chicken"], o()),
    mk("🐧", "penguin", "Penguin", "nature", ["penguin"], o()),
    mk("🐦", "bird", "Bird", "nature", ["bird"], o()),
    mk("🦄", "unicorn", "Unicorn", "nature", ["unicorn", "magic"], o()),
    mk("🐝", "bee", "Honeybee", "nature", ["bee"], o()),
    mk("🦋", "butterfly", "Butterfly", "nature", ["butterfly"], o()),
    mk("🐢", "turtle", "Turtle", "nature", ["turtle", "slow"], o()),
    mk("🐍", "snake", "Snake", "nature", ["snake"], o()),
    mk("🐙", "octopus", "Octopus", "nature", ["octopus"], o()),
    mk("🐬", "dolphin", "Dolphin", "nature", ["dolphin"], o()),
    mk("🐳", "whale", "Spouting Whale", "nature", ["whale"], o()),
    mk("🌸", "cherry_blossom", "Cherry Blossom", "nature", ["flower", "spring"], o()),
    mk("🌺", "hibiscus", "Hibiscus", "nature", ["flower"], o()),
    mk("🌻", "sunflower", "Sunflower", "nature", ["flower", "sun"], o()),
    mk("🌹", "rose", "Rose", "nature", ["flower", "love"], o()),
    mk("🌲", "evergreen_tree", "Evergreen Tree", "nature", ["tree", "forest"], o()),
    mk("🌴", "palm_tree", "Palm Tree", "nature", ["tree", "beach"], o()),
    mk("🌵", "cactus", "Cactus", "nature", ["cactus", "desert"], o()),
    mk("☀️", "sunny", "Sun", "nature", ["sun", "weather", "hot"], o()),
    mk("🌙", "crescent_moon", "Crescent Moon", "nature", ["moon", "night"], o()),
    mk("⭐", "star", "Star", "nature", ["star", "favorite"], o()),
    mk("🌟", "star2", "Glowing Star", "nature", ["star", "sparkle"], o()),
    mk("⚡", "zap", "High Voltage", "nature", ["lightning", "fast", "power"], o()),
    mk("🔥", "fire", "Fire", "nature", ["fire", "lit", "hot", "flame"], o()),
    mk("🌈", "rainbow", "Rainbow", "nature", ["rainbow", "pride"], o()),
    mk("❄️", "snowflake", "Snowflake", "nature", ["snow", "cold", "winter"], o()),
    mk("💧", "droplet", "Droplet", "nature", ["water", "drop"], o()),
    mk("🌊", "ocean", "Water Wave", "nature", ["wave", "ocean", "sea"], o()),

    // ── Food & Drink ────────────────────────────────────────────────────
    mk("🍏", "green_apple", "Green Apple", "food", ["apple", "fruit"], o()),
    mk("🍎", "apple", "Red Apple", "food", ["apple", "fruit"], o()),
    mk("🍊", "tangerine", "Tangerine", "food", ["orange", "fruit"], o()),
    mk("🍋", "lemon", "Lemon", "food", ["lemon", "sour"], o()),
    mk("🍌", "banana", "Banana", "food", ["banana", "fruit"], o()),
    mk("🍉", "watermelon", "Watermelon", "food", ["fruit", "summer"], o()),
    mk("🍇", "grapes", "Grapes", "food", ["fruit", "wine"], o()),
    mk("🍓", "strawberry", "Strawberry", "food", ["fruit", "berry"], o()),
    mk("🫐", "blueberries", "Blueberries", "food", ["fruit", "berry"], o()),
    mk("🍒", "cherries", "Cherries", "food", ["fruit"], o()),
    mk("🍑", "peach", "Peach", "food", ["fruit", "butt"], o()),
    mk("🥭", "mango", "Mango", "food", ["fruit"], o()),
    mk("🍍", "pineapple", "Pineapple", "food", ["fruit"], o()),
    mk("🥥", "coconut", "Coconut", "food", ["fruit"], o()),
    mk("🥝", "kiwi_fruit", "Kiwi Fruit", "food", ["fruit"], o()),
    mk("🍅", "tomato", "Tomato", "food", ["vegetable", "fruit"], o()),
    mk("🥑", "avocado", "Avocado", "food", ["fruit", "toast"], o()),
    mk("🍆", "eggplant", "Eggplant", "food", ["vegetable", "aubergine"], o()),
    mk("🥕", "carrot", "Carrot", "food", ["vegetable"], o()),
    mk("🌽", "corn", "Ear of Corn", "food", ["corn", "vegetable"], o()),
    mk("🌶️", "hot_pepper", "Hot Pepper", "food", ["spicy", "chili"], o()),
    mk("🍞", "bread", "Bread", "food", ["bread", "toast"], o()),
    mk("🧀", "cheese", "Cheese Wedge", "food", ["cheese"], o()),
    mk("🍗", "poultry_leg", "Poultry Leg", "food", ["chicken", "meat"], o()),
    mk("🍔", "hamburger", "Hamburger", "food", ["burger", "fast food"], o()),
    mk("🍟", "fries", "French Fries", "food", ["fries", "fast food"], o()),
    mk("🍕", "pizza", "Pizza", "food", ["pizza", "food"], o()),
    mk("🌭", "hotdog", "Hot Dog", "food", ["hotdog", "sausage"], o()),
    mk("🌮", "taco", "Taco", "food", ["taco", "mexican"], o()),
    mk("🌯", "burrito", "Burrito", "food", ["burrito", "mexican"], o()),
    mk("🍜", "ramen", "Steaming Bowl", "food", ["noodles", "ramen", "soup"], o()),
    mk("🍣", "sushi", "Sushi", "food", ["sushi", "japanese"], o()),
    mk("🍦", "icecream", "Soft Ice Cream", "food", ["ice cream", "dessert"], o()),
    mk("🍩", "doughnut", "Doughnut", "food", ["donut", "dessert"], o()),
    mk("🍪", "cookie", "Cookie", "food", ["cookie", "dessert"], o()),
    mk("🎂", "birthday", "Birthday Cake", "food", ["cake", "birthday", "celebrate"], o()),
    mk("🍰", "cake", "Shortcake", "food", ["cake", "dessert"], o()),
    mk("🍫", "chocolate_bar", "Chocolate Bar", "food", ["chocolate", "candy"], o()),
    mk("🍬", "candy", "Candy", "food", ["candy", "sweet"], o()),
    mk("☕", "coffee", "Hot Beverage", "food", ["coffee", "tea", "drink"], o()),
    mk("🍵", "tea", "Teacup Without Handle", "food", ["tea", "drink"], o()),
    mk("🍺", "beer", "Beer Mug", "food", ["beer", "drink"], o()),
    mk("🍻", "beers", "Clinking Beer Mugs", "food", ["beer", "cheers"], o()),
    mk("🍷", "wine_glass", "Wine Glass", "food", ["wine", "drink"], o()),
    mk("🥂", "champagne", "Clinking Glasses", "food", ["cheers", "celebrate"], o()),
    mk("🍸", "cocktail", "Cocktail Glass", "food", ["drink", "martini"], o()),

    // ── Activities ──────────────────────────────────────────────────────
    mk("⚽", "soccer", "Soccer Ball", "activity", ["football", "soccer", "sport"], o()),
    mk("🏀", "basketball", "Basketball", "activity", ["sport", "basketball"], o()),
    mk("🏈", "football", "American Football", "activity", ["football", "sport"], o()),
    mk("⚾", "baseball", "Baseball", "activity", ["baseball", "sport"], o()),
    mk("🎾", "tennis", "Tennis", "activity", ["tennis", "sport"], o()),
    mk("🏐", "volleyball", "Volleyball", "activity", ["volleyball", "sport"], o()),
    mk("🏓", "ping_pong", "Ping Pong", "activity", ["table tennis", "sport"], o()),
    mk("🏸", "badminton", "Badminton", "activity", ["badminton", "sport"], o()),
    mk("🥅", "goal_net", "Goal Net", "activity", ["goal", "sport"], o()),
    mk("⛳", "golf", "Flag in Hole", "activity", ["golf", "sport"], o()),
    mk("🎯", "dart", "Bullseye", "activity", ["target", "dart", "goal"], o()),
    mk("🎮", "video_game", "Video Game", "activity", ["game", "controller", "gaming"], o()),
    mk("🎲", "game_die", "Game Die", "activity", ["dice", "game"], o()),
    mk("🧩", "jigsaw", "Puzzle Piece", "activity", ["puzzle", "piece"], o()),
    mk("🎨", "art", "Artist Palette", "activity", ["art", "paint"], o()),
    mk("🎬", "clapper", "Clapper Board", "activity", ["movie", "film"], o()),
    mk("🎤", "microphone", "Microphone", "activity", ["mic", "sing", "karaoke"], o()),
    mk("🎧", "headphones", "Headphone", "activity", ["music", "audio"], o()),
    mk("🎵", "musical_note", "Musical Note", "activity", ["music", "note"], o()),
    mk("🎸", "guitar", "Guitar", "activity", ["music", "guitar"], o()),
    mk("🥇", "1st_place_medal", "1st Place Medal", "activity", ["gold", "winner", "first"], o()),
    mk("🥈", "2nd_place_medal", "2nd Place Medal", "activity", ["silver", "second"], o()),
    mk("🥉", "3rd_place_medal", "3rd Place Medal", "activity", ["bronze", "third"], o()),
    mk("🏆", "trophy", "Trophy", "activity", ["win", "award", "champion"], o()),
    mk("🎉", "tada", "Party Popper", "activity", ["party", "celebrate", "congrats"], o()),
    mk("🎊", "confetti_ball", "Confetti Ball", "activity", ["party", "celebrate"], o()),
    mk("🎈", "balloon", "Balloon", "activity", ["party", "birthday"], o()),
    mk("🎁", "gift", "Wrapped Gift", "activity", ["present", "gift", "birthday"], o()),

    // ── Travel & Places ─────────────────────────────────────────────────
    mk("🚗", "car", "Automobile", "travel", ["car", "drive"], o()),
    mk("🚕", "taxi", "Taxi", "travel", ["taxi", "cab"], o()),
    mk("🚙", "blue_car", "Sport Utility Vehicle", "travel", ["car", "suv"], o()),
    mk("🚌", "bus", "Bus", "travel", ["bus"], o()),
    mk("🚓", "police_car", "Police Car", "travel", ["police"], o()),
    mk("🚑", "ambulance", "Ambulance", "travel", ["ambulance", "emergency"], o()),
    mk("🚒", "fire_engine", "Fire Engine", "travel", ["fire truck"], o()),
    mk("🚲", "bike", "Bicycle", "travel", ["bike", "cycle"], o()),
    mk("🛵", "motor_scooter", "Motor Scooter", "travel", ["scooter"], o()),
    mk("🏍️", "motorcycle", "Motorcycle", "travel", ["motorcycle"], o()),
    mk("✈️", "airplane", "Airplane", "travel", ["plane", "fly", "travel"], o()),
    mk("🚀", "rocket", "Rocket", "travel", ["rocket", "launch", "space", "fast"], o()),
    mk("🛸", "flying_saucer", "Flying Saucer", "travel", ["ufo", "alien"], o()),
    mk("🚁", "helicopter", "Helicopter", "travel", ["helicopter"], o()),
    mk("⛵", "boat", "Sailboat", "travel", ["boat", "sail"], o()),
    mk("🚢", "ship", "Ship", "travel", ["ship", "cruise"], o()),
    mk("🚂", "steam_locomotive", "Locomotive", "travel", ["train"], o()),
    mk("🚆", "train2", "Train", "travel", ["train"], o()),
    mk("🗺️", "world_map", "World Map", "travel", ["map", "travel"], o()),
    mk("🗽", "statue_of_liberty", "Statue of Liberty", "travel", ["new york", "usa"], o()),
    mk("🗼", "tokyo_tower", "Tokyo Tower", "travel", ["tokyo", "japan"], o()),
    mk("🏰", "european_castle", "Castle", "travel", ["castle"], o()),
    mk("🏖️", "beach_umbrella", "Beach With Umbrella", "travel", ["beach", "vacation"], o()),
    mk("🏔️", "mountain_snow", "Snow-Capped Mountain", "travel", ["mountain", "snow"], o()),
    mk("🌋", "volcano", "Volcano", "travel", ["volcano", "eruption"], o()),
    mk("🏠", "house", "House", "travel", ["home", "house"], o()),
    mk("🏢", "office", "Office Building", "travel", ["office", "building", "work"], o()),
    mk("🏥", "hospital", "Hospital", "travel", ["hospital"], o()),
    mk("🏦", "bank", "Bank", "travel", ["bank", "money"], o()),
    mk("🏨", "hotel", "Hotel", "travel", ["hotel"], o()),
    mk("🌆", "city_sunset", "Cityscape at Dusk", "travel", ["city", "sunset"], o()),
    mk("🌃", "night_with_stars", "Night With Stars", "travel", ["night", "city"], o()),

    // ── Objects ─────────────────────────────────────────────────────────
    mk("⌚", "watch", "Watch", "objects", ["time", "watch"], o()),
    mk("📱", "iphone", "Mobile Phone", "objects", ["phone", "mobile", "cell"], o()),
    mk("💻", "computer", "Laptop", "objects", ["laptop", "computer", "work"], o()),
    mk("⌨️", "keyboard", "Keyboard", "objects", ["keyboard", "type"], o()),
    mk("🖥️", "desktop_computer", "Desktop Computer", "objects", ["computer", "desktop"], o()),
    mk("🖨️", "printer", "Printer", "objects", ["printer", "print"], o()),
    mk("🖱️", "computer_mouse", "Computer Mouse", "objects", ["mouse"], o()),
    mk("💾", "floppy_disk", "Floppy Disk", "objects", ["save", "disk"], o()),
    mk("📷", "camera", "Camera", "objects", ["camera", "photo"], o()),
    mk("🎥", "movie_camera", "Movie Camera", "objects", ["video", "film"], o()),
    mk("📞", "telephone_receiver", "Telephone Receiver", "objects", ["phone", "call"], o()),
    mk("📺", "tv", "Television", "objects", ["tv", "television"], o()),
    mk("🔋", "battery", "Battery", "objects", ["battery", "power"], o()),
    mk("🔌", "electric_plug", "Electric Plug", "objects", ["plug", "power"], o()),
    mk("💡", "bulb", "Light Bulb", "objects", ["idea", "light", "bulb"], o()),
    mk("🔦", "flashlight", "Flashlight", "objects", ["flashlight", "torch"], o()),
    mk("📚", "books", "Books", "objects", ["book", "read", "study"], o()),
    mk("📖", "open_book", "Open Book", "objects", ["book", "read"], o()),
    mk("📝", "memo", "Memo", "objects", ["note", "write", "memo"], o()),
    mk("✏️", "pencil2", "Pencil", "objects", ["write", "pencil", "edit"], o()),
    mk("📌", "pushpin", "Pushpin", "objects", ["pin", "location"], o()),
    mk("📎", "paperclip", "Paperclip", "objects", ["clip", "attach"], o()),
    mk("✂️", "scissors", "Scissors", "objects", ["cut", "scissors"], o()),
    mk("🔑", "key", "Key", "objects", ["key", "lock", "password"], o()),
    mk("🔒", "lock", "Locked", "objects", ["lock", "secure", "private"], o()),
    mk("🔓", "unlock", "Unlocked", "objects", ["unlock", "open"], o()),
    mk("🔔", "bell", "Bell", "objects", ["bell", "notification", "alert"], o()),
    mk("💰", "moneybag", "Money Bag", "objects", ["money", "cash", "rich"], o()),
    mk("💵", "dollar", "Dollar Banknote", "objects", ["money", "cash", "dollar"], o()),
    mk("💳", "credit_card", "Credit Card", "objects", ["card", "payment", "money"], o()),
    mk("📦", "package", "Package", "objects", ["box", "package", "delivery"], o()),
    mk("📧", "email", "E-Mail", "objects", ["email", "mail", "message"], o()),
    mk("🎓", "mortar_board", "Graduation Cap", "objects", ["graduate", "school", "education"], o()),
    mk("💼", "briefcase", "Briefcase", "objects", ["work", "business", "office"], o()),
    mk("🛒", "shopping_cart", "Shopping Cart", "objects", ["cart", "shopping"], o()),
    mk("🧹", "broom", "Broom", "objects", ["clean", "sweep"], o()),
    mk("💊", "pill", "Pill", "objects", ["medicine", "pill", "drug"], o()),

    // ── Symbols ─────────────────────────────────────────────────────────
    mk("❤️", "heart", "Red Heart", "symbols", ["love", "heart", "like"], o()),
    mk("🧡", "orange_heart", "Orange Heart", "symbols", ["love", "heart"], o()),
    mk("💛", "yellow_heart", "Yellow Heart", "symbols", ["love", "heart"], o()),
    mk("💚", "green_heart", "Green Heart", "symbols", ["love", "heart"], o()),
    mk("💙", "blue_heart", "Blue Heart", "symbols", ["love", "heart"], o()),
    mk("💜", "purple_heart", "Purple Heart", "symbols", ["love", "heart"], o()),
    mk("🖤", "black_heart", "Black Heart", "symbols", ["love", "heart"], o()),
    mk("🤍", "white_heart", "White Heart", "symbols", ["love", "heart"], o()),
    mk("🤎", "brown_heart", "Brown Heart", "symbols", ["love", "heart"], o()),
    mk("💔", "broken_heart", "Broken Heart", "symbols", ["heartbreak", "sad"], o()),
    mk("❣️", "heavy_heart_exclamation", "Heart Exclamation", "symbols", ["love", "heart"], o()),
    mk("💕", "two_hearts", "Two Hearts", "symbols", ["love", "hearts"], o()),
    mk("💖", "sparkling_heart", "Sparkling Heart", "symbols", ["love", "heart"], o()),
    mk("💗", "heartpulse", "Growing Heart", "symbols", ["love", "heart"], o()),
    mk("💯", "100", "Hundred Points", "symbols", ["100", "perfect", "score"], o()),
    mk("✨", "sparkles", "Sparkles", "symbols", ["sparkle", "shine", "new"], o()),
    mk("⭐", "star_symbol", "Star Symbol", "symbols", ["star", "favorite"], o()),
    mk("💥", "boom", "Collision", "symbols", ["boom", "explode"], o()),
    mk("💫", "dizzy", "Dizzy", "symbols", ["star", "dizzy"], o()),
    mk("💢", "anger", "Anger Symbol", "symbols", ["angry", "mad"], o()),
    mk("💨", "dash", "Dashing Away", "symbols", ["fast", "wind", "dash"], o()),
    mk("✅", "white_check_mark", "Check Mark Button", "symbols", ["check", "done", "yes", "ok"], o()),
    mk("☑️", "ballot_box_with_check", "Check Box With Check", "symbols", ["check", "done"], o()),
    mk("✔️", "heavy_check_mark", "Check Mark", "symbols", ["check", "done", "yes"], o()),
    mk("❌", "x", "Cross Mark", "symbols", ["x", "no", "wrong", "cancel"], o()),
    mk("❎", "negative_squared_cross_mark", "Cross Mark Button", "symbols", ["x", "no"], o()),
    mk("➕", "heavy_plus_sign", "Plus", "symbols", ["plus", "add"], o()),
    mk("➖", "heavy_minus_sign", "Minus", "symbols", ["minus", "subtract"], o()),
    mk("❓", "question", "Question Mark", "symbols", ["question", "ask"], o()),
    mk("❗", "exclamation", "Exclamation Mark", "symbols", ["exclamation", "alert"], o()),
    mk("⚠️", "warning", "Warning", "symbols", ["warning", "alert", "caution"], o()),
    mk("🚫", "no_entry_sign", "Prohibited", "symbols", ["no", "stop", "ban"], o()),
    mk("💤", "zzz", "Zzz", "symbols", ["sleep", "tired", "zzz"], o()),
    mk("🔴", "red_circle", "Red Circle", "symbols", ["red", "circle"], o()),
    mk("🟢", "green_circle", "Green Circle", "symbols", ["green", "circle", "online"], o()),
    mk("🔵", "large_blue_circle", "Blue Circle", "symbols", ["blue", "circle"], o()),

    // ── Flags ───────────────────────────────────────────────────────────
    mk("🏳️", "white_flag", "White Flag", "flags", ["flag", "surrender"], o()),
    mk("🏴", "black_flag", "Black Flag", "flags", ["flag"], o()),
    mk("🏁", "checkered_flag", "Chequered Flag", "flags", ["race", "finish", "flag"], o()),
    mk("🚩", "triangular_flag_on_post", "Triangular Flag", "flags", ["flag", "milestone"], o()),
    mk("🏳️‍🌈", "rainbow_flag", "Rainbow Flag", "flags", ["pride", "lgbt", "flag"], o()),
];

export const HAS_BUNDLED_ASSETS = false;