import { StyleSheet } from "react-native";
import type { Theme } from "../../src/theme";

export const makeStyles = (theme: Theme) =>
  StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.bg },
  center: { alignItems: "center", justifyContent: "center", flex: 1 },
  tabBarScroll: { flexGrow: 0, flexShrink: 0 },
  tabBar: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
    alignItems: "center",
  },
  tabBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: theme.radiusFull,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    height: 36,
  },
  tabBtnActive: {
    backgroundColor: theme.primaryGlow,
    borderColor: theme.primary,
  },
  tabText: { fontSize: 13, color: theme.textSecondary, fontWeight: "600" },
  tabTextActive: { color: theme.primary },
  tabBadge: {
    backgroundColor: theme.warning,
    borderRadius: theme.radiusFull,
    minWidth: 18,
    paddingHorizontal: 5,
    paddingVertical: 1,
    alignItems: "center",
  },
  tabBadgeText: { color: "#fff", fontSize: 11, fontWeight: "700" },
  content: { padding: 16, paddingTop: 4, gap: 10 },
  primaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: theme.primary,
    borderRadius: theme.radiusSm,
    paddingVertical: 12,
  },
  primaryBtnText: { color: "#fff", fontSize: 14, fontWeight: "600" },
  card: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    padding: 12,
  },
  iconWrap: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: theme.primaryGlow,
    alignItems: "center",
    justifyContent: "center",
  },
  body: { flex: 1, gap: 2 },
  name: { fontSize: 15, fontWeight: "600", color: theme.text },
  meta: { fontSize: 12, color: theme.textSecondary },
  statusText: { fontSize: 11, fontWeight: "700", marginTop: 2 },
  iconBtn: { padding: 6 },
  empty: {
    color: theme.textMuted,
    fontSize: 13,
    textAlign: "center",
    paddingTop: 32,
  },
  section: {
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusLg,
    padding: 16,
    gap: 8,
  },
  sectionTitle: { fontSize: 16, fontWeight: "700", color: theme.text },
  hint: { fontSize: 12, color: theme.textSecondary, lineHeight: 17 },
  fieldLabel: {
    fontSize: 12,
    color: theme.textSecondary,
    fontWeight: "500",
    marginTop: 6,
  },
  input: {
    backgroundColor: theme.inputBg,
    borderWidth: 1,
    borderColor: theme.inputBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: theme.text,
    fontSize: 15,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
  },
  toggleLabel: { fontSize: 14, color: theme.text },
  compRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 6,
  },
  compInput: { flex: 1, paddingVertical: 8 },
  compLabel: {
    flex: 1,
    fontSize: 13,
    color: theme.text,
    textTransform: "capitalize",
  },
  typeChip: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: theme.radiusSm,
    backgroundColor: theme.primaryGlow,
  },
  typeChipDed: { backgroundColor: "rgba(239,68,68,0.15)" },
  typeChipText: { fontSize: 12, fontWeight: "600", color: theme.text },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 10,
  },
  addBtnText: { fontSize: 13, fontWeight: "600", color: theme.primary },
  saveBtn: {
    backgroundColor: theme.primary,
    borderRadius: theme.radiusSm,
    paddingVertical: 13,
    alignItems: "center",
    marginTop: 10,
  },
  saveBtnText: { color: "#fff", fontSize: 15, fontWeight: "600" },
  modalOverlay: { flex: 1, justifyContent: "flex-end" },
  modalScrim: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  sheet: {
    backgroundColor: theme.bgElevated,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    gap: 6,
  },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
    gap: 12,
  },
  sheetTitle: { flex: 1, fontSize: 18, fontWeight: "700", color: theme.text },
});
