import { StyleSheet } from "react-native";
import type { Theme } from "../../src/theme";

export const makeStyles = (theme: Theme) =>
  StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.bg },
  center: { alignItems: "center", justifyContent: "center" },
  container: { padding: 16, gap: 16, paddingBottom: 48 },
  section: {
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusLg,
    padding: 16,
    gap: 10,
  },
  sectionTitleRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  sectionTitle: { fontSize: 15, fontWeight: "700", color: theme.text },
  subHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  subHeader: { fontSize: 13, fontWeight: "600", color: theme.textSecondary },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: theme.radiusSm,
    backgroundColor: theme.primaryGlow,
  },
  addBtnText: { fontSize: 12, fontWeight: "600", color: theme.primary },
  fieldLabel: { fontSize: 12, color: theme.textSecondary, fontWeight: "500" },
  input: {
    backgroundColor: theme.inputBg,
    borderWidth: 1,
    borderColor: theme.inputBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: theme.text,
    fontSize: 15,
  },
  inputTall: { minHeight: 120, textAlignVertical: "top" },
  dayRow: { flexDirection: "row", gap: 6, flexWrap: "wrap" },
  dayChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: theme.radiusSm,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  dayChipActive: { backgroundColor: theme.primary, borderColor: theme.primary },
  dayChipText: { fontSize: 12, color: theme.textSecondary, fontWeight: "600" },
  dayChipTextActive: { color: "#fff" },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  toggleLabel: { fontSize: 14, color: theme.text, flex: 1, marginRight: 12 },
  latLngRow: { flexDirection: "row", gap: 12 },
  saveBtn: {
    backgroundColor: theme.primary,
    borderRadius: theme.radiusSm,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 4,
  },
  saveBtnText: { color: "#fff", fontSize: 15, fontWeight: "600" },
  swatchRow: { flexDirection: "row", gap: 12, flexWrap: "wrap" },
  swatch: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 3,
    borderColor: "transparent",
  },
  swatchActive: { borderColor: theme.text },
  hint: { fontSize: 12, color: theme.textMuted },
  mapPreview: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusSm,
    padding: 12,
    gap: 8,
    marginTop: 4,
  },
  mapPreviewRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  mapPreviewCoord: { fontSize: 14, fontWeight: "600", color: theme.text },
  mapPreviewMeta: { fontSize: 12, color: theme.textMuted },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.border,
  },
  colorDot: { width: 12, height: 12, borderRadius: 6 },
  itemName: { fontSize: 14, fontWeight: "600", color: theme.text },
  itemMeta: { fontSize: 11, color: theme.textMuted, marginTop: 1 },
  codeText: {
    fontSize: 14,
    fontWeight: "700",
    color: theme.text,
    letterSpacing: 1,
  },
  iconBtn: { padding: 6 },
  logoRow: { flexDirection: "row", alignItems: "center", gap: 16 },
  logoPreview: {
    width: 72,
    height: 72,
    borderRadius: theme.radiusSm,
    backgroundColor: theme.surface,
  },
  logoPlaceholder: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  smallBtn: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  smallBtnText: { color: theme.text, fontSize: 13, fontWeight: "600" },
  smallBtnDanger: {
    borderWidth: 1,
    borderColor: theme.danger,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  smallBtnDangerText: { color: theme.danger, fontSize: 13, fontWeight: "600" },
  modalOverlay: { flex: 1, justifyContent: "flex-end" },
  modalScrim: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  sheet: {
    backgroundColor: theme.bgElevated,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    gap: 10,
  },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
    gap: 12,
  },
  sheetTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "700",
    color: theme.text,
  },
  // Attendance: location + map
  locBtnRow: { flexDirection: "row", gap: 12 },
  mapHintRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  mapWebWrap: {
    height: 240,
    borderRadius: theme.radiusSm,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    overflow: "hidden",
    backgroundColor: theme.surface,
  },
  mapWeb: { flex: 1, backgroundColor: theme.surface },
  // Office Wi-Fi allow-list
  wifiSection: {
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: theme.border,
    gap: 8,
  },
  wifiHeaderRow: { flexDirection: "row", alignItems: "center" },
  wifiTitle: { fontSize: 14, fontWeight: "700", color: theme.text },
  wifiManualForm: { gap: 8, marginTop: 4 },
  wifiManualActions: { flexDirection: "row", gap: 12 },
  wifiActionRow: { flexDirection: "row", gap: 12, marginTop: 4 },
  wifiErr: { fontSize: 12, color: theme.danger },
  // System role cards
  systemRoleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    marginTop: 8,
    borderRadius: theme.radiusSm,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  systemRoleHeader: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  systemBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: theme.radiusFull,
    backgroundColor: theme.surfaceHover,
  },
  systemBadgeText: { fontSize: 10, color: theme.textMuted, fontWeight: "600" },
  levelBadge: {
    fontSize: 10,
    color: theme.textSecondary,
    fontWeight: "600",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: theme.radiusFull,
    backgroundColor: theme.surfaceHover,
  },
  // Branding: hex input + live preview
  hexRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  hexSwatch: {
    width: 40,
    height: 40,
    borderRadius: theme.radiusSm,
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  previewLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: theme.textSecondary,
    marginTop: 4,
  },
  previewCard: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusSm,
    padding: 16,
    gap: 8,
  },
  previewLogo: { height: 40, width: 120, resizeMode: "contain" },
  previewHeading: { fontSize: 16, fontWeight: "700", color: theme.text },
  previewText: { fontSize: 13, color: theme.textSecondary },
  previewBtn: {
    alignSelf: "flex-start",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: theme.radiusSm,
    marginTop: 4,
  },
  previewBtnText: { color: "#fff", fontSize: 13, fontWeight: "600" },
  // Branding save banner — theme-aware inline status (replaces blocking Alerts)
  brandingBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: theme.radiusSm,
    borderWidth: 1,
    marginTop: 4,
  },
  brandingBannerSuccess: {
    backgroundColor: theme.primaryGlow,
    borderColor: theme.primary,
  },
  brandingBannerError: {
    backgroundColor: theme.surface,
    borderColor: theme.danger,
  },
  brandingBannerText: { flex: 1, fontSize: 13, fontWeight: "600" },
});

