-- =============================================================================
-- 0002_migration_catchup.sql
--
-- GENERATED by scripts/a2-generate-baseline.mjs — DO NOT EDIT BY HAND.
-- Regenerate with:  node scripts/a2-generate-baseline.mjs
--
-- WHAT THIS IS
--   The flattened equivalent of the 30 entries that used to live in
--   MIGRATIONS[] in server/utils/migrationRunner.ts.
--
--   It runs AFTER initTenantSchema() (server/db.ts), which remains the base
--   schema layer. Together they produce the complete tenant schema.
--
-- WHY IT EXISTS
--   scripts/analyze-migration-coverage.mjs proved that 26 DDL objects were
--   created ONLY by MIGRATIONS[] and never by initTenantSchema() — including
--   device_tokens (push notifications), webauthn_credentials +
--   device_credentials (biometric login), the users.mfa_* columns (2FA),
--   sprint_burndown_snapshots, sprint_retro_votes, tasks.cycle_started_at /
--   lead_started_at, and 3 performance indexes.
--
--   Before this file, a newly-created tenant got an INCOMPLETE schema from
--   initTenantSchema() and only received those objects later, whenever the
--   migration sweep happened to run. This closes that gap permanently.
--
-- IDEMPOTENCY
--   Every statement is IF NOT EXISTS / IF EXISTS guarded, so re-running against
--   an already-migrated database is a safe no-op.
--
-- Statements: 170
-- =============================================================================

-- ------------------------------------------------------------------------
-- 2026_05_v1_index_users_org_active
-- ------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_users_org_active
                ON users (org_id) WHERE is_active = TRUE;

-- ------------------------------------------------------------------------
-- 2026_05_v1_index_audit_logs_actor_created
-- ------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_created
                ON audit_logs (actor_id, created_at DESC);

-- ------------------------------------------------------------------------
-- 2026_05_v1_index_audit_logs_entity_created
-- ------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_created
                ON audit_logs (entity_type, created_at DESC);

-- ------------------------------------------------------------------------
-- 2026_05_v1_agile_customisation_tables
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS org_agile_settings (
                    org_id                      INTEGER PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
                    estimation_type             TEXT NOT NULL DEFAULT 'fibonacci'
                        CHECK(estimation_type IN ('fibonacci','linear','tshirt','hours','none','custom')),
                    estimation_values           JSONB NOT NULL DEFAULT '[0.5,1,2,3,5,8,13,21,34]'::jsonb,
                    estimation_unit_label       TEXT NOT NULL DEFAULT 'SP',
                    priority_scheme             JSONB NOT NULL DEFAULT '[{"key":"low","label":"Low","color":"#10b981"},{"key":"medium","label":"Medium","color":"#f59e0b"},{"key":"high","label":"High","color":"#ef4444"}]'::jsonb,
                    enable_story_points         BOOLEAN NOT NULL DEFAULT TRUE,
                    enable_epics                BOOLEAN NOT NULL DEFAULT TRUE,
                    enable_dependencies         BOOLEAN NOT NULL DEFAULT TRUE,
                    enable_acceptance_criteria  BOOLEAN NOT NULL DEFAULT TRUE,
                    enable_wip_limits           BOOLEAN NOT NULL DEFAULT FALSE,
                    enable_blockers             BOOLEAN NOT NULL DEFAULT TRUE,
                    enable_retrospectives       BOOLEAN NOT NULL DEFAULT TRUE,
                    require_estimate_for_sprint BOOLEAN NOT NULL DEFAULT FALSE,
                    default_dod                 TEXT,
                    updated_at                  TIMESTAMPTZ DEFAULT NOW()
                );
CREATE TABLE IF NOT EXISTS work_item_types (
                    id          SERIAL PRIMARY KEY,
                    org_id      INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    key         TEXT NOT NULL,
                    name        TEXT NOT NULL,
                    icon        TEXT,
                    color       TEXT NOT NULL DEFAULT '#6366f1',
                    description TEXT,
                    is_default  BOOLEAN NOT NULL DEFAULT FALSE,
                    is_epic     BOOLEAN NOT NULL DEFAULT FALSE,
                    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
                    sort_order  INTEGER NOT NULL DEFAULT 0,
                    created_at  TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE(org_id, key)
                );
CREATE INDEX IF NOT EXISTS idx_work_item_types_org ON work_item_types(org_id, is_active, sort_order);
CREATE TABLE IF NOT EXISTS workflow_states (
                    id            SERIAL PRIMARY KEY,
                    org_id        INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    key           TEXT NOT NULL,
                    name          TEXT NOT NULL,
                    category      TEXT NOT NULL CHECK(category IN ('open','in_progress','in_review','done')),
                    color         TEXT NOT NULL DEFAULT '#6b7280',
                    icon          TEXT,
                    wip_limit     INTEGER,
                    is_initial    BOOLEAN NOT NULL DEFAULT FALSE,
                    is_terminal   BOOLEAN NOT NULL DEFAULT FALSE,
                    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
                    sort_order    INTEGER NOT NULL DEFAULT 0,
                    created_at    TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE(org_id, key)
                );
CREATE INDEX IF NOT EXISTS idx_workflow_states_org ON workflow_states(org_id, is_active, sort_order);
CREATE TABLE IF NOT EXISTS workflow_state_type_map (
                    state_id INTEGER NOT NULL REFERENCES workflow_states(id) ON DELETE CASCADE,
                    type_id  INTEGER NOT NULL REFERENCES work_item_types(id) ON DELETE CASCADE,
                    PRIMARY KEY (state_id, type_id)
                );
CREATE TABLE IF NOT EXISTS workflow_transitions (
                    id            SERIAL PRIMARY KEY,
                    org_id        INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    from_state_id INTEGER NOT NULL REFERENCES workflow_states(id) ON DELETE CASCADE,
                    to_state_id   INTEGER NOT NULL REFERENCES workflow_states(id) ON DELETE CASCADE,
                    required_role TEXT,
                    UNIQUE(from_state_id, to_state_id)
                );
CREATE INDEX IF NOT EXISTS idx_workflow_transitions_org ON workflow_transitions(org_id);
CREATE TABLE IF NOT EXISTS team_agile_settings (
                    team_id            INTEGER PRIMARY KEY REFERENCES teams(id) ON DELETE CASCADE,
                    estimation_type    TEXT,
                    estimation_values  JSONB,
                    capacity_points    NUMERIC(7,1),
                    updated_at         TIMESTAMPTZ DEFAULT NOW()
                );
CREATE TABLE IF NOT EXISTS agile_editor_grants (
                    id          SERIAL PRIMARY KEY,
                    org_id      INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    granted_by  INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    granted_at  TIMESTAMPTZ DEFAULT NOW(),
                    revoked_at  TIMESTAMPTZ,
                    UNIQUE(org_id, user_id)
                );
CREATE INDEX IF NOT EXISTS idx_agile_grants_active ON agile_editor_grants(org_id, user_id) WHERE revoked_at IS NULL;
CREATE TABLE IF NOT EXISTS agile_editor_requests (
                    id            SERIAL PRIMARY KEY,
                    org_id        INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    reason        TEXT,
                    status        TEXT NOT NULL DEFAULT 'pending'
                        CHECK(status IN ('pending','approved','rejected','cancelled')),
                    reviewed_by   INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    reviewed_at   TIMESTAMPTZ,
                    reject_reason TEXT,
                    created_at    TIMESTAMPTZ DEFAULT NOW()
                );
CREATE INDEX IF NOT EXISTS idx_agile_requests_status ON agile_editor_requests(org_id, status, created_at);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS story_points NUMERIC(6,2);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS work_item_type_id INTEGER REFERENCES work_item_types(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS workflow_state_id INTEGER REFERENCES workflow_states(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS parent_task_id INTEGER REFERENCES tasks(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS rank_value NUMERIC(20,10);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS acceptance_criteria JSONB;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS is_blocked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS blocked_reason TEXT;
CREATE INDEX IF NOT EXISTS idx_tasks_workflow_state ON tasks(workflow_state_id) WHERE workflow_state_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_parent ON tasks(parent_task_id) WHERE parent_task_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS task_dependencies (
                    id            SERIAL PRIMARY KEY,
                    task_id       INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
                    depends_on_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
                    type          TEXT NOT NULL DEFAULT 'blocks'
                        CHECK(type IN ('blocks','relates','duplicates','clones')),
                    created_by    INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    created_at    TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE(task_id, depends_on_id, type)
                );
CREATE INDEX IF NOT EXISTS idx_task_deps_task ON task_dependencies(task_id);
CREATE INDEX IF NOT EXISTS idx_task_deps_depends_on ON task_dependencies(depends_on_id);
CREATE TABLE IF NOT EXISTS sprint_retrospectives (
                    id          SERIAL PRIMARY KEY,
                    sprint_id   INTEGER NOT NULL REFERENCES sprints(id) ON DELETE CASCADE,
                    category    TEXT NOT NULL CHECK(category IN ('went_well','went_wrong','action_item','kudos')),
                    content     TEXT NOT NULL,
                    author_id   INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    votes       INTEGER NOT NULL DEFAULT 0,
                    created_at  TIMESTAMPTZ DEFAULT NOW()
                );
DO $do$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                         WHERE table_name  = 'sprint_retrospectives'
                           AND column_name = 'category'
                    ) THEN
                        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_retro_sprint ON sprint_retrospectives(sprint_id, category)';
                    END IF;
                END $do$;
CREATE TABLE IF NOT EXISTS sprint_retro_votes (
                    retro_id INTEGER NOT NULL REFERENCES sprint_retrospectives(id) ON DELETE CASCADE,
                    user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    PRIMARY KEY (retro_id, user_id)
                );
DO $do$
                DECLARE r record;
                BEGIN
                    FOR r IN
                        SELECT con.conname
                        FROM   pg_constraint con
                        JOIN   pg_class       rel ON rel.oid = con.conrelid
                        JOIN   pg_attribute   att ON att.attrelid = rel.oid
                                                 AND att.attnum   = ANY(con.conkey)
                        WHERE  rel.relname = 'tasks'
                          AND  con.contype = 'c'
                          AND  att.attname = 'status'
                    LOOP
                        EXECUTE 'ALTER TABLE tasks DROP CONSTRAINT ' || quote_ident(r.conname);
                    END LOOP;
                EXCEPTION WHEN others THEN NULL;
                END $do$;

-- ------------------------------------------------------------------------
-- 2026_05_v2_sprint_lifecycle
-- ------------------------------------------------------------------------
ALTER TABLE sprints ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;
ALTER TABLE sprints ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE sprints ADD COLUMN IF NOT EXISTS velocity_points NUMERIC(8,2);
CREATE TABLE IF NOT EXISTS sprint_burndown_snapshots (
                    id               SERIAL PRIMARY KEY,
                    sprint_id        INTEGER NOT NULL REFERENCES sprints(id) ON DELETE CASCADE,
                    snapshot_date    DATE NOT NULL,
                    total_points     NUMERIC(10,2) NOT NULL DEFAULT 0,
                    done_points      NUMERIC(10,2) NOT NULL DEFAULT 0,
                    remaining_points NUMERIC(10,2) NOT NULL DEFAULT 0,
                    blocked_points   NUMERIC(10,2) NOT NULL DEFAULT 0,
                    open_tasks       INTEGER NOT NULL DEFAULT 0,
                    created_at       TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE (sprint_id, snapshot_date)
                );
CREATE INDEX IF NOT EXISTS idx_burndown_sprint_date ON sprint_burndown_snapshots(sprint_id, snapshot_date);

-- ------------------------------------------------------------------------
-- 2026_05_v3_cycle_time_and_retros
-- ------------------------------------------------------------------------
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS cycle_started_at TIMESTAMPTZ;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS lead_started_at  TIMESTAMPTZ;
UPDATE tasks SET lead_started_at = COALESCE(lead_started_at, created_at) WHERE lead_started_at IS NULL;
DROP TABLE IF EXISTS sprint_retro_votes;
DROP TABLE IF EXISTS sprint_retrospectives;
CREATE TABLE IF NOT EXISTS sprint_retrospectives (
                    id              SERIAL PRIMARY KEY,
                    sprint_id       INTEGER NOT NULL UNIQUE REFERENCES sprints(id) ON DELETE CASCADE,
                    went_well       TEXT,
                    to_improve      TEXT,
                    action_items    JSONB DEFAULT '[]'::jsonb,
                    team_mood       SMALLINT CHECK (team_mood IS NULL OR team_mood BETWEEN 1 AND 5),
                    summary         TEXT,
                    created_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    updated_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    created_at      TIMESTAMPTZ DEFAULT NOW(),
                    updated_at      TIMESTAMPTZ DEFAULT NOW()
                );
CREATE INDEX IF NOT EXISTS idx_retros_sprint ON sprint_retrospectives(sprint_id);

-- ------------------------------------------------------------------------
-- 2026_05_v4_retro_cleanup
-- ------------------------------------------------------------------------
DROP TABLE IF EXISTS sprint_retro_votes;
DROP INDEX IF EXISTS idx_retro_sprint;
ALTER TABLE sprint_retrospectives DROP COLUMN IF EXISTS category;
ALTER TABLE sprint_retrospectives DROP COLUMN IF EXISTS content;
ALTER TABLE sprint_retrospectives DROP COLUMN IF EXISTS votes;
ALTER TABLE sprint_retrospectives DROP COLUMN IF EXISTS author_id;
DO $do$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                         WHERE conrelid = 'sprint_retrospectives'::regclass
                           AND contype  = 'u'
                           AND conkey   = ARRAY[(
                               SELECT attnum FROM pg_attribute
                                WHERE attrelid = 'sprint_retrospectives'::regclass
                                  AND attname  = 'sprint_id'
                           )]::smallint[]
                    ) THEN
                        BEGIN
                            ALTER TABLE sprint_retrospectives
                                ADD CONSTRAINT sprint_retrospectives_sprint_id_key
                                UNIQUE (sprint_id);
                        EXCEPTION WHEN duplicate_object THEN NULL;
                        END;
                    END IF;
                END $do$;
CREATE INDEX IF NOT EXISTS idx_retros_sprint ON sprint_retrospectives(sprint_id);

-- ------------------------------------------------------------------------
-- 2026_06_v1_branding_and_email_templates
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS org_branding (
                    org_id        INTEGER PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
                    logo_url      TEXT,
                    accent_color  TEXT NOT NULL DEFAULT '#6366f1',
                    updated_by    INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    updated_at    TIMESTAMPTZ DEFAULT NOW()
                );
CREATE TABLE IF NOT EXISTS org_email_templates (
                    org_id        INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    template_key  TEXT    NOT NULL,
                    subject       TEXT    NOT NULL,
                    body_html     TEXT    NOT NULL,
                    enabled       BOOLEAN NOT NULL DEFAULT TRUE,
                    updated_by    INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    updated_at    TIMESTAMPTZ DEFAULT NOW(),
                    PRIMARY KEY (org_id, template_key)
                );
CREATE INDEX IF NOT EXISTS idx_org_email_templates_org ON org_email_templates(org_id);

-- ------------------------------------------------------------------------
-- 2026_06_v1_custom_fields
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS custom_field_definitions (
                    id              SERIAL PRIMARY KEY,
                    org_id          INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    key             TEXT    NOT NULL,
                    label           TEXT    NOT NULL,
                    field_type      TEXT    NOT NULL CHECK(field_type IN
                                        ('text','number','date','select','multiselect','checkbox','url')),
                    description     TEXT,
                    options         JSONB   NOT NULL DEFAULT '[]'::jsonb,
                    is_required     BOOLEAN NOT NULL DEFAULT FALSE,
                    show_on_card    BOOLEAN NOT NULL DEFAULT FALSE,
                    applies_to_types JSONB  NOT NULL DEFAULT '[]'::jsonb,
                    sort_order      INTEGER NOT NULL DEFAULT 0,
                    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
                    created_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    created_at      TIMESTAMPTZ DEFAULT NOW(),
                    updated_at      TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE(org_id, key)
                );
CREATE INDEX IF NOT EXISTS idx_cfd_org ON custom_field_definitions(org_id, is_active, sort_order);
CREATE TABLE IF NOT EXISTS task_custom_field_values (
                    task_id     INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
                    field_id    INTEGER NOT NULL REFERENCES custom_field_definitions(id) ON DELETE CASCADE,
                    value       JSONB,
                    updated_by  INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    updated_at  TIMESTAMPTZ DEFAULT NOW(),
                    PRIMARY KEY (task_id, field_id)
                );
CREATE INDEX IF NOT EXISTS idx_tcfv_field ON task_custom_field_values(field_id);

-- ------------------------------------------------------------------------
-- 2026_06_v3_compensation_payroll_tables
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS compensation_templates (
                    id              SERIAL PRIMARY KEY,
                    org_id          INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    name            TEXT NOT NULL,
                    description     TEXT,
                    components      JSONB NOT NULL DEFAULT '[]',
                    is_default      BOOLEAN NOT NULL DEFAULT FALSE,
                    created_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    created_at      TIMESTAMPTZ DEFAULT NOW(),
                    updated_at      TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE(org_id, name)
                );
CREATE INDEX IF NOT EXISTS idx_compensation_templates_org ON compensation_templates(org_id);
CREATE TABLE IF NOT EXISTS employee_compensation (
                    id                  SERIAL PRIMARY KEY,
                    user_id             INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    org_id              INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    template_id         INTEGER REFERENCES compensation_templates(id) ON DELETE SET NULL,
                    effective_from      TEXT NOT NULL,
                    effective_to        TEXT,
                    base_salary         NUMERIC(12,2) NOT NULL DEFAULT 0,
                    components          JSONB NOT NULL DEFAULT '{}',
                    currency            TEXT NOT NULL DEFAULT 'INR',
                    payment_frequency   TEXT NOT NULL DEFAULT 'monthly' CHECK(payment_frequency IN ('monthly','biweekly','weekly')),
                    bank_account        TEXT,
                    notes               TEXT,
                    created_by          INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    created_at          TIMESTAMPTZ DEFAULT NOW(),
                    updated_at          TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE(user_id, effective_from)
                );
CREATE INDEX IF NOT EXISTS idx_employee_compensation_user ON employee_compensation(user_id, effective_from DESC);
CREATE INDEX IF NOT EXISTS idx_employee_compensation_org ON employee_compensation(org_id);
CREATE TABLE IF NOT EXISTS salary_slips (
                    id                  SERIAL PRIMARY KEY,
                    org_id              INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    user_id             INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    pay_period_id       INTEGER NOT NULL REFERENCES pay_periods(id) ON DELETE CASCADE,
                    compensation_id     INTEGER REFERENCES employee_compensation(id) ON DELETE SET NULL,
                    slip_month          TEXT NOT NULL,
                    earnings            JSONB NOT NULL DEFAULT '{}',
                    deductions          JSONB NOT NULL DEFAULT '{}',
                    gross_earnings      NUMERIC(12,2) NOT NULL DEFAULT 0,
                    total_deductions    NUMERIC(12,2) NOT NULL DEFAULT 0,
                    net_pay             NUMERIC(12,2) NOT NULL DEFAULT 0,
                    days_worked         NUMERIC(5,2) DEFAULT 0,
                    days_absent         NUMERIC(5,2) DEFAULT 0,
                    leave_days          NUMERIC(5,2) DEFAULT 0,
                    overtime_hours      NUMERIC(6,2) DEFAULT 0,
                    status              TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','generated','published','revised')),
                    generated_by        INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    published_at        TIMESTAMPTZ,
                    created_at          TIMESTAMPTZ DEFAULT NOW(),
                    updated_at          TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE(org_id, user_id, pay_period_id)
                );
CREATE INDEX IF NOT EXISTS idx_salary_slips_user ON salary_slips(user_id, slip_month DESC);
CREATE INDEX IF NOT EXISTS idx_salary_slips_period ON salary_slips(pay_period_id);
CREATE INDEX IF NOT EXISTS idx_salary_slips_org_month ON salary_slips(org_id, slip_month);
CREATE TABLE IF NOT EXISTS payroll_disbursements (
                    id                          SERIAL PRIMARY KEY,
                    org_id                      INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    salary_slip_id              INTEGER NOT NULL REFERENCES salary_slips(id) ON DELETE CASCADE,
                    user_id                     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    amount                      NUMERIC(12,2) NOT NULL,
                    currency                    TEXT NOT NULL DEFAULT 'INR',
                    razorpay_payout_id          TEXT,
                    razorpay_fund_account_id    TEXT,
                    transfer_mode               TEXT NOT NULL DEFAULT 'NEFT',
                    status                      TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','processing','processed','reversed','failed')),
                    failure_reason              TEXT,
                    utr                         TEXT,
                    initiated_by                INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    initiated_at                TIMESTAMPTZ,
                    processed_at                TIMESTAMPTZ,
                    created_at                  TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE(salary_slip_id)
                );
CREATE INDEX IF NOT EXISTS idx_payroll_disbursements_org ON payroll_disbursements(org_id, status);
CREATE INDEX IF NOT EXISTS idx_payroll_disbursements_user ON payroll_disbursements(user_id);
CREATE TABLE IF NOT EXISTS org_payment_config (
                    id                      SERIAL PRIMARY KEY,
                    org_id                  INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    provider                TEXT NOT NULL DEFAULT 'razorpay',
                    api_key_id              TEXT,
                    api_key_secret          TEXT,
                    account_number          TEXT,
                    webhook_secret          TEXT,
                    default_transfer_mode   TEXT NOT NULL DEFAULT 'NEFT',
                    is_active               BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at              TIMESTAMPTZ DEFAULT NOW(),
                    updated_at              TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE(org_id)
                );
CREATE TABLE IF NOT EXISTS employee_bank_details (
                    id                          SERIAL PRIMARY KEY,
                    user_id                     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    org_id                      INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    account_holder_name         TEXT NOT NULL,
                    account_number              TEXT NOT NULL,
                    ifsc_code                   TEXT NOT NULL,
                    bank_name                   TEXT,
                    account_type                TEXT NOT NULL DEFAULT 'savings',
                    razorpay_contact_id         TEXT,
                    razorpay_fund_account_id    TEXT,
                    is_verified                 BOOLEAN NOT NULL DEFAULT FALSE,
                    verified_at                 TIMESTAMPTZ,
                    created_at                  TIMESTAMPTZ DEFAULT NOW(),
                    updated_at                  TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE(user_id, org_id)
                );
CREATE INDEX IF NOT EXISTS idx_employee_bank_details_org ON employee_bank_details(org_id);

-- ------------------------------------------------------------------------
-- 2026_06_v4_ctc_support
-- ------------------------------------------------------------------------
ALTER TABLE employee_compensation
                ADD COLUMN IF NOT EXISTS ctc_annual NUMERIC(12,2) NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS org_ctc_config (
                    org_id          INTEGER PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
                    basic_pct       NUMERIC(5,2) NOT NULL DEFAULT 40,
                    hra_pct         NUMERIC(5,2) NOT NULL DEFAULT 50,
                    conveyance_pct  NUMERIC(5,2) NOT NULL DEFAULT 5,
                    pf_pct          NUMERIC(5,2) NOT NULL DEFAULT 12,
                    pf_max          NUMERIC(10,2) NOT NULL DEFAULT 1800,
                    pt_fixed        NUMERIC(10,2) NOT NULL DEFAULT 200,
                    updated_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    updated_at      TIMESTAMPTZ DEFAULT NOW()
                );

-- ------------------------------------------------------------------------
-- 2026_06_v5_drop_legacy_user_status_columns
-- ------------------------------------------------------------------------
DO $do$
                DECLARE r record;
                BEGIN
                    FOR r IN
                        SELECT con.conname
                        FROM   pg_constraint con
                        JOIN   pg_class       rel ON rel.oid = con.conrelid
                        JOIN   pg_attribute   att ON att.attrelid = rel.oid
                                                 AND att.attnum   = ANY(con.conkey)
                        WHERE  rel.relname = 'users'
                          AND  con.contype = 'c'
                          AND  att.attname = 'user_status'
                    LOOP
                        EXECUTE 'ALTER TABLE users DROP CONSTRAINT ' || quote_ident(r.conname);
                    END LOOP;
                EXCEPTION WHEN others THEN NULL;
                END $do$;
ALTER TABLE users DROP COLUMN IF EXISTS user_status;
ALTER TABLE users DROP COLUMN IF EXISTS user_status_text;

-- ------------------------------------------------------------------------
-- 2026_06_v6_projects_and_git_integration
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
                    id              SERIAL PRIMARY KEY,
                    org_id          INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    key             TEXT    NOT NULL,
                    name            TEXT    NOT NULL,
                    description     TEXT,
                    color           TEXT    NOT NULL DEFAULT '#6366f1',
                    lead_user_id    INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    next_task_number INTEGER NOT NULL DEFAULT 1,
                    is_archived     BOOLEAN NOT NULL DEFAULT FALSE,
                    created_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    created_at      TIMESTAMPTZ DEFAULT NOW(),
                    updated_at      TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE (org_id, key)
                );
DO $do$ BEGIN
                    ALTER TABLE projects DROP CONSTRAINT IF EXISTS projects_key_format_check;
                    ALTER TABLE projects ADD CONSTRAINT projects_key_format_check
                        CHECK (key ~ '^[A-Z][A-Z0-9_]{1,9}$');
                EXCEPTION WHEN others THEN NULL;
                END $do$;
CREATE INDEX IF NOT EXISTS idx_projects_org ON projects(org_id, is_archived);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS task_number INTEGER;
CREATE UNIQUE INDEX IF NOT EXISTS uq_tasks_project_number ON tasks(project_id, task_number) WHERE project_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id) WHERE project_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS org_integrations (
                    id           SERIAL PRIMARY KEY,
                    org_id       INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
                    provider     TEXT    NOT NULL CHECK (provider IN ('github','gitlab','bitbucket')),
                    config       JSONB   NOT NULL DEFAULT '{}'::jsonb,
                    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
                    created_by   INTEGER REFERENCES users(id) ON DELETE SET NULL,
                    created_at   TIMESTAMPTZ DEFAULT NOW(),
                    updated_at   TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE (org_id, provider)
                );
CREATE INDEX IF NOT EXISTS idx_integrations_org ON org_integrations(org_id, is_active);
CREATE TABLE IF NOT EXISTS org_integration_secrets (
                    integration_id   INTEGER PRIMARY KEY REFERENCES org_integrations(id) ON DELETE CASCADE,
                    webhook_secret   TEXT,
                    access_token     TEXT,
                    refresh_token    TEXT,
                    token_expires_at TIMESTAMPTZ,
                    github_login     TEXT,
                    github_avatar    TEXT,
                    scopes           TEXT,
                    updated_at       TIMESTAMPTZ DEFAULT NOW()
                );
ALTER TABLE org_integration_secrets ADD COLUMN IF NOT EXISTS github_login TEXT;
ALTER TABLE org_integration_secrets ADD COLUMN IF NOT EXISTS github_avatar TEXT;
ALTER TABLE org_integration_secrets ADD COLUMN IF NOT EXISTS scopes TEXT;
CREATE TABLE IF NOT EXISTS task_git_refs (
                    id              SERIAL PRIMARY KEY,
                    task_id         INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
                    integration_id  INTEGER REFERENCES org_integrations(id) ON DELETE SET NULL,
                    ref_type        TEXT NOT NULL CHECK (ref_type IN ('branch','pull_request','commit')),
                    status          TEXT NOT NULL DEFAULT 'open'
                                         CHECK (status IN ('open','merged','closed','draft','committed')),
                    external_id     TEXT,
                    title           TEXT,
                    url             TEXT,
                    repository      TEXT,
                    ref_name        TEXT,
                    author_login    TEXT,
                    commit_sha      TEXT,
                    payload         JSONB,
                    event_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    created_at      TIMESTAMPTZ DEFAULT NOW(),
                    updated_at      TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE (task_id, ref_type, external_id, repository)
                );
CREATE INDEX IF NOT EXISTS idx_task_git_refs_task ON task_git_refs(task_id, event_at DESC);
CREATE INDEX IF NOT EXISTS idx_task_git_refs_status ON task_git_refs(status) WHERE status != 'merged';
CREATE TABLE IF NOT EXISTS github_repo_connections (
                    id              SERIAL PRIMARY KEY,
                    integration_id  INTEGER NOT NULL REFERENCES org_integrations(id) ON DELETE CASCADE,
                    full_name       TEXT    NOT NULL,
                    html_url        TEXT,
                    default_branch  TEXT,
                    hook_id         BIGINT,
                    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at      TIMESTAMPTZ DEFAULT NOW(),
                    updated_at      TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE (integration_id, full_name)
                );
CREATE INDEX IF NOT EXISTS idx_gh_repo_conn_integration ON github_repo_connections(integration_id, is_active);

-- ------------------------------------------------------------------------
-- 2026_05_attendance_face_location
-- ------------------------------------------------------------------------
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS attendance_verification_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS office_latitude DOUBLE PRECISION;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS office_longitude DOUBLE PRECISION;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS office_radius_m INTEGER;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS office_address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS face_descriptor JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS face_enrolled_at TIMESTAMPTZ;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS clock_in_lat DOUBLE PRECISION;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS clock_in_lng DOUBLE PRECISION;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS clock_in_accuracy_m REAL;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS clock_in_distance_m INTEGER;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS face_verified BOOLEAN;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS face_match_score REAL;
DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'time_entries' AND column_name = 'clock_in_latitude'
                    ) THEN
                        UPDATE time_entries SET clock_in_lat = clock_in_latitude
                            WHERE clock_in_lat IS NULL AND clock_in_latitude IS NOT NULL;
                        ALTER TABLE time_entries DROP COLUMN clock_in_latitude;
                    END IF;
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'time_entries' AND column_name = 'clock_in_longitude'
                    ) THEN
                        UPDATE time_entries SET clock_in_lng = clock_in_longitude
                            WHERE clock_in_lng IS NULL AND clock_in_longitude IS NOT NULL;
                        ALTER TABLE time_entries DROP COLUMN clock_in_longitude;
                    END IF;
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'time_entries' AND column_name = 'clock_in_accuracy'
                    ) THEN
                        UPDATE time_entries SET clock_in_accuracy_m = clock_in_accuracy
                            WHERE clock_in_accuracy_m IS NULL AND clock_in_accuracy IS NOT NULL;
                        ALTER TABLE time_entries DROP COLUMN clock_in_accuracy;
                    END IF;
                END $$;

-- ------------------------------------------------------------------------
-- 2026_05_attendance_face_location_column_rename_fix
-- ------------------------------------------------------------------------
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS clock_in_lat DOUBLE PRECISION;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS clock_in_lng DOUBLE PRECISION;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS clock_in_accuracy_m REAL;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS clock_in_distance_m INTEGER;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS face_verified BOOLEAN;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS face_match_score REAL;
DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'time_entries' AND column_name = 'clock_in_latitude'
                    ) THEN
                        UPDATE time_entries SET clock_in_lat = clock_in_latitude
                            WHERE clock_in_lat IS NULL AND clock_in_latitude IS NOT NULL;
                        ALTER TABLE time_entries DROP COLUMN clock_in_latitude;
                    END IF;
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'time_entries' AND column_name = 'clock_in_longitude'
                    ) THEN
                        UPDATE time_entries SET clock_in_lng = clock_in_longitude
                            WHERE clock_in_lng IS NULL AND clock_in_longitude IS NOT NULL;
                        ALTER TABLE time_entries DROP COLUMN clock_in_longitude;
                    END IF;
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'time_entries' AND column_name = 'clock_in_accuracy'
                    ) THEN
                        UPDATE time_entries SET clock_in_accuracy_m = clock_in_accuracy
                            WHERE clock_in_accuracy_m IS NULL AND clock_in_accuracy IS NOT NULL;
                        ALTER TABLE time_entries DROP COLUMN clock_in_accuracy;
                    END IF;
                END $$;

-- ------------------------------------------------------------------------
-- 2026_06_v7_office_wifi_verification
-- ------------------------------------------------------------------------
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS office_wifi_bssids JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS office_wifi_verification_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS verified_via TEXT;
ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS clock_in_wifi_bssid TEXT;

-- ------------------------------------------------------------------------
-- 2026_06_v8_messages_client_msg_id
-- ------------------------------------------------------------------------
ALTER TABLE messages ADD COLUMN IF NOT EXISTS client_msg_id TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_client_msg_id
                ON messages (conversation_id, sender_id, client_msg_id)
                WHERE client_msg_id IS NOT NULL;

-- ------------------------------------------------------------------------
-- 2026_06_v9_users_hidden_from_directory
-- ------------------------------------------------------------------------
ALTER TABLE users ADD COLUMN IF NOT EXISTS hidden_from_directory BOOLEAN NOT NULL DEFAULT FALSE;
CREATE INDEX IF NOT EXISTS idx_users_directory_visible ON users (org_id) WHERE hidden_from_directory = FALSE;

-- ------------------------------------------------------------------------
-- 2026_06_v10_user_mfa
-- ------------------------------------------------------------------------
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_secret TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_enrolled_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_pending_secret TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_recovery_codes JSONB;

-- ------------------------------------------------------------------------
-- 2026_06_v11_task_comment_attachments
-- ------------------------------------------------------------------------
ALTER TABLE task_comments ALTER COLUMN content DROP NOT NULL;
ALTER TABLE task_comments ADD COLUMN IF NOT EXISTS file_url   TEXT;
ALTER TABLE task_comments ADD COLUMN IF NOT EXISTS file_name  VARCHAR(255);
ALTER TABLE task_comments ADD COLUMN IF NOT EXISTS file_type  VARCHAR(100);
ALTER TABLE task_comments ADD COLUMN IF NOT EXISTS file_size  INTEGER;

-- ------------------------------------------------------------------------
-- 2026_06_v12_mfa_reset_tokens
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mfa_reset_tokens (
                    id         SERIAL PRIMARY KEY,
                    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    token      TEXT NOT NULL,
                    expires_at TIMESTAMPTZ NOT NULL,
                    used       BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMPTZ DEFAULT NOW()
                );
CREATE INDEX IF NOT EXISTS idx_mfa_reset_tokens_token ON mfa_reset_tokens(token);
CREATE INDEX IF NOT EXISTS idx_mfa_reset_tokens_user ON mfa_reset_tokens(user_id);

-- ------------------------------------------------------------------------
-- 2026_06_v13_push_notification_device_tokens
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS device_tokens (
                    id              SERIAL PRIMARY KEY,
                    user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    tenant_id       INTEGER REFERENCES organizations(id) ON DELETE CASCADE,
                    device_token    TEXT NOT NULL,
                    platform        TEXT NOT NULL CHECK(platform IN ('ios','android','web')),
                    last_seen_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    created_at      TIMESTAMPTZ DEFAULT NOW(),
                    UNIQUE(user_id, device_token)
                );
CREATE INDEX IF NOT EXISTS idx_device_tokens_user ON device_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_device_tokens_org ON device_tokens(tenant_id) WHERE tenant_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_device_tokens_last_seen ON device_tokens(last_seen_at);

-- ------------------------------------------------------------------------
-- 2026_06_v14_biometric_device_credentials
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS device_credentials (
                    id            TEXT PRIMARY KEY,
                    user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    secret_hash   TEXT NOT NULL,
                    device_label  TEXT,
                    platform      TEXT NOT NULL CHECK(platform IN ('ios','android','desktop','web')),
                    last_used_at  TIMESTAMPTZ,
                    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    revoked_at    TIMESTAMPTZ
                );
CREATE INDEX IF NOT EXISTS idx_device_credentials_user ON device_credentials(user_id) WHERE revoked_at IS NULL;

-- ------------------------------------------------------------------------
-- 2026_06_v15_webauthn_credentials
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS webauthn_credentials (
                    id             SERIAL PRIMARY KEY,
                    user_id        INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    credential_id  TEXT NOT NULL UNIQUE,
                    public_key     TEXT NOT NULL,
                    counter        BIGINT NOT NULL DEFAULT 0,
                    transports     TEXT,
                    device_label   TEXT,
                    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    last_used_at   TIMESTAMPTZ,
                    revoked_at     TIMESTAMPTZ
                );
CREATE INDEX IF NOT EXISTS idx_webauthn_credentials_user ON webauthn_credentials(user_id) WHERE revoked_at IS NULL;

-- ------------------------------------------------------------------------
-- 2026_06_v16_biometric_login_enabled_flag
-- ------------------------------------------------------------------------
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS biometric_login_enabled BOOLEAN NOT NULL DEFAULT TRUE;

-- ------------------------------------------------------------------------
-- 2026_06_v17_chat_media_jobs_foundation
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_media_jobs (
                    id                SERIAL PRIMARY KEY,
                    message_id        INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE UNIQUE,
                    conversation_id   INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
                    sender_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    status            TEXT NOT NULL DEFAULT 'queued'
                                        CHECK (status IN ('queued','processing','completed','failed','cancelled')),
                    progress          INTEGER NOT NULL DEFAULT 0,
                    attempts          INTEGER NOT NULL DEFAULT 0,
                    failure_reason    TEXT,
                    cancel_requested  BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at        TIMESTAMPTZ DEFAULT NOW(),
                    updated_at        TIMESTAMPTZ DEFAULT NOW()
                );
CREATE INDEX IF NOT EXISTS idx_chat_media_jobs_conv ON chat_media_jobs(conversation_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_media_jobs_sender ON chat_media_jobs(sender_id, created_at DESC);

-- ------------------------------------------------------------------------
-- 2026_06_v18_chat_media_pipeline_stages
-- ------------------------------------------------------------------------
ALTER TABLE chat_media_jobs ADD COLUMN IF NOT EXISTS stage TEXT NOT NULL DEFAULT 'queued';
ALTER TABLE chat_media_jobs ADD COLUMN IF NOT EXISTS checksum_sha256 TEXT;
ALTER TABLE chat_media_jobs ADD COLUMN IF NOT EXISTS resumable_token TEXT;
ALTER TABLE chat_media_jobs ADD COLUMN IF NOT EXISTS pipeline_meta JSONB NOT NULL DEFAULT '{}'::jsonb;

-- ------------------------------------------------------------------------
-- 2026_07_v19_notification_metric_events
-- ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notification_metric_events (
                    id                SERIAL PRIMARY KEY,
                    client_event_id   TEXT NOT NULL UNIQUE,
                    user_id           INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    dedupe_key        TEXT,
                    conversation_id   TEXT,
                    message_id        TEXT,
                    notification_type TEXT,
                    level             TEXT NOT NULL DEFAULT 'INFO',
                    event             TEXT NOT NULL,
                    state             TEXT,
                    source            TEXT,
                    duration_ms       INTEGER,
                    error_hash        TEXT,
                    metadata          JSONB NOT NULL DEFAULT '{}'::jsonb,
                    client_timestamp  TIMESTAMPTZ NOT NULL,
                    received_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );
CREATE INDEX IF NOT EXISTS idx_notification_metric_events_timestamp
                ON notification_metric_events(client_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_notification_metric_events_dedupe
                ON notification_metric_events(dedupe_key)
                WHERE dedupe_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_notification_metric_events_state
                ON notification_metric_events(state, client_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_notification_metric_events_user
                ON notification_metric_events(user_id, client_timestamp DESC);

-- ------------------------------------------------------------------------
-- 2026_06_v4_status_service_v2_schema
--   Inlined from server/services/status/migration.ts
-- ------------------------------------------------------------------------
ALTER TABLE users
            ADD COLUMN IF NOT EXISTS manual_status TEXT,
            ADD COLUMN IF NOT EXISTS presence_preference TEXT NOT NULL DEFAULT 'auto',
            ADD COLUMN IF NOT EXISTS status_message TEXT,
            ADD COLUMN IF NOT EXISTS status_message_expires_at TIMESTAMPTZ,
            ADD COLUMN IF NOT EXISTS last_activity_at TIMESTAMPTZ DEFAULT NOW();
DO $do$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'users_manual_status_check'
            ) THEN
                ALTER TABLE users
                    ADD CONSTRAINT users_manual_status_check
                    CHECK (manual_status IS NULL OR manual_status IN ('available','busy','dnd','brb'));
            END IF;
        END $do$;
DO $do$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'users_presence_pref_check'
            ) THEN
                ALTER TABLE users
                    ADD CONSTRAINT users_presence_pref_check
                    CHECK (presence_preference IN ('auto','invisible'));
            END IF;
        END $do$;
CREATE TABLE IF NOT EXISTS user_presence_sessions (
            id              BIGSERIAL PRIMARY KEY,
            user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            session_key     TEXT NOT NULL UNIQUE,
            device_label    TEXT,
            connected_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            last_seen_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            disconnected_at TIMESTAMPTZ,
            activity        TEXT,
            activity_ref_id INTEGER
        );
DO $do$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'user_presence_sessions_activity_check'
            ) THEN
                ALTER TABLE user_presence_sessions
                    ADD CONSTRAINT user_presence_sessions_activity_check
                    CHECK (activity IS NULL OR activity IN ('in_call','in_meeting'));
            END IF;
        END $do$;
CREATE INDEX IF NOT EXISTS idx_user_presence_sessions_user_open
            ON user_presence_sessions(user_id) WHERE disconnected_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_user_presence_sessions_user_seen
            ON user_presence_sessions(user_id, last_seen_at DESC);
CREATE TABLE IF NOT EXISTS user_status_events (
            id           BIGSERIAL PRIMARY KEY,
            user_id      INTEGER NOT NULL,
            source       TEXT NOT NULL,
            from_state   TEXT,
            to_state     TEXT,
            session_key  TEXT,
            metadata     JSONB,
            created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );
CREATE INDEX IF NOT EXISTS idx_user_status_events_user_time
            ON user_status_events(user_id, created_at DESC);

