import { StyleSheet } from "react-native";
import type { Theme } from "../../src/theme";

export const makeStyles = (theme: Theme) =>
  StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.bg },
  center: { alignItems: "center", justifyContent: "center" },
  container: { padding: 16, gap: 10, paddingBottom: 24 },
  headerActions: { flexDirection: "row", gap: 18, alignItems: "center" },
  taskTitle: { fontSize: 20, fontWeight: "700", color: theme.text, lineHeight: 26 },
  metaRow: { flexDirection: "row", alignItems: "center", gap: 10, flexWrap: "wrap" },
  badge: { borderRadius: theme.radiusSm, paddingHorizontal: 10, paddingVertical: 4 },
  badgeText: { fontSize: 12, fontWeight: "600" },
  priorityChip: { flexDirection: "row", alignItems: "center", gap: 6 },
  dot: { width: 9, height: 9, borderRadius: 4.5 },
  priorityText: { fontSize: 13, color: theme.textSecondary },
  pointBadge: {
    backgroundColor: theme.primaryGlow,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  pointBadgeText: { fontSize: 12, fontWeight: "700", color: theme.primaryLight },
  blockerBadge: {
    backgroundColor: "rgba(224, 62, 62, 0.15)",
    borderRadius: theme.radiusSm,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  blockerText: { fontSize: 12, fontWeight: "700", color: theme.danger },
  labelRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  labelPill: {
    borderRadius: theme.radiusSm,
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  labelPillText: { fontSize: 12, fontWeight: "600" },
  detailGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 4,
  },
  detailItem: {
    minWidth: "44%",
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 2,
  },
  detailLabel: {
    fontSize: 10,
    color: theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    fontWeight: "600",
  },
  detailValue: { fontSize: 14, color: theme.text, fontWeight: "600" },
  dueText: { fontSize: 14, color: theme.text },
  scheduleRow: { flexDirection: "row", gap: 8 },
  scheduleBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusSm,
    paddingVertical: 12,
  },
  scheduleBtnText: { fontSize: 13, color: theme.text, fontWeight: "600" },
  detailTabs: {
    flexDirection: "row",
    backgroundColor: theme.surface,
    borderRadius: theme.radiusSm,
    padding: 3,
    gap: 3,
    marginTop: 16,
  },
  detailTab: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 5,
    alignItems: "center",
  },
  detailTabActive: { backgroundColor: theme.primary },
  detailTabText: { fontSize: 13, color: theme.textSecondary, fontWeight: "600" },
  detailTabTextActive: { color: "#fff" },
  historyRow: { flexDirection: "row", gap: 10, marginTop: 6, alignItems: "flex-start" },
  historyDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.primary,
    marginTop: 5,
  },
  historyText: { fontSize: 13, color: theme.textSecondary, lineHeight: 18 },
  historyName: { color: theme.text, fontWeight: "600" },
  description: { fontSize: 15, color: theme.text, lineHeight: 22, marginTop: 4 },
  noDesc: { fontSize: 14, color: theme.textMuted, fontStyle: "italic" },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: theme.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 16,
  },
  statusGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  statusBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    backgroundColor: theme.glass,
    borderRadius: theme.radiusFull,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  statusBtnText: { fontSize: 13, color: theme.textSecondary, fontWeight: "500" },
  label: {
    fontSize: 11,
    fontWeight: "600",
    color: theme.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 8,
  },
  input: {
    backgroundColor: theme.inputBg,
    borderWidth: 1,
    borderColor: theme.inputBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: theme.text,
    fontSize: 15,
  },
  textarea: { minHeight: 90, textAlignVertical: "top" },
  segment: {
    flexDirection: "row",
    backgroundColor: theme.surface,
    borderRadius: theme.radiusSm,
    padding: 3,
    gap: 3,
  },
  segmentBtn: { flex: 1, paddingVertical: 9, borderRadius: 5, alignItems: "center" },
  segmentText: { fontSize: 13, color: theme.textSecondary, fontWeight: "600" },
  segmentTextActive: { color: "#fff" },
  saveBtn: {
    backgroundColor: theme.primary,
    borderRadius: theme.radiusSm,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 16,
  },
  saveText: { color: "#fff", fontSize: 15, fontWeight: "600" },
  disabled: { opacity: 0.5 },
  comment: { flexDirection: "row", gap: 10, marginTop: 4 },
  commentAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  commentAvatarText: { color: "#fff", fontSize: 13, fontWeight: "700" },
  commentBody: {
    flex: 1,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    padding: 12,
    gap: 4,
  },
  commentTop: { flexDirection: "row", justifyContent: "space-between" },
  commentName: { fontSize: 13, fontWeight: "600", color: theme.text },
  commentTime: { fontSize: 11, color: theme.textMuted },
  commentText: { fontSize: 14, color: theme.textSecondary, lineHeight: 19 },
  attachImageWrap: { marginTop: 4 },
  attachImage: {
    width: 180,
    height: 140,
    borderRadius: theme.radiusSm,
    backgroundColor: theme.surface,
  },
  attachFileCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  attachFileName: { flex: 1, fontSize: 13, color: theme.primaryLight, fontWeight: "600" },
  composerWrap: {
    borderTopWidth: 1,
    borderTopColor: theme.border,
    backgroundColor: theme.bgSecondary,
    paddingTop: 8,
  },
  attachChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    marginHorizontal: 12,
    marginBottom: 6,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusFull,
    paddingHorizontal: 10,
    paddingVertical: 6,
    maxWidth: "85%",
  },
  attachChipText: { fontSize: 12, color: theme.text, maxWidth: 200 },
  attachBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  composer: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    paddingHorizontal: 12,
  },
  commentInput: {
    flex: 1,
    maxHeight: 100,
    backgroundColor: theme.inputBg,
    borderWidth: 1,
    borderColor: theme.inputBorder,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    color: theme.text,
    fontSize: 15,
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
  },
});
