/**
 * Config plugin: strip the expo-notifications `ExpoFirebaseMessagingService`
 * from the merged AndroidManifest so @react-native-firebase/messaging is the
 * SOLE handler of `com.google.firebase.MESSAGING_EVENT`.
 *
 * WHY: When multiple services are registered for `com.google.firebase.MESSAGING_EVENT`,
 * Android delivers each FCM message to only ONE of them. This app ships BOTH:
 *   - io.invertase.firebase.messaging.ReactNativeFirebaseMessagingService  (RN Firebase)
 *   - expo.modules.notifications.service.ExpoFirebaseMessagingService       (expo-notifications)
 *
 * If the Expo service wins, our DATA-ONLY call/message pushes are intercepted by
 * expo-notifications and silently dropped — `setBackgroundMessageHandler` /
 * `onMessage` never fire, so Notifee never renders the incoming-call screen or
 * the status-bar message notification. This was the root cause of "no push
 * notification for calls/messages" even though the WebSocket ringtone worked.
 *
 * IMPORTANT: The Expo service is declared in the expo-notifications *library*
 * manifest and added during the Gradle manifest merge — it is NOT present in the
 * app's source manifest. So we cannot simply filter it out. Instead we inject a
 * `<service android:name="..." tools:node="remove"/>` entry into the source
 * manifest, which instructs the manifest merger to delete the library-provided
 * declaration.
 *
 * We deliberately rely on @react-native-firebase/messaging + Notifee for push
 * delivery/rendering (see notifeeService / backgroundPushService), so removing
 * the Expo messaging service is safe — expo-notifications is still used for
 * permissions, channels, and badge APIs, none of which need this service.
 *
 * The `android/` folder is gitignored and regenerated by `expo prebuild`, so this
 * plugin re-applies the removal idempotently on every prebuild.
 */
const { withAndroidManifest } = require("expo/config-plugins");

const EXPO_FCM_SERVICE = "expo.modules.notifications.service.ExpoFirebaseMessagingService";

module.exports = function withRemoveExpoFirebaseMessagingService(config) {
    return withAndroidManifest(config, (config) => {
        const manifest = config.modResults?.manifest;
        const application = manifest?.application?.[0];
        if (!application) {
            return config;
        }

        // Ensure the tools namespace is declared so `tools:node` resolves.
        manifest.$ = manifest.$ || {};
        if (!manifest.$["xmlns:tools"]) {
            manifest.$["xmlns:tools"] = "http://schemas.android.com/tools";
        }

        application.service = application.service || [];

        const alreadyPresent = application.service.some(
            (service) =>
                service?.$?.["android:name"] === EXPO_FCM_SERVICE &&
                service?.$?.["tools:node"] === "remove",
        );

        if (!alreadyPresent) {
            application.service.push({
                $: {
                    "android:name": EXPO_FCM_SERVICE,
                    "tools:node": "remove",
                },
            });
            console.log(
                "[withRemoveExpoFirebaseMessagingService] Injected tools:node=remove for ExpoFirebaseMessagingService so RN Firebase owns FCM delivery.",
            );
        }

        return config;
    });
};