/**
 * Config plugin: make the main Activity capable of showing over the lock screen
 * and turning the screen on when launched.
 *
 * WHY: On Android, an incoming-call full-screen-intent notification launches the
 * app's main Activity. For the call UI to actually appear OVER the lock screen
 * (WhatsApp/Teams style) — instead of only ringing while the user is forced to
 * unlock and open the app — the Activity must call setShowWhenLocked(true) +
 * setTurnScreenOn(true) (API 27+). This avoids depending on the special
 * "Display over other apps" (SYSTEM_ALERT_WINDOW) overlay permission, which is
 * frequently greyed out / blocked by OEM ROMs (Xiaomi/Oppo/Vivo/etc.).
 *
 * The `android/` folder is gitignored and regenerated by `expo prebuild`, so the
 * manual edit in MainActivity.kt would be lost on regeneration. This plugin
 * re-applies the change idempotently during prebuild.
 */
const { withMainActivity } = require("expo/config-plugins");

const SHOW_WHEN_LOCKED_BLOCK = `
    // [withAndroidCallActivityFlags] Show over lock screen + turn screen on so
    // full-screen-intent incoming-call notifications can surface the call UI
    // over the lock screen without the SYSTEM_ALERT_WINDOW overlay permission.
    if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O_MR1) {
      setShowWhenLocked(true)
      setTurnScreenOn(true)
    } else {
      @Suppress("DEPRECATION")
      window.addFlags(
        android.view.WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED or
          android.view.WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON or
          android.view.WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON or
          android.view.WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD
      )
    }`;

module.exports = function withAndroidCallActivityFlags(config) {
    return withMainActivity(config, (config) => {
        let contents = config.modResults.contents;

        // Idempotency guard.
        if (contents.includes("[withAndroidCallActivityFlags]")) {
            return config;
        }

        // Kotlin only (Expo SDK 50+ uses Kotlin MainActivity).
        if (config.modResults.language !== "kt") {
            console.warn(
                "[withAndroidCallActivityFlags] Unsupported MainActivity language; skipping.",
            );
            return config;
        }

        // Insert right after the `super.onCreate(...)` call inside onCreate.
        const superOnCreate = /super\.onCreate\([^)]*\)/;
        const match = contents.match(superOnCreate);
        if (!match) {
            console.warn(
                "[withAndroidCallActivityFlags] Could not find super.onCreate(); skipping.",
            );
            return config;
        }

        const insertAt = match.index + match[0].length;
        contents =
            contents.slice(0, insertAt) +
            "\n" +
            SHOW_WHEN_LOCKED_BLOCK +
            contents.slice(insertAt);

        config.modResults.contents = contents;
        return config;
    });
};