#!/usr/bin/env node
/**
 * generate-emoji.mjs — Signal-style bundled emoji asset generator.
 *
 * Produces an image-based emoji set (so emoji look identical on Windows, macOS,
 * Android and iOS) from the open `emoji-datasource-apple` package — the standard
 * freely-distributable equivalent of Signal's proprietary emoji art.
 *
 * Outputs (see docs/CHAT_DESIGN_SPEC.md §1):
 *   client/public/emoji/sprite.png   — web sprite sheet (64px cells)
 *   client/public/emoji/sprite.css   — web background-position rules
 *   client/src/emoji/generated.ts    — web dataset (with sheet coords)
 *   mobile/assets/emoji/*.png        — mobile per-emoji PNGs
 *   mobile/src/emoji/generated.ts    — mobile dataset (with asset requires)
 *
 * Usage:
 *   npm i -D emoji-datasource-apple   (in the repo root or client)
 *   node scripts/generate-emoji.mjs
 *
 * If `emoji-datasource-apple` is not installed the script prints guidance and
 * exits 0 — the app still works because the curated `emojiData.ts` dataset
 * renders native unicode glyphs as a fallback.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

function tryResolveDatasource() {
    const candidates = [
        path.join(ROOT, "node_modules", "emoji-datasource-apple"),
        path.join(ROOT, "client", "node_modules", "emoji-datasource-apple"),
        path.join(ROOT, "mobile", "node_modules", "emoji-datasource-apple"),
    ];
    for (const dir of candidates) {
        if (fs.existsSync(path.join(dir, "emoji.json"))) return dir;
    }
    return null;
}

const datasource = tryResolveDatasource();
if (!datasource) {
    console.log(
        [
            "[generate-emoji] emoji-datasource-apple not found.",
            "",
            "The chat UI works today using native unicode glyphs (the curated",
            "emojiData.ts fallback). To enable the bundled image emoji set:",
            "",
            "  npm i -D emoji-datasource-apple",
            "  node scripts/generate-emoji.mjs",
            "",
            "Skipping asset generation (exit 0).",
        ].join("\n")
    );
    process.exit(0);
}

const CATEGORY_MAP = {
    "Smileys & Emotion": "smileys",
    "People & Body": "people",
    "Animals & Nature": "nature",
    "Food & Drink": "food",
    Activities: "activity",
    "Travel & Places": "travel",
    Objects: "objects",
    Symbols: "symbols",
    Flags: "flags",
};

const SIZE = 64; // emoji-datasource cell size we read from (img/apple/64)
const imgDir = path.join(datasource, "img", "apple", String(SIZE));

const raw = JSON.parse(fs.readFileSync(path.join(datasource, "emoji.json"), "utf8"));
const emojis = raw
    .filter((e) => e.has_img_apple && CATEGORY_MAP[e.category])
    .sort((a, b) => a.sort_order - b.sort_order);

function toNative(unified) {
    return unified
        .split("-")
        .map((u) => String.fromCodePoint(parseInt(u, 16)))
        .join("");
}

// ── Build dataset ──────────────────────────────────────────────────────────
const dataset = emojis.map((e) => {
    const base = {
        unified: e.unified,
        native: toNative(e.unified),
        sheetX: e.sheet_x,
        sheetY: e.sheet_y,
        image: `${e.unified}.png`,
    };
    const skins = e.skin_variations
        ? Object.values(e.skin_variations).map((v) => ({
            unified: v.unified,
            native: toNative(v.unified),
            sheetX: v.sheet_x,
            sheetY: v.sheet_y,
            image: `${v.unified}.png`,
        }))
        : undefined;
    return {
        id: e.short_name,
        name: e.name || e.short_name,
        native: base.native,
        keywords: Array.from(new Set([...(e.short_names || []), ...(e.texts || [])])),
        category: CATEGORY_MAP[e.category],
        sortOrder: e.sort_order,
        base,
        ...(skins && skins.length ? { skins } : {}),
    };
});

// ── Web: sprite sheet + css + dataset ───────────────────────────────────────
function writeWeb() {
    const outDir = path.join(ROOT, "client", "public", "emoji");
    fs.mkdirSync(outDir, { recursive: true });

    // Copy the prebuilt apple sprite that ships with the datasource package.
    const spriteSrc = path.join(datasource, "img", "apple", "sheets-clean", "64.png");
    const spriteFallback = path.join(datasource, "img", "apple", "sheets", "64.png");
    const sprite = fs.existsSync(spriteSrc) ? spriteSrc : spriteFallback;
    if (fs.existsSync(sprite)) {
        fs.copyFileSync(sprite, path.join(outDir, "sprite.png"));
    } else {
        console.warn("[generate-emoji] sprite sheet not found in datasource; web sprite skipped");
    }

    const css = [
        `/* AUTOGENERATED by scripts/generate-emoji.mjs — do not edit */`,
        `.wp-emoji{display:inline-block;width:1.25em;height:1.25em;vertical-align:-0.25em;`,
        `background-image:url("/emoji/sprite.png");background-repeat:no-repeat;`,
        `background-size:${(57 * 100).toFixed(0)}% ${(57 * 100).toFixed(0)}%;}`,
    ].join("");
    fs.writeFileSync(path.join(outDir, "sprite.css"), css);

    const ts = renderDatasetTs("web");
    const tsDir = path.join(ROOT, "client", "src", "emoji");
    fs.mkdirSync(tsDir, { recursive: true });
    fs.writeFileSync(path.join(tsDir, "generated.ts"), ts);
    console.log(`[generate-emoji] web: wrote ${dataset.length} emoji + sprite`);
}

// ── Mobile: per-emoji PNGs + dataset with require() map ──────────────────────
function writeMobile() {
    const outDir = path.join(ROOT, "mobile", "assets", "emoji");
    fs.mkdirSync(outDir, { recursive: true });
    let copied = 0;
    const allVariants = [];
    for (const e of dataset) {
        allVariants.push(e.base);
        if (e.skins) allVariants.push(...e.skins);
    }
    for (const v of allVariants) {
        const src = path.join(imgDir, v.image);
        if (fs.existsSync(src)) {
            fs.copyFileSync(src, path.join(outDir, v.image));
            copied++;
        }
    }
    const ts = renderDatasetTs("mobile");
    const tsDir = path.join(ROOT, "mobile", "src", "emoji");
    fs.mkdirSync(tsDir, { recursive: true });
    fs.writeFileSync(path.join(tsDir, "generated.ts"), ts);
    console.log(`[generate-emoji] mobile: wrote ${dataset.length} emoji, copied ${copied} PNGs`);
}

function renderDatasetTs(target) {
    const header = `// AUTOGENERATED by scripts/generate-emoji.mjs — do not edit.\n// Source: emoji-datasource-apple (Apple emoji art, open dataset).\nimport type { Emoji } from "./types";\n\n`;
    const body = `export const GENERATED_EMOJI: Emoji[] = ${JSON.stringify(dataset)};\n`;
    const flag =
        target === "mobile"
            ? `export const HAS_BUNDLED_ASSETS = true;\n`
            : `export const HAS_BUNDLED_ASSETS = true;\n`;
    return header + flag + body;
}

writeWeb();
writeMobile();
console.log("[generate-emoji] done.");