import { StyleSheet } from "react-native";
import type { Theme } from "../../src/theme";

export const makeStyles = (theme: Theme) =>
  StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.bg },
  center: { alignItems: "center", justifyContent: "center" },
  container: { padding: 16, gap: 16, paddingBottom: 48 },
  header: {
    alignItems: "center",
    gap: 6,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusLg,
    padding: 20,
  },
  icon: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: theme.primaryGlow,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  name: { fontSize: 20, fontWeight: "800", color: theme.text },
  domain: { fontSize: 13, color: theme.textMuted },
  statusPill: {
    borderRadius: theme.radiusFull,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginTop: 4,
  },
  statusText: { fontSize: 12, fontWeight: "600", textTransform: "capitalize" },
  plan: { fontSize: 13, color: theme.textSecondary, marginTop: 4 },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusLg,
    padding: 16,
  },
  stat: { flex: 1, alignItems: "center", gap: 2 },
  statValue: { fontSize: 18, fontWeight: "800", color: theme.primary },
  statLabel: {
    fontSize: 10,
    color: theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  statDivider: { width: 1, height: 28, backgroundColor: theme.border },
  infoGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  infoCard: {
    width: "47%",
    flexGrow: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    padding: 12,
  },
  infoLabel: {
    fontSize: 10,
    color: theme.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  infoValue: { fontSize: 13, fontWeight: "600", color: theme.text },
  actionsCol: { gap: 10 },
  actionBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: theme.radiusSm,
    paddingVertical: 13,
  },
  accessBtn: { backgroundColor: theme.primary },
  suspendBtn: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  deleteBtn: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  reactivateBtn: { backgroundColor: theme.success },
  actionBtnText: { fontSize: 15, fontWeight: "600" },
  settingsCard: {
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusLg,
    padding: 16,
    gap: 10,
  },
  settingsMsg: { fontSize: 13, color: theme.success },
  note: { fontSize: 12, color: theme.textSecondary, lineHeight: 17 },
  fieldLabel: {
    fontSize: 12,
    color: theme.textSecondary,
    fontWeight: "500",
    marginTop: 2,
  },
  input: {
    backgroundColor: theme.inputBg,
    borderWidth: 1,
    borderColor: theme.inputBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: theme.text,
    fontSize: 15,
  },
  inlineRow: { flexDirection: "row", gap: 10, alignItems: "center" },
  smallBtn: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  smallBtnText: { color: theme.text, fontSize: 13, fontWeight: "600" },
  saveBtn: {
    backgroundColor: theme.primary,
    borderRadius: theme.radiusSm,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 4,
  },
  saveBtnText: { color: "#fff", fontSize: 15, fontWeight: "600" },
  disabled: { opacity: 0.5 },
  featureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 4,
  },
  featureName: { fontSize: 13, color: theme.text, fontWeight: "500" },
  featurePlanDefault: { fontSize: 10, marginTop: 2 },
  segment: {
    flexDirection: "row",
    backgroundColor: theme.surface,
    borderRadius: theme.radiusSm,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    overflow: "hidden",
  },
  segmentBtn: { paddingHorizontal: 10, paddingVertical: 7 },
  segmentBtnActive: { backgroundColor: theme.primary },
  segmentText: { fontSize: 11, color: theme.textSecondary, fontWeight: "600" },
  segmentTextActive: { color: "#fff" },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  sectionTitle: { fontSize: 15, fontWeight: "700", color: theme.text },
  userCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: theme.glass,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    padding: 12,
  },
  userBody: { flex: 1, gap: 2 },
  userName: { fontSize: 14, fontWeight: "600", color: theme.text },
  userMeta: { fontSize: 12, color: theme.textSecondary },
  roleBadge: {
    backgroundColor: theme.primaryGlow,
    borderRadius: theme.radiusFull,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  roleText: { color: theme.primaryLight, fontSize: 11, fontWeight: "600" },
  privacyNote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radius,
    padding: 12,
  },
  privacyText: { flex: 1, fontSize: 12, color: theme.textMuted, lineHeight: 17 },
  empty: { color: theme.textMuted, fontSize: 13, paddingVertical: 8 },
});

export const makeMaStyles = (theme: Theme) =>
  StyleSheet.create({
  overlay: { flex: 1, justifyContent: "flex-end" },
  scrim: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  sheet: {
    backgroundColor: theme.bgElevated,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 30,
    gap: 12,
  },
  headerRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  title: { flex: 1, fontSize: 16, fontWeight: "700", color: theme.text },
  error: { fontSize: 13, color: theme.danger },
  note: { fontSize: 12, color: theme.textSecondary, lineHeight: 17 },
  meta: { fontSize: 12, color: theme.textMuted },
  fieldLabel: { fontSize: 12, color: theme.textSecondary, fontWeight: "500" },
  input: {
    backgroundColor: theme.inputBg,
    borderWidth: 1,
    borderColor: theme.inputBorder,
    borderRadius: theme.radiusSm,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: theme.text,
    fontSize: 15,
  },
  inputMultiline: { minHeight: 72, textAlignVertical: "top" },
  otpInput: {
    fontSize: 22,
    letterSpacing: 8,
    textAlign: "center",
    fontWeight: "700",
  },
  primaryBtn: {
    backgroundColor: theme.primary,
    borderRadius: theme.radiusSm,
    paddingVertical: 13,
    alignItems: "center",
  },
  primaryBtnText: { color: "#fff", fontSize: 15, fontWeight: "600" },
  secondaryBtn: {
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
    borderRadius: theme.radiusSm,
    paddingVertical: 12,
    alignItems: "center",
  },
  secondaryBtnText: { color: theme.textSecondary, fontSize: 14, fontWeight: "600" },
  dangerBtn: {
    backgroundColor: theme.danger,
    borderRadius: theme.radiusSm,
    paddingVertical: 13,
    alignItems: "center",
  },
  disabled: { opacity: 0.5 },
  glassNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 10,
    borderRadius: theme.radiusSm,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.glassBorder,
  },
  glassNoticeText: { flex: 1, fontSize: 12, color: theme.warning },
  waitTitle: { fontSize: 16, fontWeight: "700", color: theme.text },
  successRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  successText: { fontSize: 13, color: theme.success, fontWeight: "600" },
  dangerBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    padding: 12,
    borderRadius: theme.radiusSm,
    backgroundColor: theme.danger + "18",
  },
  dangerText: { flex: 1, fontSize: 12, color: theme.danger, lineHeight: 17 },
});
