/**
 * AUTO-GENERATED by scripts/gen-custom-icons.cjs — do not edit by hand.
 *
 * Custom stroke icons (path data from Lucide, ISC license) for glyphs that
 * have no Heroicons v2 equivalent. Rendered with the same props API as the
 * Heroicons components re-exported from ./index so call-sites can't tell the
 * difference: `size`, `color` (via currentColor), `strokeWidth`, `fill`,
 * `style`, plus any other react-native-svg prop.
 */
import type { ReactNode } from "react";
import Svg, { Circle as SvgCircle, Line as SvgLine, Path as SvgPath, Rect as SvgRect } from "react-native-svg";
import type { NumberProp, SvgProps } from "react-native-svg";

export interface IconProps extends SvgProps {
  size?: NumberProp;
}

const makeIcon =
  (children: ReactNode) =>
  ({ size = 24, ...props }: IconProps) => (
    <Svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="none"
      stroke="currentColor"
      strokeWidth={2}
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      {children}
    </Svg>
  );

export const Activity = makeIcon(
  <>
    <SvgPath d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2" />
  </>,
);

export const AlarmClock = makeIcon(
  <>
    <SvgCircle cx="12" cy="13" r="8" />
    <SvgPath d="M12 9v4l2 2" />
    <SvgPath d="M5 3 2 6" />
    <SvgPath d="m22 6-3-3" />
    <SvgPath d="M6.38 18.7 4 21" />
    <SvgPath d="M17.64 18.67 20 21" />
  </>,
);

export const CalendarOff = makeIcon(
  <>
    <SvgPath d="M4.2 4.2A2 2 0 0 0 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 1.82-1.18" />
    <SvgPath d="M21 15.5V6a2 2 0 0 0-2-2H9.5" />
    <SvgPath d="M16 2v4" />
    <SvgPath d="M3 10h7" />
    <SvgPath d="M21 10h-5.5" />
    <SvgPath d="m2 2 20 20" />
  </>,
);

export const CalendarPlus = makeIcon(
  <>
    <SvgPath d="M16 19h6" />
    <SvgPath d="M16 2v4" />
    <SvgPath d="M19 16v6" />
    <SvgPath d="M21 12.598V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h8.5" />
    <SvgPath d="M3 10h18" />
    <SvgPath d="M8 2v4" />
  </>,
);

export const CalendarRange = makeIcon(
  <>
    <SvgRect width="18" height="18" x="3" y="4" rx="2" />
    <SvgPath d="M16 2v4" />
    <SvgPath d="M3 10h18" />
    <SvgPath d="M8 2v4" />
    <SvgPath d="M17 14h-6" />
    <SvgPath d="M13 18H7" />
    <SvgPath d="M7 14h.01" />
    <SvgPath d="M17 18h.01" />
  </>,
);

export const CalendarX = makeIcon(
  <>
    <SvgPath d="M8 2v4" />
    <SvgPath d="M16 2v4" />
    <SvgRect width="18" height="18" x="3" y="4" rx="2" />
    <SvgPath d="M3 10h18" />
    <SvgPath d="m14 14-4 4" />
    <SvgPath d="m10 14 4 4" />
  </>,
);

export const CheckCheck = makeIcon(
  <>
    <SvgPath d="M18 6 7 17l-5-5" />
    <SvgPath d="m22 10-7.5 7.5L13 16" />
  </>,
);

export const CheckSquare = makeIcon(
  <>
    <SvgPath d="M21 10.656V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h12.344" />
    <SvgPath d="m9 11 3 3L22 4" />
  </>,
);

export const Circle = makeIcon(
  <>
    <SvgCircle cx="12" cy="12" r="10" />
  </>,
);

export const CircleDot = makeIcon(
  <>
    <SvgCircle cx="12" cy="12" r="10" />
    <SvgCircle cx="12" cy="12" r="1" />
  </>,
);

export const Coffee = makeIcon(
  <>
    <SvgPath d="M10 2v2" />
    <SvgPath d="M14 2v2" />
    <SvgPath d="M16 8a1 1 0 0 1 1 1v8a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1h14a4 4 0 1 1 0 8h-1" />
    <SvgPath d="M6 2v2" />
  </>,
);

export const Crop = makeIcon(
  <>
    <SvgPath d="M6 2v14a2 2 0 0 0 2 2h14" />
    <SvgPath d="M18 22V8a2 2 0 0 0-2-2H2" />
  </>,
);

export const Crown = makeIcon(
  <>
    <SvgPath d="M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z" />
    <SvgPath d="M5 21h14" />
  </>,
);

export const Disc = makeIcon(
  <>
    <SvgCircle cx="12" cy="12" r="10" />
    <SvgCircle cx="12" cy="12" r="2" />
  </>,
);

export const GitBranch = makeIcon(
  <>
    <SvgPath d="M15 6a9 9 0 0 0-9 9V3" />
    <SvgCircle cx="18" cy="6" r="3" />
    <SvgCircle cx="6" cy="18" r="3" />
  </>,
);

export const GitMerge = makeIcon(
  <>
    <SvgCircle cx="18" cy="18" r="3" />
    <SvgCircle cx="6" cy="6" r="3" />
    <SvgPath d="M6 21V9a9 9 0 0 0 9 9" />
  </>,
);

export const Handshake = makeIcon(
  <>
    <SvgPath d="m11 17 2 2a1 1 0 1 0 3-3" />
    <SvgPath d="m14 14 2.5 2.5a1 1 0 1 0 3-3l-3.88-3.88a3 3 0 0 0-4.24 0l-.88.88a1 1 0 1 1-3-3l2.81-2.81a5.79 5.79 0 0 1 7.06-.87l.47.28a2 2 0 0 0 1.42.25L21 4" />
    <SvgPath d="m21 3 1 11h-2" />
    <SvgPath d="M3 3 2 14l6.5 6.5a1 1 0 1 0 3-3" />
    <SvgPath d="M3 4h8" />
  </>,
);

export const Keyboard = makeIcon(
  <>
    <SvgPath d="M10 8h.01" />
    <SvgPath d="M12 12h.01" />
    <SvgPath d="M14 8h.01" />
    <SvgPath d="M16 12h.01" />
    <SvgPath d="M18 8h.01" />
    <SvgPath d="M6 8h.01" />
    <SvgPath d="M7 16h10" />
    <SvgPath d="M8 12h.01" />
    <SvgRect width="20" height="16" x="2" y="4" rx="2" />
  </>,
);

export const ListChecks = makeIcon(
  <>
    <SvgPath d="M13 5h8" />
    <SvgPath d="M13 12h8" />
    <SvgPath d="M13 19h8" />
    <SvgPath d="m3 17 2 2 4-4" />
    <SvgPath d="m3 7 2 2 4-4" />
  </>,
);

export const MicOff = makeIcon(
  <>
    <SvgPath d="M12 19v3" />
    <SvgPath d="M15 9.34V5a3 3 0 0 0-5.68-1.33" />
    <SvgPath d="M16.95 16.95A7 7 0 0 1 5 12v-2" />
    <SvgPath d="M18.89 13.23A7 7 0 0 0 19 12v-2" />
    <SvgPath d="m2 2 20 20" />
    <SvgPath d="M9 9v3a3 3 0 0 0 5.12 2.12" />
  </>,
);

export const Palmtree = makeIcon(
  <>
    <SvgPath d="M13 8c0-2.76-2.46-5-5.5-5S2 5.24 2 8h2l1-1 1 1h4" />
    <SvgPath d="M13 7.14A5.82 5.82 0 0 1 16.5 6c3.04 0 5.5 2.24 5.5 5h-3l-1-1-1 1h-3" />
    <SvgPath d="M5.89 9.71c-2.15 2.15-2.3 5.47-.35 7.43l4.24-4.25.7-.7.71-.71 2.12-2.12c-1.95-1.96-5.27-1.8-7.42.35" />
    <SvgPath d="M11 15.5c.5 2.5-.17 4.5-1 6.5h4c2-5.5-.5-12-1-14" />
  </>,
);

export const Pin = makeIcon(
  <>
    <SvgPath d="M12 17v5" />
    <SvgPath d="M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z" />
  </>,
);

export const Save = makeIcon(
  <>
    <SvgPath d="M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z" />
    <SvgPath d="M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7" />
    <SvgPath d="M7 3v4a1 1 0 0 0 1 1h7" />
  </>,
);

export const ScanFace = makeIcon(
  <>
    <SvgPath d="M3 7V5a2 2 0 0 1 2-2h2" />
    <SvgPath d="M17 3h2a2 2 0 0 1 2 2v2" />
    <SvgPath d="M21 17v2a2 2 0 0 1-2 2h-2" />
    <SvgPath d="M7 21H5a2 2 0 0 1-2-2v-2" />
    <SvgPath d="M8 14s1.5 2 4 2 4-2 4-2" />
    <SvgPath d="M9 9h.01" />
    <SvgPath d="M15 9h.01" />
  </>,
);

export const Shapes = makeIcon(
  <>
    <SvgPath d="M8.3 10a.7.7 0 0 1-.626-1.079L11.4 3a.7.7 0 0 1 1.198-.043L16.3 8.9a.7.7 0 0 1-.572 1.1Z" />
    <SvgRect x="3" y="14" width="7" height="7" rx="1" />
    <SvgCircle cx="17.5" cy="17.5" r="3.5" />
  </>,
);

export const Shield = makeIcon(
  <>
    <SvgPath d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
  </>,
);

export const SmilePlus = makeIcon(
  <>
    <SvgPath d="M22 11v1a10 10 0 1 1-9-10" />
    <SvgPath d="M8 14s1.5 2 4 2 4-2 4-2" />
    <SvgLine x1="9" x2="9.01" y1="9" y2="9" />
    <SvgLine x1="15" x2="15.01" y1="9" y2="9" />
    <SvgPath d="M16 5h6" />
    <SvgPath d="M19 2v6" />
  </>,
);

export const Sprout = makeIcon(
  <>
    <SvgPath d="M14 9.536V7a4 4 0 0 1 4-4h1.5a.5.5 0 0 1 .5.5V5a4 4 0 0 1-4 4 4 4 0 0 0-4 4c0 2 1 3 1 5a5 5 0 0 1-1 3" />
    <SvgPath d="M4 9a5 5 0 0 1 8 4 5 5 0 0 1-8-4" />
    <SvgPath d="M5 21h14" />
  </>,
);

export const StickyNote = makeIcon(
  <>
    <SvgPath d="M21 9a2.4 2.4 0 0 0-.706-1.706l-3.588-3.588A2.4 2.4 0 0 0 15 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2z" />
    <SvgPath d="M15 3v5a1 1 0 0 0 1 1h5" />
  </>,
);

export const SwitchCamera = makeIcon(
  <>
    <SvgPath d="M11 19H4a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h5" />
    <SvgPath d="M13 5h7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-5" />
    <SvgCircle cx="12" cy="12" r="3" />
    <SvgPath d="m18 22-3-3 3-3" />
    <SvgPath d="m6 2 3 3-3 3" />
  </>,
);

export const Target = makeIcon(
  <>
    <SvgCircle cx="12" cy="12" r="10" />
    <SvgCircle cx="12" cy="12" r="6" />
    <SvgCircle cx="12" cy="12" r="2" />
  </>,
);

export const Thermometer = makeIcon(
  <>
    <SvgPath d="M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z" />
  </>,
);

export const Timer = makeIcon(
  <>
    <SvgLine x1="10" x2="14" y1="2" y2="2" />
    <SvgLine x1="12" x2="15" y1="14" y2="11" />
    <SvgCircle cx="12" cy="14" r="8" />
  </>,
);

export const ToggleLeft = makeIcon(
  <>
    <SvgCircle cx="9" cy="12" r="3" />
    <SvgRect width="20" height="14" x="2" y="5" rx="7" />
  </>,
);

export const ToggleRight = makeIcon(
  <>
    <SvgCircle cx="15" cy="12" r="3" />
    <SvgRect width="20" height="14" x="2" y="5" rx="7" />
  </>,
);

export const UserCheck = makeIcon(
  <>
    <SvgPath d="m16 11 2 2 4-4" />
    <SvgPath d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
    <SvgCircle cx="9" cy="7" r="4" />
  </>,
);

export const UserCog = makeIcon(
  <>
    <SvgPath d="M10 15H6a4 4 0 0 0-4 4v2" />
    <SvgPath d="m14.305 16.53.923-.382" />
    <SvgPath d="m15.228 13.852-.923-.383" />
    <SvgPath d="m16.852 12.228-.383-.923" />
    <SvgPath d="m16.852 17.772-.383.924" />
    <SvgPath d="m19.148 12.228.383-.923" />
    <SvgPath d="m19.53 18.696-.382-.924" />
    <SvgPath d="m20.772 13.852.924-.383" />
    <SvgPath d="m20.772 16.148.924.383" />
    <SvgCircle cx="18" cy="15" r="3" />
    <SvgCircle cx="9" cy="7" r="4" />
  </>,
);

export const Workflow = makeIcon(
  <>
    <SvgRect width="8" height="8" x="3" y="3" rx="2" />
    <SvgPath d="M7 11v4a2 2 0 0 0 2 2h4" />
    <SvgRect width="8" height="8" x="13" y="13" rx="2" />
  </>,
);

