/**
 * Central icon module — single source of truth for every icon in the app.
 *
 * Icons are Heroicons v2 outline (react-native-heroicons, MIT) re-exported
 * under the lucide-react-native names the codebase already uses, so call
 * sites keep the same `<Send size={20} color="#fff" />` API. Glyphs with no
 * Heroicons equivalent live in ./custom.tsx (auto-generated stroke SVGs).
 *
 * To swap or tweak any icon app-wide, change its mapping here — never at the
 * call sites.
 */
import type { ComponentType } from "react";
import type { NumberProp, SvgProps } from "react-native-svg";

/** Props accepted by every icon component (Heroicons + custom). */
export interface IconProps extends SvgProps {
  size?: NumberProp;
}

/**
 * Back-compat alias for code that typed icons as `LucideIcon`
 * (e.g. src/notes/templates.ts, src/constants/leaves.ts).
 */
export type LucideIcon = ComponentType<IconProps>;

// ---------------------------------------------------------------------------
// Heroicons v2 (outline) mapped to the lucide names used across the app.
// ---------------------------------------------------------------------------
export {
  AdjustmentsHorizontalIcon as Settings2,
  AdjustmentsHorizontalIcon as SlidersHorizontal,
  ArchiveBoxArrowDownIcon as ArchiveRestore,
  ArchiveBoxIcon as Archive,
  ArrowDownTrayIcon as Download,
  ArrowUpTrayIcon as Upload,
  ArrowLeftIcon as ArrowLeft,
  ArrowPathIcon as Loader2,
  ArrowPathIcon as RefreshCw,
  ArrowPathRoundedSquareIcon as Repeat,
  ArrowRightIcon as ArrowRight,
  ArrowRightStartOnRectangleIcon as LogOut,
  ArrowsPointingInIcon as Minimize2,
  ArrowTrendingUpIcon as TrendingUp,
  ArrowUpRightIcon as ArrowUpRight,
  ArrowUturnLeftIcon as CornerUpLeft,
  ArrowUturnLeftIcon as RotateCcw,
  ArrowUturnRightIcon as Forward,
  ArrowUturnRightIcon as RotateCw,
  BackspaceIcon as Delete,
  Bars3Icon as Menu,
  BeakerIcon as FlaskConical,
  BellAlertIcon as BellDot,
  BellIcon as Bell,
  BellSlashIcon as BellOff,
  BoltIcon as Zap,
  BoltSlashIcon as ZapOff,
  BookmarkSquareIcon as BookMarked,
  BugAntIcon as Bug,
  BuildingOffice2Icon as Building2,
  BuildingOfficeIcon as Building,
  CalendarDaysIcon as CalendarDays,
  CalendarIcon as Calendar,
  CameraIcon as Camera,
  ChartBarIcon as BarChart3,
  ChartPieIcon as PieChart,
  ChatBubbleLeftIcon as MessageSquare,
  ChatBubbleLeftRightIcon as MessagesSquare,
  CheckCircleIcon as CheckCircle2,
  CheckIcon as Check,
  ChevronDownIcon as ChevronDown,
  ChevronLeftIcon as ChevronLeft,
  ChevronRightIcon as ChevronRight,
  ChevronUpIcon as ChevronUp,
  CircleStackIcon as Database,
  ClipboardDocumentCheckIcon as ClipboardCheck,
  ClipboardDocumentListIcon as ClipboardList,
  ClockIcon as Clock,
  ClockIcon as Clock3,
  Cog6ToothIcon as Settings,
  CreditCardIcon as CreditCard,
  CurrencyDollarIcon as DollarSign,
  DocumentPlusIcon as FilePlus,
  DocumentTextIcon as FileText,
  DocumentTextIcon as ScrollText,
  EllipsisVerticalIcon as MoreVertical,
  EnvelopeIcon as Mail,
  EnvelopeOpenIcon as MailOpen,
  ExclamationCircleIcon as BadgeAlert,
  ExclamationTriangleIcon as AlertTriangle,
  EyeIcon as Eye,
  EyeSlashIcon as EyeOff,
  FaceSmileIcon as Smile,
  FilmIcon as Film,
  FingerPrintIcon as Fingerprint,
  FlagIcon as Flag,
  FolderIcon as Folder,
  FolderOpenIcon as FolderOpen,
  FolderPlusIcon as FolderPlus,
  GlobeAltIcon as Globe,
  HandRaisedIcon as Hand,
  HeartIcon as Heart,
  HomeIcon as Home,
  HomeIcon as House,
  InboxIcon as Inbox,
  KeyIcon as KeyRound,
  LifebuoyIcon as LifeBuoy,
  LinkIcon,
  LockClosedIcon as Lock,
  MagnifyingGlassIcon as Search,
  MapPinIcon as MapPin,
  MegaphoneIcon as Megaphone,
  MicrophoneIcon as Mic,
  MinusIcon as Minus,
  NoSymbolIcon as Ban,
  PaperAirplaneIcon as Send,
  PaperClipIcon as Paperclip,
  PauseIcon as Pause,
  PencilIcon as Edit3,
  PencilIcon as Pencil,
  PencilSquareIcon as FileEdit,
  PhoneArrowDownLeftIcon as PhoneIncoming,
  PhoneArrowUpRightIcon as PhoneOutgoing,
  PhoneIcon as Phone,
  PhoneXMarkIcon as PhoneMissed,
  PhoneXMarkIcon as PhoneOff,
  PhotoIcon as Image,
  PhotoIcon as Images,
  PlayIcon as Play,
  PlusIcon as Plus,
  QuestionMarkCircleIcon as HelpCircle,
  ReceiptPercentIcon as Receipt,
  RectangleGroupIcon as LayoutTemplate,
  RocketLaunchIcon as Rocket,
  ServerIcon as Server,
  ServerStackIcon as HardDrive,
  ShareIcon as Share2,
  ShieldCheckIcon as ShieldCheck,
  ShieldExclamationIcon as ShieldAlert,
  SignalIcon as Signal,
  SparklesIcon as Sparkles,
  SpeakerWaveIcon as Volume1,
  SpeakerWaveIcon as Volume2,
  Square2StackIcon as Copy,
  Squares2X2Icon as LayoutDashboard,
  StarIcon as Star,
  SwatchIcon as Palette,
  TagIcon as Tag,
  TrashIcon as Trash2,
  UserGroupIcon as UsersRound,
  UserIcon as User,
  UserPlusIcon as UserPlus,
  UsersIcon as Users,
  VideoCameraIcon as Video,
  VideoCameraSlashIcon as VideoOff,
  WalletIcon as Wallet,
  WifiIcon as Wifi,
  WrenchIcon as Wrench,
  XCircleIcon as XCircle,
  XMarkIcon as X,
} from "react-native-heroicons/outline";

// ---------------------------------------------------------------------------
// Custom stroke icons — glyphs Heroicons doesn't ship (see ./custom.tsx).
// ---------------------------------------------------------------------------
export {
  Activity,
  AlarmClock,
  CalendarOff,
  CalendarPlus,
  CalendarRange,
  CalendarX,
  CheckCheck,
  CheckSquare,
  Circle,
  CircleDot,
  Coffee,
  Crop,
  Crown,
  Disc,
  GitBranch,
  GitMerge,
  Handshake,
  Keyboard,
  ListChecks,
  MicOff,
  Palmtree,
  Pin,
  Save,
  ScanFace,
  Shapes,
  Shield,
  SmilePlus,
  Sprout,
  StickyNote,
  SwitchCamera,
  Target,
  Thermometer,
  Timer,
  ToggleLeft,
  ToggleRight,
  UserCheck,
  UserCog,
  Workflow,
} from "./custom";