/**
 * Generate app icons from the master brand artwork.
 * Run: node generate-icons.js
 * Requires: sharp + png-to-ico (dev dependencies)
 *
 * The single source of truth for the WorkPulse brand mark is
 * `icons/icon-source.png` (a high-resolution square PNG). Every other raster
 * size — plus the Windows .ico — is derived from it here so a brand refresh is
 * a one-file swap followed by re-running the generators (desktop + mobile +
 * client).
 */
import sharp from "sharp";
import pngToIco from "png-to-ico";
import path from "path";
import fs from "fs";

const SOURCE_PATH = path.join(__dirname, "icons", "icon-source.png");
const ICONS_DIR = path.join(__dirname, "icons");

async function generate(): Promise<void> {
  if (!fs.existsSync(SOURCE_PATH)) {
    throw new Error(`Source artwork not found: ${SOURCE_PATH}`);
  }
  const source = fs.readFileSync(SOURCE_PATH);

  // Generate PNG at multiple sizes (for Linux icon set + general use)
  const sizes = [16, 32, 48, 64, 128, 256, 512];
  for (const size of sizes) {
    await sharp(source)
      .resize(size, size, { fit: "cover" })
      .png()
      .toFile(path.join(ICONS_DIR, `${size}x${size}.png`));
    console.log(`  ✓ ${size}x${size}.png`);
  }

  // Main icon.png (256x256 — used by Electron window/tray/PiP + Linux)
  await sharp(source)
    .resize(256, 256, { fit: "cover" })
    .png()
    .toFile(path.join(ICONS_DIR, "icon.png"));
  console.log("  ✓ icon.png (256x256)");

  // Windows .ico — a real multi-resolution icon (16/32/48/64/128/256). While
  // electron-builder can synthesize one from icon.png, shipping a proper .ico
  // keeps the file-explorer / shortcut icons crisp at every size.
  const icoSizes = [16, 32, 48, 64, 128, 256];
  const icoBuffers = await Promise.all(
    icoSizes.map((size) =>
      sharp(source).resize(size, size, { fit: "cover" }).png().toBuffer(),
    ),
  );
  const ico = await pngToIco(icoBuffers);
  fs.writeFileSync(path.join(ICONS_DIR, "icon.ico"), ico);
  console.log("  ✓ icon.ico (16–256 multi-res)");

  console.log("\nDone! Desktop icons regenerated from icons/icon-source.png");
  console.log(
    "  macOS .icns is auto-generated by electron-builder from icon.png.",
  );
}

generate().catch((err) => {
  console.error("Icon generation failed:", err);
  process.exit(1);
});
