/**
 * Generate app icons from the master brand artwork.
 * Run: node generate-icons.js
 * Requires: sharp + png-to-ico (dev dependencies)
 *
 * The single source of truth for the AINO brand mark is
 * `icons/icon-source.png` (a high-resolution square PNG). Every other raster
 * size — plus the Windows .ico — is derived from it here so a brand refresh is
 * a one-file swap followed by re-running the generators (desktop + mobile +
 * client).
 */
import sharp from "sharp";
import pngToIco from "png-to-ico";
import path from "path";
import fs from "fs";

const SOURCE_PATH = path.join(__dirname, "icons", "icon-source.png");
const ICONS_DIR = path.join(__dirname, "icons");

/**
 * Render the master artwork down to a square `size` PNG buffer with maximum
 * fidelity. Two things make small icons look crisp rather than "cheap":
 *   1. Lanczos3 resampling (sharp's highest-quality downscale kernel).
 *   2. A mild, size-proportional unsharp mask on the small bitmaps (≤ 64px).
 *      Heavy downscaling softens fine logo detail; a gentle sharpen restores
 *      edge definition without the halos a stronger amount would introduce.
 * The PNG is written lossless (compressionLevel 9) so nothing is degraded.
 */
async function renderPng(source: Buffer, size: number): Promise<Buffer> {
  let pipeline = sharp(source).resize(size, size, {
    fit: "cover",
    kernel: "lanczos3",
  });
  if (size <= 64) {
    pipeline = pipeline.sharpen({ sigma: 0.6 });
  }
  return pipeline.png({ compressionLevel: 9, quality: 100 }).toBuffer();
}

async function generate(): Promise<void> {
  if (!fs.existsSync(SOURCE_PATH)) {
    throw new Error(`Source artwork not found: ${SOURCE_PATH}`);
  }
  const source = fs.readFileSync(SOURCE_PATH);

  // Generate PNG at multiple sizes (for Linux icon set + general use)
  const sizes = [16, 32, 48, 64, 128, 256, 512];
  for (const size of sizes) {
    const buf = await renderPng(source, size);
    fs.writeFileSync(path.join(ICONS_DIR, `${size}x${size}.png`), buf);
    console.log(`  ✓ ${size}x${size}.png`);
  }

  // Main icon.png (512x512 — used by the Electron window on macOS/Linux + PiP,
  // and as electron-builder's source icon for the macOS/Windows targets).
  // It MUST stay >= 512x512: electron-builder rejects a smaller image when
  // packaging the macOS app ("image ... must be at least 512x512").
  fs.writeFileSync(
    path.join(ICONS_DIR, "icon.png"),
    await renderPng(source, 512),
  );
  console.log("  ✓ icon.png (512x512)");

  // Dedicated, pre-sharpened system-tray bitmaps. Electron's runtime
  // nativeImage.resize() is a low-quality scaler, so downscaling the 256px
  // icon to 16px on the fly produced the blurry tray/taskbar mark. Shipping a
  // crisp 16px base plus a 32px `@2x` representation (auto-loaded by
  // nativeImage.createFromPath on HiDPI displays) keeps the tray icon sharp.
  fs.writeFileSync(
    path.join(ICONS_DIR, "tray.png"),
    await renderPng(source, 16),
  );
  fs.writeFileSync(
    path.join(ICONS_DIR, "tray@2x.png"),
    await renderPng(source, 32),
  );
  console.log("  ✓ tray.png + tray@2x.png (16/32 sharpened)");

  // Windows .ico — a real multi-resolution icon. Including the in-between
  // taskbar DPI steps (20/24/40) on top of the usual 16/32/48/… means Windows
  // can pick a hand-rendered bitmap for the exact pixel size it needs instead
  // of runtime-downscaling a single large image (the root cause of the
  // "cheap"-looking taskbar icon).
  const icoSizes = [16, 20, 24, 32, 40, 48, 64, 128, 256];
  const icoBuffers = await Promise.all(
    icoSizes.map((size) => renderPng(source, size)),
  );
  const ico = await pngToIco(icoBuffers);
  fs.writeFileSync(path.join(ICONS_DIR, "icon.ico"), ico);
  console.log("  ✓ icon.ico (16–256 multi-res, taskbar DPI steps included)");

  console.log("\nDone! Desktop icons regenerated from icons/icon-source.png");
  console.log(
    "  macOS .icns is auto-generated by electron-builder from icon.png.",
  );
}

generate().catch((err) => {
  console.error("Icon generation failed:", err);
  process.exit(1);
});
